/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void sub_1160();
// int __fastcall _cxa_finalize(void *);
// int __fastcall _cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle);
// int __fastcall _register_atfork(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
// void *malloc(size_t size);
// void __fastcall _aeabi_memclr4(void *, size_t); idb
// int __fastcall socket_local_client(int a1, int a2, int a3);
// int pthread_mutex_init(pthread_mutex_t *mutex, const pthread_mutexattr_t *mutexattr);
// int pipe(int pipedes[2]);
// int pthread_create(pthread_t *newthread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg);
// int close(int fd);
// void free(void *ptr);
// int __fastcall _FD_SET_chk(_DWORD, _DWORD, _DWORD); weak
// int select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval *timeout);
// int __fastcall _FD_ISSET_chk(_DWORD, _DWORD, _DWORD); weak
// int __fastcall _read_chk(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// int usleep(__useconds_t useconds);
// unsigned int sleep(unsigned int seconds);
int __fastcall j_RILC_Reconnect(int);
// int pthread_join(pthread_t th, void **thread_return);
// int __fastcall _write_chk(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int _errno(void); weak
// void __fastcall _aeabi_memcpy(void *, const void *, size_t); idb
// void __fastcall operator delete(void *); idb
void *__fastcall ProductFeature::GetInstance(ProductFeature *this);
// int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...); weak
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
int __fastcall ProductFeature::Function_GetFastDormancyInfo(ProductFeature *this, unsigned __int8 *a2, unsigned __int8 *a3, unsigned __int8 *a4, unsigned __int8 *a5);
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this);
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this);
void __fastcall ProductFeature::ProductFeature(ProductFeature *this);
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2);
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this);
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// void __fastcall _aeabi_memclr8(void *, size_t); idb
// int __fastcall dladdr(_DWORD, _DWORD); weak
// int _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, const char *, ...); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_13DC();
int (*__fastcall sub_13FC(int (*result)(void)))(void);
int __fastcall sub_1428(void *a1);
int __fastcall sub_1474(int a1, int a2, int a3);
char *RILC_Open();
int __fastcall sub_1600(int *a1);
int __fastcall sub_1A5C(int *a1);
int __fastcall RILC_Reconnect(int a1);
int __fastcall RILC_Close(int *a1);
int __fastcall RILC_RegisterUnsolicitedHandler(int a1, int a2);
int __fastcall RILC_Send(_DWORD *a1, int a2, const void *a3, size_t a4, int a5, int a6);
void __fastcall ProductFeature::ProductFeature(ProductFeature *this);
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
int __fastcall ProductFeature::Init(ProductFeature *this, const char *a2);
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this);
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this);
int __fastcall ProductFeature::Function_SendDebugTraceOffAtBootup(ProductFeature *this);
int __fastcall ProductFeature::Function_GetFastDormancyInfo(ProductFeature *this, unsigned __int8 *a2, unsigned __int8 *a3, unsigned __int8 *a4, unsigned __int8 *a5);
int __fastcall ProductFeature::Function_RilResetByCrashExitInUserMode(ProductFeature *this);
int __fastcall ProductFeature::Function_DeviceBasedCwInCs(ProductFeature *this);
const char *sub_2188();
const char *sub_2194();
void *__fastcall ProductFeature::GetInstance(ProductFeature *this);
void __fastcall CustomProductFeature::CustomProductFeature(CustomProductFeature *this);
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2);
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this);
int __fastcall CustomProductFeature::Custom_SaveImeiToProperty(CustomProductFeature *this);
int __fastcall CustomProductFeature::Custom_ReturnCurrentPlmn(CustomProductFeature *this);
int __fastcall CustomProductFeature::ModuleAudio_VolumeStartFrom1(CustomProductFeature *this);
const char *sub_22AC();
const char *sub_22B8();
unsigned int *__fastcall sub_22C4(unsigned int *result, int *a2, int *a3);
int __fastcall sub_2318(int a1, int a2, unsigned int a3, unsigned int a4);
int __fastcall sub_265C(int a1, int a2, unsigned int a3, int a4, int *a5);
int __fastcall sub_26F8(int a1, int a2, unsigned int a3, int a4);
int __fastcall sub_2834(int a1, int a2, int a3);
int __fastcall sub_283C(int a1, int a2);
int __fastcall sub_2898(int a1, int a2, int a3);
int __fastcall sub_28A0(int a1, int a2, int a3);
int __fastcall sub_28A8(int *a1, int a2, int a3, int a4);
int __fastcall sub_2954(const void *a1, int *a2, char a3);
void __fastcall __noreturn sub_2A40(int *a1, int a2, int a3, int a4);
void __fastcall __noreturn sub_2A74(const char *a1, int a2, const char *a3);
int __fastcall sub_2AA4(int a1);
int __fastcall sub_2AE0(int a1);
int __fastcall sub_2B28(int a1, int a2);
int __fastcall sub_2B3C(_DWORD *a1, int a2, int a3, int a4, int a5);
_QWORD *__fastcall sub_2B54(_QWORD *result);
_QWORD *__fastcall sub_2B5C(_QWORD *result);
_QWORD *__fastcall sub_2B64(_QWORD *result);
void sub_2B6C();
void sub_2BB0();
int __fastcall sub_2BC4(int a1, const void *a2);
int __fastcall sub_2C08(int a1, int a2, _DWORD *a3);
int __fastcall sub_2C36(int a1, int a2, int a3);
int __fastcall sub_2C7A(int a1, int a2, _QWORD *a3);
int __fastcall sub_2CAA(int a1, int a2, int a3, int a4);
int __fastcall sub_2CE2(int a1);
int __fastcall sub_2CE8(int a1, int a2);
int __fastcall sub_2D06(int a1);
int __fastcall sub_2D18(int a1);
int __fastcall sub_2D1E(int a1, int a2);
int __fastcall sub_2D40(int a1, int a2);
int __fastcall sub_2DCC(int result, int a2, int a3);
int __fastcall sub_2E58(int a1, int a2);
__int64 __fastcall sub_2E7C(int a1, int a2);
int __fastcall sub_2F20(int a1, int a2, int a3, int a4);
int __fastcall sub_2FEC(_DWORD *a1);
_DWORD *__fastcall sub_303C(int a1, _DWORD *a2);
int __fastcall sub_3054(int a1);
int __fastcall sub_306A(int a1);
int __fastcall sub_3070(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_30E0(int *a1, int a2);
int __fastcall sub_3156(int result);
void __fastcall __noreturn sub_3160(const char *a1, const char *a2, int a3, const char *a4);
int __fastcall sub_318C(int a1);
_DWORD *__fastcall sub_31E0(int a1);
int __fastcall sub_3238(int *a1, int a2, _DWORD *a3);
_DWORD *__fastcall sub_33DC(_DWORD *a1, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int __fastcall sub_386C(int a1);
void sub_3880();
void sub_3888();
void sub_3890();
_DWORD *__fastcall sub_3898(int *a1);
_DWORD *__fastcall sub_38DC(int *a1);
void __fastcall operator delete(void *); // idb
void __fastcall j_ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
int __fastcall j___cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle);
int __fastcall sub_3920(int a1);
_DWORD *__fastcall sub_3930(int *a1);
// int __fastcall socket_local_client(_DWORD, _DWORD, _DWORD); weak

//-------------------------------------------------------------------------
// Data declarations

char byte_4 = '\x01'; // weak
void *off_5D40 = (void *)0x2031; // weak
void *off_5D6C = (void *)0x21C5; // weak
void *off_5D98 = (void *)0x2031; // weak
void *off_6000 = &off_6000; // weak
_UNKNOWN instance; // weak
_UNKNOWN unk_6008; // weak
// extern _UNKNOWN _stack_chk_guard; weak
// extern struct _IO_FILE *stderr;


//----- (00001160) --------------------------------------------------------
void sub_1160()
{
  JUMPOUT(0);
}
// 116C: control flows out of bounds to 0

//----- (00001270) --------------------------------------------------------
// attributes: thunk
int __fastcall j_RILC_Reconnect(int a1)
{
  return RILC_Reconnect(a1);
}

//----- (000012B8) --------------------------------------------------------
// attributes: thunk
void *__fastcall ProductFeature::GetInstance(ProductFeature *this)
{
  return _ZN14ProductFeature11GetInstanceEv(this);
}

//----- (000012D0) --------------------------------------------------------
// attributes: thunk
void __fastcall ProductFeature::~ProductFeature(ProductFeature *this)
{
  _ZN14ProductFeatureD2Ev(this);
}

//----- (000012DC) --------------------------------------------------------
// attributes: thunk
void __fastcall ProductFeature::~ProductFeature(ProductFeature *this)
{
  _ZN14ProductFeatureD0Ev(this);
}

//----- (000012F4) --------------------------------------------------------
// attributes: thunk
int __fastcall ProductFeature::Function_GetFastDormancyInfo(
        ProductFeature *this,
        unsigned __int8 *a2,
        unsigned __int8 *a3,
        unsigned __int8 *a4,
        unsigned __int8 *a5)
{
  return _ZN14ProductFeature28Function_GetFastDormancyInfoERhS0_S0_S0_(this, a2, a3, a4, a5);
}

//----- (00001300) --------------------------------------------------------
// attributes: thunk
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this)
{
  return _ZN14ProductFeature23Custom_SupportOnly5ModeEv(this);
}

//----- (0000130C) --------------------------------------------------------
// attributes: thunk
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this)
{
  return _ZN14ProductFeature43Custom_SupportOnlyBasicPreferredNetworkTypeEv(this);
}

//----- (00001318) --------------------------------------------------------
// attributes: thunk
void __fastcall ProductFeature::ProductFeature(ProductFeature *this)
{
  _ZN14ProductFeatureC2Ev(this);
}

//----- (00001324) --------------------------------------------------------
// attributes: thunk
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *this)
{
  _ZN20CustomProductFeatureD2Ev(this);
}

//----- (00001330) --------------------------------------------------------
// attributes: thunk
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *this)
{
  _ZN20CustomProductFeatureD0Ev(this);
}

//----- (0000133C) --------------------------------------------------------
// attributes: thunk
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2)
{
  return _ZN20CustomProductFeature10CustomInitEPKc(this, a2);
}

//----- (00001348) --------------------------------------------------------
// attributes: thunk
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this)
{
  return _ZN20CustomProductFeature14GetProductNameEv(this);
}

//----- (000013DC) --------------------------------------------------------
int sub_13DC()
{
  return _cxa_finalize(&off_6000);
}
// 6000: using guessed type void *off_6000;

//----- (000013FC) --------------------------------------------------------
int (*__fastcall sub_13FC(int (*result)(void)))(void)
{
  if ( result )
    return (int (*)(void))result();
  return result;
}

//----- (00001428) --------------------------------------------------------
int __fastcall sub_1428(void *a1)
{
  return _cxa_atexit((void (__fastcall *)(void *))sub_13FC, a1, &off_6000);
}
// 6000: using guessed type void *off_6000;

//----- (00001474) --------------------------------------------------------
int __fastcall sub_1474(int a1, int a2, int a3)
{
  return _register_atfork(a1, a2, a3, &off_6000);
}
// 118C: using guessed type int __fastcall _register_atfork(_DWORD, _DWORD, _DWORD, _DWORD);
// 6000: using guessed type void *off_6000;

//----- (000014BC) --------------------------------------------------------
char *RILC_Open()
{
  char *v0; // r0
  char *v1; // r4
  int i; // r0
  char *v3; // r2
  int v4; // r0

  _android_log_print(3, "RILClient", "[OemClient] %s", "RILC_Open");
  v0 = (char *)malloc(0x89Cu);
  v1 = v0;
  if ( v0 )
  {
    memset(v0, 0, 0x89Cu);
    for ( i = 0; i != 255; ++i )
    {
      v3 = &v1[8 * i];
      *((_DWORD *)v3 + 41) = -1;
    }
    v4 = socket_local_client("RIL-CLIENT", 0, 1);
    *(_DWORD *)v1 = v4;
    if ( v4 < 0 )
    {
      _android_log_print(6, "RILClient", "[OemClient] Failed to connect to RIL socket");
    }
    else
    {
      pthread_mutex_init((pthread_mutex_t *)(v1 + 152), 0);
      if ( pipe((int *)v1 + 2) <= -1 )
      {
        _android_log_print(6, "RILClient", "%s: fail to create pipe.", "RILC_Open");
      }
      else
      {
        if ( !pthread_create((pthread_t *)v1 + 36, 0, (void *(*)(void *))sub_1600, v1) )
        {
          pthread_create((pthread_t *)v1 + 37, 0, (void *(*)(void *))sub_1A5C, v1);
          _android_log_print(3, "RILClient", "[OemClient] Client created %p", v1);
          return v1;
        }
        _android_log_print(6, "RILClient", "[OemClient] Failed to create reader thread");
      }
      close(*((_DWORD *)v1 + 2));
      close(*((_DWORD *)v1 + 3));
      close(*(_DWORD *)v1);
    }
    free(v1);
    return 0;
  }
  else
  {
    _android_log_print(6, "RILClient", "[OemClient] Failed to allocate memory for client");
    return 0;
  }
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 11BC: using guessed type int __fastcall socket_local_client(_DWORD, _DWORD, _DWORD);
// 1600: using guessed type int sub_1600();
// 1A5C: using guessed type int sub_1A5C();

//----- (00001600) --------------------------------------------------------
int __fastcall sub_1600(int *a1)
{
  int v2; // r1
  int v3; // r11
  unsigned int v4; // r1
  int v5; // r0
  int v6; // r0
  unsigned int v7; // r8
  void *v8; // r1
  int chk; // r3
  void *v10; // r0
  void (__fastcall *v11)(int, unsigned int, unsigned int, _DWORD); // r8
  unsigned int v12; // r1
  void (__fastcall *v13)(int, int, unsigned int); // r9
  unsigned int v14; // r2
  void (__fastcall *v15)(int, _DWORD, _DWORD, _DWORD); // r5
  void (__fastcall *v17)(int, _DWORD, _DWORD, _DWORD); // r5
  int *v18; // [sp+10h] [bp-48h]
  pthread_mutex_t *mutex; // [sp+14h] [bp-44h]
  void *ptr; // [sp+18h] [bp-40h]
  unsigned __int8 v21; // [sp+1Ch] [bp-3Ch] BYREF
  unsigned int v22; // [sp+1Dh] [bp-3Bh]
  int v23; // [sp+21h] [bp-37h]
  int v24; // [sp+25h] [bp-33h]
  unsigned int v25; // [sp+29h] [bp-2Fh]

  if ( !a1 )
    return 0;
  _android_log_print(3, "RILClient", "[OemClient] %s", "RILC_Reader");
  v2 = a1[2];
  v18 = a1 + 41;
  mutex = (pthread_mutex_t *)(a1 + 38);
  if ( *a1 > v2 )
    v2 = *a1;
  v3 = v2 + 1;
LABEL_6:
  v4 = 0;
  while ( 1 )
  {
    do
    {
      while ( v4 <= 0x1F )
        a1[v4++ + 4] = 0;
      _FD_SET_chk(*a1, a1 + 4, 128);
      _FD_SET_chk(a1[2], a1 + 4, 128);
      if ( select(v3, (fd_set *)(a1 + 4), 0, 0, 0) <= 0 )
      {
        _android_log_print(6, "RILClient", "%s : error return in select", "RILC_Reader");
        goto LABEL_6;
      }
      if ( _FD_ISSET_chk(a1[2], a1 + 4, 128) )
      {
        _android_log_print(3, "RILClient", "[OemClient] %s : thread end", "RILC_Reader");
        return 0;
      }
      v5 = _FD_ISSET_chk(*a1, a1 + 4, 128);
      v4 = 0;
    }
    while ( !v5 );
    _android_log_print(3, "RILClient", "%s : something we got", "RILC_Reader");
    v6 = _read_chk(*a1, &v21, 17, 17);
    if ( v6 <= 0 )
      break;
    if ( v6 != 17 )
    {
      _android_log_print(6, "RILClient", "[OemClient] Could not read full header");
      goto LABEL_6;
    }
    _android_log_print(
      3,
      "RILClient",
      "[OemClient] RES (t = %d, id = %d, res = %d, len = %d channel = %d)",
      v22,
      v23,
      v24,
      v25,
      v21);
    v7 = v25;
    if ( !v25 )
    {
      ptr = 0;
      goto LABEL_21;
    }
    if ( v25 <= 0x1000 )
    {
      v8 = malloc(v25 + 1);
      if ( v8 )
      {
        ptr = v8;
        chk = _read_chk(*a1, v8, v7, -1);
        if ( chk <= 0 )
        {
          _android_log_print(6, "RILClient", "[OemClient] Disconnected (data)");
          v17 = (void (__fastcall *)(int, _DWORD, _DWORD, _DWORD))a1[39];
          pthread_mutex_lock(mutex);
          close(*a1);
          *a1 = -1;
          pthread_mutex_unlock(mutex);
          if ( v17 && !a1[1] )
            v17(1000, 0, 0, 0);
          return 0;
        }
        if ( chk == v25 )
        {
LABEL_21:
          if ( v22 == -1 )
          {
            pthread_mutex_lock(mutex);
            v11 = (void (__fastcall *)(int, unsigned int, unsigned int, _DWORD))a1[39];
            pthread_mutex_unlock(mutex);
            if ( v11 && !a1[1] )
            {
              v12 = v25;
              if ( v25 )
                v12 = (unsigned int)ptr;
              v11(v23, v12, v25, v21);
            }
            v4 = 0;
            v10 = ptr;
            if ( ptr )
            {
LABEL_42:
              free(v10);
              goto LABEL_6;
            }
          }
          else if ( v22 < 0xFF )
          {
            pthread_mutex_lock(mutex);
            if ( v18[2 * v22] == v23 )
            {
              v13 = (void (__fastcall *)(int, int, unsigned int))v18[2 * v22 + 1];
              v18[2 * v22] = -1;
              pthread_mutex_unlock(mutex);
              if ( v13 )
              {
                v14 = v25;
                if ( v25 )
                  v14 = (unsigned int)ptr;
                v13(v23, v24, v14);
              }
              v10 = ptr;
              v4 = 0;
              if ( ptr )
                goto LABEL_42;
            }
            else
            {
              pthread_mutex_unlock(mutex);
              _android_log_print(
                6,
                "RILClient",
                "[OemClient] MsgId mismatch. Was = %d, received = %d",
                v18[2 * v22],
                v23);
              v4 = 0;
              v10 = ptr;
              if ( ptr )
                goto LABEL_42;
            }
          }
          else
          {
            _android_log_print(6, "RILClient", "[OemClient] Transaction is incorrect (%d)", v22);
            v4 = 0;
            v10 = ptr;
            if ( ptr )
              goto LABEL_42;
          }
        }
        else
        {
          _android_log_print(6, "RILClient", "[OemClient] Could not read full message (%d from %d)", chk, v25);
          free(ptr);
          v4 = 0;
        }
      }
      else
      {
        _android_log_print(6, "RILClient", "[OemClient] failed to allocate memory for message (%d)", v7);
        v4 = 0;
      }
    }
    else
    {
      _android_log_print(6, "RILClient", "[OemClient] response length(%d) is too big <= bigger than MAX(%d)", v25, 4096);
      v4 = 0;
    }
  }
  _android_log_print(6, "RILClient", "[OemClient] Disconnected (header)");
  v15 = (void (__fastcall *)(int, _DWORD, _DWORD, _DWORD))a1[39];
  pthread_mutex_lock(mutex);
  close(*a1);
  *a1 = -1;
  pthread_mutex_unlock(mutex);
  if ( v15 && !a1[1] )
    v15(1000, 0, 0, 0);
  _android_log_print(6, "RILClient", "[OemClient] RILC_Reader thread end");
  return 0;
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 1204: using guessed type int __fastcall _FD_SET_chk(_DWORD, _DWORD, _DWORD);
// 121C: using guessed type int __fastcall _FD_ISSET_chk(_DWORD, _DWORD, _DWORD);
// 1228: using guessed type int __fastcall _read_chk(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00001A5C) --------------------------------------------------------
int __fastcall sub_1A5C(int *a1)
{
  if ( a1 )
  {
    _android_log_print(3, "RILClient", "[OemClient] %s", "RILC_Monitor");
    usleep(0x7A120u);
    while ( a1[1] != 1 )
    {
      if ( *a1 < 0 )
      {
        _android_log_print(3, "RILClient", "[OemClient] detect socket disconnection -> try to reconnect");
        sleep(5u);
        j_RILC_Reconnect((int)a1);
      }
      usleep(0x7A120u);
    }
    _android_log_print(3, "RILClient", "[OemClient] exit %s", "RILC_Monitor");
  }
  return 0;
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00001AF8) --------------------------------------------------------
int __fastcall RILC_Reconnect(int a1)
{
  int v2; // r6
  int v3; // r0

  _android_log_print(3, "RILClient", "[OemClient] %s", "RILC_Reconnect");
  if ( !a1 )
    return -3;
  pthread_mutex_lock((pthread_mutex_t *)(a1 + 152));
  if ( *(int *)a1 < 1 )
  {
    v3 = socket_local_client((int)"RIL-CLIENT", 0, 1);
    *(_DWORD *)a1 = v3;
    if ( v3 <= -1 )
    {
      pthread_mutex_unlock((pthread_mutex_t *)(a1 + 152));
      _android_log_print(6, "RILClient", "[OemClient] Failed to re-connect to RIL socket");
      return -1;
    }
    else
    {
      if ( pthread_join(*(_DWORD *)(a1 + 144), 0) )
        _android_log_print(6, "RILClient", "[OemClient] Could not join thread");
      else
        _android_log_print(6, "RILClient", "[OemClient] reader thread join for exit");
      v2 = 0;
      if ( pthread_create((pthread_t *)(a1 + 144), 0, (void *(*)(void *))sub_1600, (void *)a1) )
      {
        close(*(_DWORD *)a1);
        v2 = -1;
        *(_DWORD *)a1 = -1;
        pthread_mutex_unlock((pthread_mutex_t *)(a1 + 152));
        _android_log_print(6, "RILClient", "[OemClient] Failed to create reader thread");
      }
      else
      {
        *(_DWORD *)(a1 + 4) = 0;
        pthread_mutex_unlock((pthread_mutex_t *)(a1 + 152));
        _android_log_print(3, "RILClient", "[OemClient] Client re-connected");
      }
    }
  }
  else
  {
    pthread_mutex_unlock((pthread_mutex_t *)(a1 + 152));
    return 0;
  }
  return v2;
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00001C10) --------------------------------------------------------
int __fastcall RILC_Close(int *a1)
{
  _android_log_print(3, "RILClient", "[OemClient] %s", "RILC_Close");
  if ( !a1 )
    return -3;
  if ( *a1 > 0 )
  {
    a1[1] = 1;
    while ( _write_chk(a1[3], "close", 5, 6) <= -1 && *(_DWORD *)_errno() == 4 )
      ;
    if ( pthread_join(a1[36], 0) )
      _android_log_print(6, "RILClient", "[OemClient] Could not join thread");
    else
      _android_log_print(6, "RILClient", "[OemClient] reader thread join for exit");
    if ( pthread_join(a1[37], 0) )
      _android_log_print(6, "RILClient", "[OemClient] Could not join thread");
    else
      _android_log_print(6, "RILClient", "[OemClient] mon thread join for exit");
  }
  close(a1[2]);
  close(a1[3]);
  if ( *a1 >= 1 )
    close(*a1);
  free(a1);
  _android_log_print(3, "RILClient", "[OemClient] %s, exit", "RILC_Close");
  return 0;
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 1288: using guessed type int __fastcall _write_chk(_DWORD, _DWORD, _DWORD, _DWORD);
// 1294: using guessed type int _errno(void);

//----- (00001D10) --------------------------------------------------------
int __fastcall RILC_RegisterUnsolicitedHandler(int a1, int a2)
{
  _android_log_print(3, "RILClient", "[OemClient] %s", "RILC_RegisterUnsolicitedHandler");
  if ( !a1 )
    return -3;
  pthread_mutex_lock((pthread_mutex_t *)(a1 + 152));
  *(_DWORD *)(a1 + 156) = a2;
  pthread_mutex_unlock((pthread_mutex_t *)(a1 + 152));
  return 0;
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00001D54) --------------------------------------------------------
int __fastcall RILC_Send(_DWORD *a1, int a2, const void *a3, size_t a4, int a5, int a6)
{
  int v10; // r7
  size_t v11; // r7
  int result; // r0
  char *v13; // r0
  char *v14; // r10
  unsigned __int8 v15; // r1
  _DWORD *v16; // r0
  int v17; // r2
  int v18; // r7
  size_t v19; // [sp+10h] [bp-28h]

  _android_log_print(3, "RILClient", "[OemClient] %s msgId:%d lengh:%zu channel:%d", "RILC_Send", a2, a4, a6);
  if ( !a1 || !a3 && a4 )
    return -3;
  pthread_mutex_lock((pthread_mutex_t *)(a1 + 38));
  v10 = *a1;
  pthread_mutex_unlock((pthread_mutex_t *)(a1 + 38));
  if ( v10 < 0 )
    return -2;
  v11 = 13;
  switch ( a2 )
  {
    case 1:
    case 11:
    case 13:
    case 15:
    case 17:
      goto LABEL_11;
    case 2:
    case 5:
    case 6:
    case 30:
    case 31:
    case 32:
    case 34:
    case 35:
    case 60:
    case 61:
    case 81:
    case 82:
    case 83:
    case 84:
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 106:
    case 107:
    case 108:
    case 109:
    case 110:
    case 111:
    case 112:
    case 113:
    case 114:
    case 115:
    case 116:
    case 117:
    case 118:
    case 119:
    case 120:
    case 121:
    case 122:
    case 123:
    case 124:
    case 125:
    case 126:
    case 127:
    case 128:
    case 129:
    case 130:
    case 131:
    case 132:
    case 133:
    case 134:
    case 135:
      goto LABEL_10;
    case 3:
    case 4:
      if ( a4 != 1 )
        return -3;
      v11 = 14;
      goto LABEL_11;
    case 7:
    case 8:
    case 9:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 62:
    case 63:
    case 64:
    case 65:
    case 66:
    case 67:
    case 68:
    case 69:
    case 70:
    case 71:
    case 72:
    case 73:
    case 74:
    case 75:
    case 76:
    case 77:
    case 78:
    case 79:
    case 80:
    case 85:
    case 86:
    case 87:
    case 88:
    case 89:
    case 90:
    case 91:
    case 92:
    case 93:
    case 94:
    case 95:
    case 96:
    case 97:
    case 98:
    case 99:
      goto LABEL_24;
    case 10:
    case 12:
    case 14:
    case 16:
    case 18:
      if ( a4 != 4 )
        return -3;
      v11 = 17;
      goto LABEL_11;
    case 19:
      if ( a4 != 8 )
        return -3;
      v11 = 21;
      goto LABEL_11;
    case 33:
      v11 = 15;
      goto LABEL_11;
    default:
      if ( (unsigned int)(a2 - 200) >= 0xF )
      {
LABEL_24:
        _android_log_print(6, "RILClient", "[OemClient] Unsupported msgId = %d", a2);
        return -3;
      }
LABEL_10:
      v11 = a4 + 13;
LABEL_11:
      v13 = (char *)malloc(v11);
      v14 = v13;
      if ( !v13 )
        return -5;
      *v13 = a6;
      *(_DWORD *)(v13 + 5) = a2;
      v19 = v11;
      *(_DWORD *)(v13 + 9) = a4;
      if ( a4 )
        qmemcpy(v13 + 13, a3, a4);
      pthread_mutex_lock((pthread_mutex_t *)(a1 + 38));
      v15 = *((_BYTE *)a1 + 160);
      v16 = a1 + 41;
      v17 = 0;
      while ( 1 )
      {
        v18 = v15;
        if ( v16[2 * v15] == -1 )
          break;
        ++v15;
        ++v17;
        *((_BYTE *)a1 + 160) = v15;
        if ( v17 >= 255 )
        {
          pthread_mutex_unlock((pthread_mutex_t *)(a1 + 38));
          _android_log_print(6, "RILClient", "[OemClient] No available transactions");
          free(v14);
          return -5;
        }
      }
      *(_DWORD *)(v14 + 1) = v15;
      v16[2 * v15] = a2;
      *((_BYTE *)a1 + 160) = v15 + 1;
      v16[2 * v15 + 1] = a5;
      pthread_mutex_unlock((pthread_mutex_t *)(a1 + 38));
      _android_log_print(
        3,
        "RILClient",
        "[OemClient] REQ (t = %d, id = %d, len = %d channel = %d)",
        v18,
        a2,
        a4,
        (unsigned __int8)a6);
      if ( _write_chk(*a1, v14, v19, -1) < 0 )
      {
        _android_log_print(6, "RILClient", "[OemClient] Failed to send message to RIL");
        free(v14);
        result = -4;
      }
      else
      {
        free(v14);
        result = 0;
      }
      break;
  }
  return result;
}
// 1198: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 1288: using guessed type int __fastcall _write_chk(_DWORD, _DWORD, _DWORD, _DWORD);

//----- (00002020) --------------------------------------------------------
void __fastcall ProductFeature::ProductFeature(ProductFeature *this)
{
  *(_DWORD *)this = &off_5D40;
}
// 5D40: using guessed type void *;

//----- (00002036) --------------------------------------------------------
int __fastcall ProductFeature::Init(ProductFeature *this, const char *a2)
{
  void *Instance; // r0

  Instance = ProductFeature::GetInstance(this);
  (*(void (__fastcall **)(void *, ProductFeature *))(*(_DWORD *)Instance + 8))(Instance, this);
  return 1;
}

//----- (0000204C) --------------------------------------------------------
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::SupportOnly5Mode == %s", v1, "true");
  return 1;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (0000207C) --------------------------------------------------------
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::SupportOnlyBasicPreferredNetworkType == %s", v1, "true");
  return 1;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (000020AC) --------------------------------------------------------
int __fastcall ProductFeature::Function_SendDebugTraceOffAtBootup(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::SendDebugTraceOffAtBootup == %s", v1, "false");
  return 0;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (000020DC) --------------------------------------------------------
int __fastcall ProductFeature::Function_GetFastDormancyInfo(
        ProductFeature *this,
        unsigned __int8 *a2,
        unsigned __int8 *a3,
        unsigned __int8 *a4,
        unsigned __int8 *a5)
{
  const char *v8; // r0

  *a2 = 0;
  *a3 = 0;
  *a4 = 0;
  *a5 = 0;
  v8 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(
    1,
    4,
    0,
    "[%s]  ProductFeature::SupportFastDormancyInfo == %s(%d,%d,%d,%d [.5sec/unit]))",
    v8,
    "false",
    *a2,
    *a3,
    *a4,
    *a5);
  return 0;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002128) --------------------------------------------------------
int __fastcall ProductFeature::Function_RilResetByCrashExitInUserMode(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::RilResetByModemCrash == %s", v1, "false");
  return 0;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002158) --------------------------------------------------------
int __fastcall ProductFeature::Function_DeviceBasedCwInCs(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::DeviceBasedCWinCS == %s", v1, "true");
  return 1;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002188) --------------------------------------------------------
const char *sub_2188()
{
  return "/efs/";
}

//----- (00002194) --------------------------------------------------------
const char *sub_2194()
{
  return "/efs/backup/nv_protected";
}

//----- (000021A0) --------------------------------------------------------
void *__fastcall ProductFeature::GetInstance(ProductFeature *this)
{
  return &instance;
}

//----- (000021AC) --------------------------------------------------------
void __fastcall CustomProductFeature::CustomProductFeature(CustomProductFeature *this)
{
  _DWORD *v1; // r0

  ProductFeature::ProductFeature(this);
  *v1 = &off_5D6C;
}
// 21BA: variable 'v1' is possibly undefined
// 5D6C: using guessed type void *;

//----- (000021C8) --------------------------------------------------------
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *this)
{
  void *v1; // r0

  ProductFeature::~ProductFeature(this);
  operator delete(v1);
}
// 21D2: variable 'v1' is possibly undefined

//----- (000021D8) --------------------------------------------------------
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2)
{
  const char *v2; // r0

  v2 = "unknown";
  if ( a2 )
    v2 = a2;
  _android_log_buf_print(1, 4, 0, "<%s> [%s] CustomProductFeature::Init", v2, "m86");
  return 1;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002210) --------------------------------------------------------
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this)
{
  return "m86";
}

//----- (0000221C) --------------------------------------------------------
int __fastcall CustomProductFeature::Custom_SaveImeiToProperty(CustomProductFeature *this)
{
  _android_log_buf_print(1, 4, 0, "[%s] CustomProductFeature::SaveImeiToProperty == %s", "m86", "true");
  return 1;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (0000224C) --------------------------------------------------------
int __fastcall CustomProductFeature::Custom_ReturnCurrentPlmn(CustomProductFeature *this)
{
  _android_log_buf_print(1, 4, 0, "[%s] CustomProductFeature::ReturnCurrentPlmn == %s", "m86", "false");
  return 0;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (0000227C) --------------------------------------------------------
int __fastcall CustomProductFeature::ModuleAudio_VolumeStartFrom1(CustomProductFeature *this)
{
  _android_log_buf_print(1, 4, 0, "[%s] CustomProductFeature::VolumeStartFrom1 == %s", "m86", "true");
  return 1;
}
// 12C4: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (000022AC) --------------------------------------------------------
const char *sub_22AC()
{
  return "/efs/nv_data/";
}

//----- (000022B8) --------------------------------------------------------
const char *sub_22B8()
{
  return "/mnv/bak/nv_protected";
}

//----- (000022C4) --------------------------------------------------------
unsigned int *__fastcall sub_22C4(unsigned int *result, int *a2, int *a3)
{
  unsigned int v3; // r3
  unsigned int v4; // t1
  int v5; // r12
  bool v6; // zf
  int v7; // r3
  int v8; // r12

  v3 = *result;
  if ( (*result & 0x80000000) == 0 )
  {
    *a2 = 1;
    v4 = result[1];
    ++result;
    *a3 = 4 * HIBYTE(v4) + 4;
    return result;
  }
  v5 = HIBYTE(v3) & 0xF;
  if ( v5 )
  {
    v6 = v5 == 3;
    if ( v5 != 3 )
      v6 = v5 == 1;
    if ( !v6 )
      return 0;
    v7 = 4 * BYTE2(v3) + 4;
    v8 = 2;
  }
  else
  {
    v8 = 1;
    v7 = 4;
  }
  *a3 = v7;
  *a2 = v8;
  return result;
}

//----- (00002318) --------------------------------------------------------
int __fastcall sub_2318(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v6; // r11
  unsigned int v8; // r7
  int v9; // r10
  int v10; // r2
  unsigned int v11; // r1
  int result; // r0
  int v13; // r3
  int v14; // r2
  int v15; // r0
  int v16; // r1
  int v17; // r2
  int v18; // r1
  int v19; // r6
  int v20; // r2
  int v21; // r0
  int v22; // r1
  int v23; // r3
  int v24; // r0
  int v25; // r2
  int v26; // r0
  unsigned int v33; // r1
  unsigned int v34; // r0
  int v35; // r1
  unsigned int v36; // r0
  int v37; // [sp+0h] [bp-30h]
  int v38; // [sp+4h] [bp-2Ch] BYREF

  v6 = a3;
  if ( a3 >= a4 )
  {
LABEL_54:
    sub_2C08(a1, 14, &v38);
    sub_2C36(a1, 15, v38);
    return 8;
  }
  v37 = 0;
  do
  {
    v8 = v6 + 1;
    v9 = *(unsigned __int8 *)(a2 + (v6 ^ 3));
    if ( (v9 & 0x80) == 0 )
    {
      sub_2C08(a1, 13, &v38);
      if ( (v9 & 0x40) != 0 )
        v10 = -4 - (unsigned __int8)(4 * v9) + v38;
      else
        v10 = 4 * v9 + v38 + 4;
LABEL_12:
      v38 = v10;
LABEL_13:
      sub_2C36(a1, 13, v10);
LABEL_36:
      v6 = v8;
      continue;
    }
    v11 = v9 & 0xF0;
    result = 9;
    if ( v11 > 0xAF )
    {
      if ( v11 == 176 )
      {
        result = 9;
        v18 = 0;
        v19 = 0;
        switch ( *(_BYTE *)(a2 + (v6 ^ 3)) )
        {
          case 0xB0:
            goto LABEL_53;
          case 0xB1:
            if ( v8 >= a4 )
              return 9;
            v20 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
            result = 9;
            if ( !*(_BYTE *)(a2 + (v8 ^ 3)) || (v20 & 0xF0) != 0 )
              return result;
            v21 = a1;
            v22 = 0;
            v23 = 0;
            goto LABEL_48;
          case 0xB2:
            break;
          case 0xB3:
            v23 = 1;
            v26 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
            _R1 = v26 << 12;
            __asm { UXTB16.W        R1, R1 }
            v20 = ((v26 & 0xF) + 1) | _R1;
            v21 = a1;
            v22 = 1;
            goto LABEL_48;
          case 0xB4:
          case 0xB5:
          case 0xB6:
          case 0xB7:
            return result;
          default:
            v16 = 1;
            v13 = 1;
            v14 = ((v9 & 7) + 1) | 0x80000;
            v15 = a1;
            goto LABEL_35;
        }
        while ( v8 < a4 )
        {
          v24 = v8++ ^ 3;
          LOBYTE(v24) = *(_BYTE *)(a2 + v24);
          v25 = (v24 & 0x7F) << v18;
          v18 += 7;
          v19 |= v25;
          if ( (v24 & 0x80) == 0 )
          {
            sub_2C08(a1, 13, &v38);
            v10 = v38 + 4 * v19 + 516;
            goto LABEL_12;
          }
        }
        return 9;
      }
      if ( v11 != 192 )
      {
        if ( v11 != 208 )
          return result;
        if ( (v9 & 8) != 0 )
          return 9;
        v16 = 1;
        v14 = ((v9 & 7) + 1) | 0x80000;
        v15 = a1;
LABEL_34:
        v13 = 5;
        goto LABEL_35;
      }
      switch ( *(_BYTE *)(a2 + (v6 ^ 3)) )
      {
        case 0xC0:
        case 0xC1:
        case 0xC2:
        case 0xC3:
        case 0xC4:
        case 0xC5:
          v16 = 3;
          v14 = ((v9 & 7) + 1) | 0xA0000;
          v15 = a1;
          goto LABEL_34;
        case 0xC6:
          v36 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
          if ( (v36 & 0xF) + (v36 >> 4) > 0xF )
            return 9;
          v20 = ((v36 & 0xF) + 1) | (v36 >> 4 << 16);
          v21 = a1;
          v22 = 3;
          break;
        case 0xC7:
          if ( !*(_BYTE *)(a2 + (v8 ^ 3)) || *(unsigned __int8 *)(a2 + (v8 ^ 3)) >= 0x10u )
            return 9;
          goto LABEL_49;
        case 0xC8:
        case 0xC9:
          v33 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
          v34 = v33 >> 4;
          if ( v9 == 200 )
            v34 = (v33 >> 4) | 0x10;
          v35 = v33 & 0xF;
          if ( v34 + v35 > 0x1F )
            return 9;
          v20 = (v35 + 1) | (v34 << 16);
          v21 = a1;
          v22 = 1;
          break;
        default:
          return 9;
      }
      v23 = 5;
LABEL_48:
      sub_26F8(v21, v22, v20, v23);
    }
    else
    {
      if ( v11 != 128 )
      {
        if ( v11 == 144 )
        {
          if ( (v9 & 0xD | 2) == 15 )
            return 9;
          sub_2C08(a1, v9 & 0xF, &v38);
          v10 = v38;
          goto LABEL_13;
        }
        if ( v11 != 160 )
          return result;
        v13 = 0;
        v14 = ((16 << ((v9 & 7) + 1)) - 16) | (v9 << 11) & 0x4000;
        v15 = a1;
        v16 = 0;
LABEL_35:
        sub_26F8(v15, v16, v14, v13);
        goto LABEL_36;
      }
      if ( v8 >= a4 )
        return 9;
      v17 = (unsigned __int16)((_WORD)v9 << 12) | (16 * *(unsigned __int8 *)(a2 + (v8 ^ 3)));
      if ( !v17 )
        return 9;
      sub_26F8(a1, 0, v17, 0);
      v37 |= (unsigned __int16)(((_WORD)v9 << 12) & 0x8000) >> 15;
    }
LABEL_49:
    v6 += 2;
  }
  while ( v6 < a4 );
LABEL_53:
  if ( (v37 & 1) == 0 )
    goto LABEL_54;
  return 8;
}

//----- (0000265C) --------------------------------------------------------
int __fastcall sub_265C(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int result; // r0
  int v8; // r2
  int v9; // r0
  int v10; // r1
  __int64 v11; // r2
  int v12; // r1

  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = a1;
      v10 = a3;
      goto LABEL_11;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_19;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_2D18(a1);
LABEL_19:
      v11 = *(_QWORD *)a5;
      v12 = a3 + 256;
LABEL_20:
      result = sub_2CAA(a1, v12, v11, SHIDWORD(v11));
LABEL_21:
      if ( result )
        return 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = a3 + 112;
      goto LABEL_20;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = a3 + 192;
      v9 = a1;
LABEL_11:
      result = sub_2C36(v9, v10, v8);
      goto LABEL_21;
    default:
      sub_2A74(
        "_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation, void *)",
        837,
        "unsupported register class");
  }
}

//----- (000026F8) --------------------------------------------------------
int __fastcall sub_26F8(int a1, int a2, unsigned int a3, int a4)
{
  char v8; // r4
  unsigned int i; // r7
  int *v10; // r0
  int v11; // r0
  char v12; // r1
  char v13; // r2
  int result; // r0
  unsigned int v15; // r4
  unsigned int v16; // r6
  int *v17; // r0
  int v18; // r2
  int v19; // r0
  int v20; // r2
  int v21[2]; // [sp+8h] [bp-30h] BYREF
  int *v22; // [sp+10h] [bp-28h] BYREF

  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_2C08(a1, 13, v21) )
        return 2;
      v8 = 0;
      for ( i = 0; i < 0x10; ++i )
      {
        if ( ((1 << i) & a3) != 0 )
        {
          v10 = (int *)v21[0];
          v21[0] += 4;
          v22 = (int *)*v10;
          v11 = sub_265C(a1, a2, i, 0, (int *)&v22);
          v12 = 0;
          v13 = 0;
          if ( i == 13 )
            v12 = 1;
          if ( !a2 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
      }
      if ( (v8 & 1) != 0 )
        return 0;
      v20 = v21[0];
      goto LABEL_26;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_2C08(a1, 13, &v22) )
        return 2;
      if ( !(_WORD)a3 )
        goto LABEL_21;
      v15 = HIWORD(a3);
      v16 = HIWORD(a3) + (unsigned __int16)a3;
      break;
    default:
      sub_2A74(
        "_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        971,
        "unsupported register class");
  }
  do
  {
    v17 = v22++;
    v18 = *v17;
    v22 = v17 + 2;
    v19 = v17[1];
    v21[0] = v18;
    v21[1] = v19;
    if ( sub_265C(a1, a2, v15, a4, v21) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( a4 == 1 )
    v20 = (int)++v22;
  else
    v20 = (int)v22;
LABEL_26:
  result = sub_2C36(a1, 13, v20);
  if ( result )
    return 2;
  return result;
}

//----- (00002834) --------------------------------------------------------
int __fastcall sub_2834(int a1, int a2, int a3)
{
  return sub_283C(a2, a3);
}

//----- (0000283C) --------------------------------------------------------
int __fastcall sub_283C(int a1, int a2)
{
  int result; // r0
  int v5; // r1
  char v6[8]; // [sp+4h] [bp-3Ch] BYREF
  _DWORD *v7; // [sp+Ch] [bp-34h]

  sub_2CE8(a2, (int)v6);
  if ( (*(_BYTE *)(a1 + 80) & 1) == 0 && *v7 )
    return 9;
  v5 = sub_2CE2(a2);
  result = 9;
  if ( v5 == 1 )
    return 8;
  return result;
}
// 283C: using guessed type char var_3C[8];

//----- (00002898) --------------------------------------------------------
int __fastcall sub_2898(int a1, int a2, int a3)
{
  return sub_283C(a2, a3);
}

//----- (000028A0) --------------------------------------------------------
int __fastcall sub_28A0(int a1, int a2, int a3)
{
  return sub_283C(a2, a3);
}

//----- (000028A8) --------------------------------------------------------
int __fastcall sub_28A8(int *a1, int a2, int a3, int a4)
{
  int v5; // r5
  int (__fastcall *v6)(_DWORD, int *, char *); // r3
  int v7; // r0
  int v9[3]; // [sp+0h] [bp-8A0h] BYREF
  int (__fastcall *v10)(_DWORD, int *, char *); // [sp+Ch] [bp-894h]
  int v11; // [sp+14h] [bp-88Ch]
  int v12; // [sp+20h] [bp-880h]
  _DWORD v13[256]; // [sp+28h] [bp-878h] BYREF
  char v14[1120]; // [sp+428h] [bp-478h] BYREF

  sub_2B3C(v13, a2, a3, a4, v9[0]);
  a1[3] = 0;
  sub_2BC4((int)v14, v13);
  if ( sub_2CE8((int)v14, (int)v9) )
    return 3;
  v5 = 3;
  while ( 1 )
  {
    v6 = v10;
    if ( v10 )
    {
      a1[18] = v9[0];
      a1[19] = v12;
      a1[20] = v11;
      v7 = v6(0, a1, v14);
      if ( v7 != 8 )
        break;
    }
    if ( sub_2CE8((int)v14, (int)v9) )
      return 3;
  }
  if ( v7 == 6 )
  {
    sub_2954(v13, a1, 0);
    return 2;
  }
  else if ( v7 == 9 )
  {
    return 9;
  }
  return v5;
}
// 28A8: using guessed type _DWORD var_878[256];

//----- (00002954) --------------------------------------------------------
int __fastcall sub_2954(const void *a1, int *a2, char a3)
{
  int i; // r6
  int v6; // r7
  int (__fastcall *v7)(int, int *, char *); // r3
  int v8; // r0
  int v10; // [sp+0h] [bp-4B8h] BYREF
  int v11[3]; // [sp+4h] [bp-4B4h] BYREF
  int (__fastcall *v12)(int, int *, char *); // [sp+10h] [bp-4A8h]
  int v13; // [sp+18h] [bp-4A0h]
  int v14; // [sp+24h] [bp-494h]
  int v15; // [sp+2Ch] [bp-48Ch] BYREF
  char v16[1124]; // [sp+30h] [bp-488h] BYREF
  int v17; // [sp+494h] [bp-24h]

  sub_2BC4((int)v16, a1);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( (a3 & 1) != 0 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_2C36((int)v16, -1, a2[4]);
        a3 = 0;
      }
    }
    sub_2C08((int)v16, -2, &v15);
    if ( sub_2CE8((int)v16, (int)v11) )
      break;
    v7 = v12;
    if ( v12 )
    {
      a2[18] = v11[0];
      a2[19] = v14;
      a2[20] = v13;
      v8 = v7(v6, a2, v16);
      if ( v8 == 7 )
      {
        sub_2C08((int)v16, -1, &v10);
        a2[4] = v10;
        sub_2D06((int)v16);
        return _stack_chk_guard - v17;
      }
      if ( v8 != 8 )
      {
        if ( v8 == 9 )
          abort();
        return _stack_chk_guard - v17;
      }
      if ( v15 == a2[8] )
        sub_2A74(
          "_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          653,
          "during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return _stack_chk_guard - v17;
}
// 2954: using guessed type int var_4B4[3];

//----- (00002A40) --------------------------------------------------------
void __fastcall __noreturn sub_2A40(int *a1, int a2, int a3, int a4)
{
  int v5[260]; // [sp+0h] [bp-410h] BYREF

  sub_2B3C(v5, a2, a3, a4, v5[0]);
  sub_2954(v5, a1, 1);
  sub_2A74("void _Unwind_Resume(_Unwind_Exception *)", 753, "_Unwind_Resume() can't return");
}

//----- (00002A74) --------------------------------------------------------
void __fastcall __noreturn sub_2A74(const char *a1, int a2, const char *a3)
{
  fprintf(stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libunwind_llvm/src/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (00002AA4) --------------------------------------------------------
int __fastcall sub_2AA4(int a1)
{
  int v1; // r1
  int result; // r0
  char v3[8]; // [sp+4h] [bp-34h] BYREF
  int v4; // [sp+Ch] [bp-2Ch]

  v1 = sub_2CE8(a1, (int)v3);
  result = v4;
  if ( v1 )
    return 0;
  return result;
}
// 2AA4: using guessed type char var_34[8];

//----- (00002AE0) --------------------------------------------------------
int __fastcall sub_2AE0(int a1)
{
  int v1; // r1
  int result; // r0
  int v3[10]; // [sp+4h] [bp-34h] BYREF

  v1 = sub_2CE8(a1, (int)v3);
  result = v3[0];
  if ( v1 )
    return 0;
  return result;
}
// 2AE0: using guessed type int var_34[10];

//----- (00002B28) --------------------------------------------------------
int __fastcall sub_2B28(int a1, int a2)
{
  int v2; // r0
  int v3; // r1

  v2 = sub_2CE2(a2);
  v3 = 9;
  if ( v2 == 1 )
    return 0;
  return v3;
}

//----- (00002B3C) --------------------------------------------------------
int __fastcall sub_2B3C(_DWORD *a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r5
  int v7; // r6
  int v8; // r7
  int v9; // r8
  int v10; // r9
  int v11; // r10
  int v12; // r11
  int v13; // r12
  int v14; // lr

  *a1 = a1;
  a1[1] = a2;
  a1[2] = a3;
  a1[3] = a4;
  a1[4] = v5;
  a1[5] = v6;
  a1[6] = v7;
  a1[7] = v8;
  a1[8] = v9;
  a1[9] = v10;
  a1[10] = v11;
  a1[11] = v12;
  a1[12] = v13;
  a1[13] = &a5;
  a1[14] = v14;
  a1[15] = v14;
  return 0;
}
// 2B3C: variable 'v5' is possibly undefined
// 2B3C: variable 'v6' is possibly undefined
// 2B3C: variable 'v7' is possibly undefined
// 2B3C: variable 'v8' is possibly undefined
// 2B3C: variable 'v9' is possibly undefined
// 2B3C: variable 'v10' is possibly undefined
// 2B3C: variable 'v11' is possibly undefined
// 2B3C: variable 'v12' is possibly undefined
// 2B3C: variable 'v13' is possibly undefined
// 2B44: variable 'v14' is possibly undefined

//----- (00002B54) --------------------------------------------------------
_QWORD *__fastcall sub_2B54(_QWORD *result)
{
  __int64 v1; // d0
  __int64 v2; // d1
  __int64 v3; // d2
  __int64 v4; // d3
  __int64 v5; // d4
  __int64 v6; // d5
  __int64 v7; // d6
  __int64 v8; // d7
  __int64 v9; // d8
  __int64 v10; // d9
  __int64 v11; // d10
  __int64 v12; // d11
  __int64 v13; // d12
  __int64 v14; // d13
  __int64 v15; // d14
  __int64 v16; // d15

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 2B54: variable 'v1' is possibly undefined
// 2B54: variable 'v2' is possibly undefined
// 2B54: variable 'v3' is possibly undefined
// 2B54: variable 'v4' is possibly undefined
// 2B54: variable 'v5' is possibly undefined
// 2B54: variable 'v6' is possibly undefined
// 2B54: variable 'v7' is possibly undefined
// 2B54: variable 'v8' is possibly undefined
// 2B54: variable 'v9' is possibly undefined
// 2B54: variable 'v10' is possibly undefined
// 2B54: variable 'v11' is possibly undefined
// 2B54: variable 'v12' is possibly undefined
// 2B54: variable 'v13' is possibly undefined
// 2B54: variable 'v14' is possibly undefined
// 2B54: variable 'v15' is possibly undefined
// 2B54: variable 'v16' is possibly undefined

//----- (00002B5C) --------------------------------------------------------
_QWORD *__fastcall sub_2B5C(_QWORD *result)
{
  __int64 v1; // d0
  __int64 v2; // d1
  __int64 v3; // d2
  __int64 v4; // d3
  __int64 v5; // d4
  __int64 v6; // d5
  __int64 v7; // d6
  __int64 v8; // d7
  __int64 v9; // d8
  __int64 v10; // d9
  __int64 v11; // d10
  __int64 v12; // d11
  __int64 v13; // d12
  __int64 v14; // d13
  __int64 v15; // d14
  __int64 v16; // d15

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 2B5C: variable 'v1' is possibly undefined
// 2B5C: variable 'v2' is possibly undefined
// 2B5C: variable 'v3' is possibly undefined
// 2B5C: variable 'v4' is possibly undefined
// 2B5C: variable 'v5' is possibly undefined
// 2B5C: variable 'v6' is possibly undefined
// 2B5C: variable 'v7' is possibly undefined
// 2B5C: variable 'v8' is possibly undefined
// 2B5C: variable 'v9' is possibly undefined
// 2B5C: variable 'v10' is possibly undefined
// 2B5C: variable 'v11' is possibly undefined
// 2B5C: variable 'v12' is possibly undefined
// 2B5C: variable 'v13' is possibly undefined
// 2B5C: variable 'v14' is possibly undefined
// 2B5C: variable 'v15' is possibly undefined
// 2B5C: variable 'v16' is possibly undefined

//----- (00002B64) --------------------------------------------------------
_QWORD *__fastcall sub_2B64(_QWORD *result)
{
  __int64 v1; // d16
  __int64 v2; // d17
  __int64 v3; // d18
  __int64 v4; // d19
  __int64 v5; // d20
  __int64 v6; // d21
  __int64 v7; // d22
  __int64 v8; // d23
  __int64 v9; // d24
  __int64 v10; // d25
  __int64 v11; // d26
  __int64 v12; // d27
  __int64 v13; // d28
  __int64 v14; // d29
  __int64 v15; // d30
  __int64 v16; // d31

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 2B64: variable 'v1' is possibly undefined
// 2B64: variable 'v2' is possibly undefined
// 2B64: variable 'v3' is possibly undefined
// 2B64: variable 'v4' is possibly undefined
// 2B64: variable 'v5' is possibly undefined
// 2B64: variable 'v6' is possibly undefined
// 2B64: variable 'v7' is possibly undefined
// 2B64: variable 'v8' is possibly undefined
// 2B64: variable 'v9' is possibly undefined
// 2B64: variable 'v10' is possibly undefined
// 2B64: variable 'v11' is possibly undefined
// 2B64: variable 'v12' is possibly undefined
// 2B64: variable 'v13' is possibly undefined
// 2B64: variable 'v14' is possibly undefined
// 2B64: variable 'v15' is possibly undefined
// 2B64: variable 'v16' is possibly undefined

//----- (00002B6C) --------------------------------------------------------
void sub_2B6C()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (00002BB0) --------------------------------------------------------
void sub_2BB0()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (00002BC4) --------------------------------------------------------
int __fastcall sub_2BC4(int a1, const void *a2)
{
  *(_DWORD *)a1 = &off_5D98;
  *(_DWORD *)(a1 + 4) = &unk_6008;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  qmemcpy((void *)(a1 + 8), a2, 0x40u);
  memset((void *)(a1 + 80), 0, 0x1C2u);
  sub_30E0((int *)a1, 0);
  return 0;
}
// 5D98: using guessed type void *;

//----- (00002C08) --------------------------------------------------------
int __fastcall sub_2C08(int a1, int a2, _DWORD *a3)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 8))(a1) != 1 )
    return -6542;
  *a3 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 12))(a1, a2);
  return 0;
}

//----- (00002C36) --------------------------------------------------------
int __fastcall sub_2C36(int a1, int a2, int a3)
{
  int v6; // r5

  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 8))(a1) != 1 )
    return -6542;
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 16))(a1, a2, a3);
  if ( a2 != -1 )
    return 0;
  v6 = 0;
  (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)a1 + 52))(a1, 0);
  return v6;
}

//----- (00002C7A) --------------------------------------------------------
int __fastcall sub_2C7A(int a1, int a2, _QWORD *a3)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 20))(a1) != 1 )
    return -6542;
  *a3 = ((__int64 (__fastcall *)(int, int))*(_DWORD *)(*(_DWORD *)a1 + 24))(a1, a2);
  return 0;
}

//----- (00002CAA) --------------------------------------------------------
int __fastcall sub_2CAA(int a1, int a2, int a3, int a4)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 20))(a1) != 1 )
    return -6542;
  (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 28))(a1, a2, a3, a4);
  return 0;
}

//----- (00002CE2) --------------------------------------------------------
int __fastcall sub_2CE2(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 32))(a1);
}

//----- (00002CE8) --------------------------------------------------------
int __fastcall sub_2CE8(int a1, int a2)
{
  int result; // r0

  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 36))(a1, a2);
  result = 0;
  if ( !*(_DWORD *)(a2 + 4) )
    return -6549;
  return result;
}

//----- (00002D06) --------------------------------------------------------
int __fastcall sub_2D06(int a1)
{
  (*(void (__fastcall **)(int))(*(_DWORD *)a1 + 40))(a1);
  return -6540;
}

//----- (00002D18) --------------------------------------------------------
int __fastcall sub_2D18(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 60))(a1);
}

//----- (00002D1E) --------------------------------------------------------
int __fastcall sub_2D1E(int a1, int a2)
{
  int v2; // r2
  bool v3; // zf
  int v4; // r0
  unsigned int v5; // r1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (00002D40) --------------------------------------------------------
int __fastcall sub_2D40(int a1, int a2)
{
  int v4; // r0

  if ( a2 > 12 )
  {
    if ( a2 != 15 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 13 )
        goto LABEL_11;
LABEL_9:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    goto LABEL_8;
  }
  if ( a2 == -2 )
    goto LABEL_9;
  if ( a2 == -1 )
  {
LABEL_8:
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
LABEL_11:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_3160(
        "uint32_t libunwind::Registers_arm::getRegister(int)",
        "external/libunwind_llvm/src/Registers.hpp",
        1452,
        "unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_2BB0();
    }
    v4 = a1 + 4 * a2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (00002DCC) --------------------------------------------------------
int __fastcall sub_2DCC(int result, int a2, int a3)
{
  int v5; // r5

  v5 = result;
  if ( a2 <= 12 )
  {
    if ( a2 == -2 )
      goto LABEL_9;
    if ( a2 != -1 )
      goto LABEL_11;
LABEL_8:
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  switch ( a2 )
  {
    case 15:
      goto LABEL_8;
    case 14:
      *(_DWORD *)(result + 64) = a3;
      return result;
    case 13:
LABEL_9:
      *(_DWORD *)(result + 60) = a3;
      return result;
  }
LABEL_11:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_3160(
        "void libunwind::Registers_arm::setRegister(int, uint32_t)",
        "external/libunwind_llvm/src/Registers.hpp",
        1471,
        "unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_2BB0();
    }
    result = v5 + 4 * a2;
    *(_DWORD *)(result - 296) = a3;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (00002E58) --------------------------------------------------------
int __fastcall sub_2E58(int a1, int a2)
{
  int v2; // r2
  bool v3; // zf
  int v4; // r0
  unsigned int v5; // r1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (00002E7C) --------------------------------------------------------
__int64 __fastcall sub_2E7C(int a1, int a2)
{
  unsigned int v4; // r0
  _QWORD *v5; // r0
  int v6; // r0

  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(a1 + 75) )
    {
      *(_BYTE *)(a1 + 75) = 1;
      sub_2B6C();
    }
    v6 = a1 + 8 * a2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(a1 + 74) )
    {
      *(_BYTE *)(a1 + 74) = 1;
      sub_2B64((_QWORD *)(a1 + 216));
    }
    v6 = a1 + 8 * a2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_3160(
        "unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        "external/libunwind_llvm/src/Registers.hpp",
        1673,
        "Unknown ARM float register");
    if ( !*(_BYTE *)(a1 + 73) )
    {
      *(_BYTE *)(a1 + 73) = 1;
      v5 = (_QWORD *)(a1 + 80);
      if ( *(_BYTE *)(a1 + 72) )
        sub_2B5C(v5);
      else
        sub_2B54(v5);
    }
    v6 = a1 + 8 * a2 - 1968;
  }
  return *(_QWORD *)v6;
}

//----- (00002F20) --------------------------------------------------------
int __fastcall sub_2F20(int a1, int a2, int a3, int a4)
{
  unsigned int v6; // r0
  _QWORD *v9; // r0
  int result; // r0
  int v11; // r1

  v6 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(a1 + 75) )
    {
      *(_BYTE *)(a1 + 75) = 1;
      sub_2B6C();
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 548) = a4;
    LOWORD(v11) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(a1 + 74) )
    {
      *(_BYTE *)(a1 + 74) = 1;
      sub_2B64((_QWORD *)(a1 + 216));
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 1956) = a4;
    LOWORD(v11) = -1960;
  }
  else
  {
    if ( v6 != 256 )
      sub_3160(
        "void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        "external/libunwind_llvm/src/Registers.hpp",
        1700,
        "Unknown ARM float register");
    if ( !*(_BYTE *)(a1 + 73) )
    {
      *(_BYTE *)(a1 + 73) = 1;
      v9 = (_QWORD *)(a1 + 80);
      if ( *(_BYTE *)(a1 + 72) )
        sub_2B5C(v9);
      else
        sub_2B54(v9);
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 1964) = a4;
    LOWORD(v11) = -1968;
  }
  HIWORD(v11) = -1;
  *(_DWORD *)(result + v11) = a3;
  return result;
}

//----- (00002FEC) --------------------------------------------------------
int __fastcall sub_2FEC(_DWORD *a1)
{
  int result; // r0
  __int64 v3; // kr00_8
  int v4; // r0

  if ( *((_BYTE *)a1 + 528) )
    return 0;
  result = sub_318C((int)a1);
  if ( result != 1 )
    return result;
  (*(void (__fastcall **)(_DWORD *, int))(*a1 + 52))(a1, 1);
  if ( *((_BYTE *)a1 + 528) )
    return 0;
  if ( a1[126] )
  {
    v3 = *(_QWORD *)(*a1 + 12);
    v4 = ((int (__fastcall *)(_DWORD *, int))v3)(a1, -2);
    ((void (__fastcall *)(_DWORD *, int, int))HIDWORD(v3))(a1, -2, a1[126] + v4);
  }
  return 1;
}

//----- (0000303C) --------------------------------------------------------
_DWORD *__fastcall sub_303C(int a1, _DWORD *a2)
{
  int *v2; // r0
  _DWORD *result; // r0
  int v4; // r2
  int v5; // r3
  int v6; // r4
  int v7; // r12
  int v8; // lr
  _DWORD *v9; // r1
  int v10; // r3
  int v11; // r4
  int v12; // r12
  int v13; // lr

  v2 = (int *)(a1 + 488);
  v4 = *v2;
  v5 = v2[1];
  v6 = v2[2];
  v7 = v2[3];
  v8 = v2[4];
  result = v2 + 5;
  *a2 = v4;
  a2[1] = v5;
  a2[2] = v6;
  a2[3] = v7;
  a2[4] = v8;
  v9 = a2 + 5;
  v10 = result[1];
  v11 = result[2];
  v12 = result[3];
  v13 = result[4];
  *v9 = *result;
  v9[1] = v10;
  v9[2] = v11;
  v9[3] = v12;
  v9[4] = v13;
  return result;
}

//----- (00003054) --------------------------------------------------------
int __fastcall sub_3054(int a1)
{
  int v1; // r4

  v1 = a1 + 8;
  sub_31E0(a1 + 8);
  return sub_3920(v1);
}

//----- (0000306A) --------------------------------------------------------
int __fastcall sub_306A(int a1)
{
  return *(unsigned __int8 *)(a1 + 529);
}

//----- (00003070) --------------------------------------------------------
int __fastcall sub_3070(int a1, int a2, int a3, _DWORD *a4)
{
  int v7; // r7
  char v9[8]; // [sp+8h] [bp-28h] BYREF
  const char *v10; // [sp+10h] [bp-20h]
  int v11; // [sp+14h] [bp-1Ch]

  v7 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 12))(a1, -1);
  if ( !dladdr(v7, v9) || !v10 )
    return 0;
  _snprintf_chk(a2, a3, 0, -1, "%s", v10);
  *a4 = v7 - v11;
  return 1;
}
// 1378: using guessed type int __fastcall dladdr(_DWORD, _DWORD);
// 1384: using guessed type int _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, const char *, ...);
// 3070: using guessed type char var_28[8];

//----- (000030E0) --------------------------------------------------------
int __fastcall sub_30E0(int *a1, int a2)
{
  int v4; // r5
  int v6[2]; // [sp+0h] [bp-20h] BYREF
  int v7[6]; // [sp+8h] [bp-18h] BYREF

  v4 = (*(int (__fastcall **)(int *, int))(*a1 + 12))(a1, -1) & 0xFFFFFFFE;
  v7[0] = 0;
  if ( a2 )
    --v4;
  v6[0] = _gnu_Unwind_Find_exidx(v4, v7);
  v6[1] = v7[0];
  if ( !v6[0] || !v7[0] || !sub_3238(a1, v4, v6) )
    *((_BYTE *)a1 + 528) = 1;
  return _stack_chk_guard - v7[1];
}
// 1390: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);

//----- (00003156) --------------------------------------------------------
int __fastcall sub_3156(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (00003160) --------------------------------------------------------
void __fastcall __noreturn sub_3160(const char *a1, const char *a2, int a3, const char *a4)
{
  fprintf(stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (0000318C) --------------------------------------------------------
int __fastcall sub_318C(int a1)
{
  int v2; // r4
  unsigned int *v3; // r0
  unsigned int v5; // [sp+4h] [bp-1Ch] BYREF
  unsigned int v6; // [sp+8h] [bp-18h] BYREF

  v2 = 0;
  v5 = 0;
  v6 = 0;
  v3 = sub_22C4(*(unsigned int **)(a1 + 520), (int *)&v5, (int *)&v6);
  if ( sub_2318(a1, (int)v3, v5, v6) == 8 )
    return 1;
  return v2;
}

//----- (000031E0) --------------------------------------------------------
_DWORD *__fastcall sub_31E0(int a1)
{
  int v2; // r0
  _DWORD *result; // r0

  if ( *(_BYTE *)(a1 + 65) )
  {
    if ( *(_BYTE *)(a1 + 64) )
      sub_3888();
    else
      sub_3880();
  }
  if ( (unsigned __int8)*(_WORD *)(a1 + 66) )
  {
    sub_3890();
    v2 = *(unsigned __int8 *)(a1 + 67);
  }
  else
  {
    v2 = HIBYTE(*(unsigned __int16 *)(a1 + 66));
  }
  if ( v2 )
    sub_3898((int *)(a1 + 336));
  result = (_DWORD *)*(unsigned __int8 *)(a1 + 68);
  if ( *(_BYTE *)(a1 + 68) )
    return sub_3930((int *)(a1 + 464));
  return result;
}

//----- (00003238) --------------------------------------------------------
int __fastcall sub_3238(int *a1, int a2, _DWORD *a3)
{
  int v4; // r5
  int v5; // r6
  char *v6; // r1
  int *v7; // r0
  int v8; // r5
  int v9; // r7
  unsigned int v10; // r6
  int v11; // r12
  int (__fastcall *v12)(int, int, int); // lr
  int v13; // r9
  int v14; // r6
  int v15; // r6
  int v16; // r3
  int v17; // r7
  int v19[3]; // [sp+14h] [bp-34h] BYREF
  int v20; // [sp+20h] [bp-28h] BYREF

  v4 = 0;
  v20 = a2;
  v5 = a3[1];
  sub_33DC(v19, 0, a1[1], a3, v5, a1[1], (int)a3, &v20);
  if ( !v19[0] || v19[0] == v5 )
    return v4;
  v6 = (char *)(*(_DWORD *)v19[2] + 8 * v19[0]);
  v7 = (int *)(v6 - 4);
  v8 = *(_DWORD *)v6;
  if ( v6 == &byte_4 )
    return 0;
  v9 = *v7;
  if ( *v7 == 1 )
    return 0;
  if ( v9 < 0 )
  {
    v11 = 1;
    goto LABEL_11;
  }
  v10 = (2 * v9) & 0x80000000 | v9;
  v9 = *(int *)((char *)v7 + v10);
  v7 = (int *)((char *)v7 + v10);
  if ( v9 <= -1 )
  {
    v11 = 0;
LABEL_11:
    v14 = HIBYTE(v9) & 0xF;
    if ( v14 == 2 )
    {
      v12 = sub_28A0;
      v15 = 1;
    }
    else
    {
      if ( v14 != 1 )
      {
        if ( v14 )
          sub_3160(
            "bool libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::getInfoFromEHABISectio"
            "n(pint_t, const libunwind::UnwindInfoSections &) [A = libunwind::LocalAddressSpace, R = libunwind::Registers_arm]",
            "external/libunwind_llvm/src/UnwindCursor.hpp",
            776,
            "unknown personality routine");
        v13 = (int)(v7 + 1);
        if ( v11 )
          v13 = 0;
        v12 = sub_2834;
        goto LABEL_17;
      }
      v12 = sub_2898;
      v15 = 0;
    }
    v16 = BYTE2(v9);
    v17 = v16;
    if ( v16 )
      v17 = 1;
    if ( (v17 & v11) == 1 )
      sub_3160(
        "bool libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::getInfoFromEHABISection(pi"
        "nt_t, const libunwind::UnwindInfoSections &) [A = libunwind::LocalAddressSpace, R = libunwind::Registers_arm]",
        "external/libunwind_llvm/src/UnwindCursor.hpp",
        783,
        "index inlined table detected but pr function requires extra words");
    v13 = (int)&v7[v16 + 1];
    goto LABEL_24;
  }
  v11 = 0;
  v12 = (int (__fastcall *)(int, int, int))((char *)v7 + (v9 | (2 * v9) & 0x80000000));
  v13 = (int)&v7[HIBYTE(v7[1]) + 2];
LABEL_17:
  v15 = 0;
LABEL_24:
  a1[122] = (int)&v6[((2 * *((_DWORD *)v6 - 2)) & 0x80000000 | *((_DWORD *)v6 - 2)) - 8];
  a1[123] = (int)&v6[v8 | (2 * v8) & 0x80000000];
  v4 = 1;
  a1[130] = (int)v7;
  a1[124] = v13;
  a1[125] = (int)v12;
  if ( v15 )
    v15 = 2;
  if ( v11 )
    v15 = 1;
  a1[127] = v15;
  return v4;
}
// 4: using guessed type char;

//----- (000033DC) --------------------------------------------------------
_DWORD *__fastcall sub_33DC(_DWORD *a1, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4
  unsigned int v9; // r5
  int v10; // r6

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + ((2 * *(_DWORD *)(*a4 + 8 * v10)) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *a1 = a2;
  a1[1] = a3;
  a1[2] = a4;
  return a1 + 3;
}

//----- (0000386C) --------------------------------------------------------
int __fastcall sub_386C(int a1)
{
  return (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD))(a1 + 60))(
           *(_DWORD *)a1,
           *(_DWORD *)(a1 + 4),
           *(_DWORD *)(a1 + 8),
           *(_DWORD *)(a1 + 12));
}

//----- (00003880) --------------------------------------------------------
void sub_3880()
{
  ;
}

//----- (00003888) --------------------------------------------------------
void sub_3888()
{
  ;
}

//----- (00003890) --------------------------------------------------------
void sub_3890()
{
  ;
}

//----- (00003898) --------------------------------------------------------
_DWORD *__fastcall sub_3898(int *a1)
{
  int *v5; // r0
  _DWORD *result; // r0

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = v5 + 2;
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (000038DC) --------------------------------------------------------
_DWORD *__fastcall sub_38DC(int *a1)
{
  int *v5; // r0
  _DWORD *result; // r0

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5++;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5++;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = v5 + 1;
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (000038F0) --------------------------------------------------------
// attributes: thunk
void __fastcall operator delete(void *a1)
{
  _ZdlPv(a1);
}

//----- (00003900) --------------------------------------------------------
// attributes: thunk
void __fastcall j_ProductFeature::~ProductFeature(ProductFeature *this)
{
  ProductFeature::~ProductFeature(this);
}

//----- (00003910) --------------------------------------------------------
// attributes: thunk
int __fastcall j___cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle)
{
  return _cxa_atexit(lpfunc, obj, lpdso_handle);
}

//----- (00003920) --------------------------------------------------------
// attributes: thunk
int __fastcall sub_3920(int a1)
{
  return sub_386C(a1);
}

//----- (00003930) --------------------------------------------------------
// attributes: thunk
_DWORD *__fastcall sub_3930(int *a1)
{
  return sub_38DC(a1);
}

// nfuncs=174 queued=103 decompiled=103 lumina nreq=0 worse=0 better=0
// ALL OK, 103 function(s) have been successfully decompiled
