/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void sub_16B0();
// int __fastcall _cxa_finalize(void *);
// int __fastcall _cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle);
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
// int gettimeofday(struct timeval *tv, __timezone_ptr_t tz);
// void __fastcall operator delete(void *); idb
// int pthread_mutex_destroy(pthread_mutex_t *mutex);
// _DWORD __fastcall android::ExynosCamera::releaseRecordingFrame(android::ExynosCamera *__hidden this, const void *); idb
// _DWORD __fastcall android::ExynosCamera::msgTypeEnabled(android::ExynosCamera *__hidden this, int); idb
// _DWORD __fastcall android::ExynosCamera::disableMsgType(android::ExynosCamera *__hidden this, int); idb
// _DWORD __fastcall android::ExynosCamera::enableMsgType(android::ExynosCamera *__hidden this, int); idb
// _DWORD android::VectorImpl::finish_vector(android::VectorImpl *__hidden this); idb
// void __fastcall android::SortedVectorImpl::~SortedVectorImpl(android::SortedVectorImpl *__hidden this); idb
// void *memmove(void *dest, const void *src, size_t n);
// int strcmp(const char *s1, const char *s2);
// void __fastcall android::String8::~String8(android::String8 *__hidden this); idb
// _DWORD android::String8::String8(android::String8 *__hidden this); idb
// _DWORD __fastcall android::String8::String8(android::String8 *__hidden this, const android::String8 *); idb
// int pthread_mutex_lock(pthread_mutex_t *mutex);
// int pthread_mutex_unlock(pthread_mutex_t *mutex);
// void *memset(void *s, int c, size_t n);
// int atoi(const char *nptr);
// void *malloc(size_t size);
// _DWORD __fastcall operator new(unsigned int); idb
// int __fastcall android::ExynosCamera::ExynosCamera(_DWORD, _DWORD, _DWORD); weak
// _DWORD __fastcall android::ExynosCamera::dump(android::ExynosCamera *__hidden this, int); idb
// _DWORD android::ExynosCamera::getCameraId(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::release(android::ExynosCamera *__hidden this); idb
// _DWORD __fastcall android::ExynosCamera::sendCommand(android::ExynosCamera *__hidden this, int, int, int); idb
// void free(void *ptr);
// _DWORD android::ExynosCamera::cancelPicture(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::takePicture_mz(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::cancelAutoFocus(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::autoFocus(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::recordingEnabled(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::stopRecording(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::startRecording(android::ExynosCamera *__hidden this); idb
// _DWORD __fastcall android::ExynosCamera::storeMetaDataInBuffers(android::ExynosCamera *__hidden this, bool); idb
// _DWORD android::ExynosCamera::previewEnabled(android::ExynosCamera *__hidden this); idb
// int usleep(__useconds_t useconds);
// _DWORD android::ExynosCamera::stopPreview(android::ExynosCamera *__hidden this); idb
// _DWORD android::ExynosCamera::startPreview(android::ExynosCamera *__hidden this); idb
// int __fastcall android::ExynosCamera::setCallbacks(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __fastcall android::ExynosCamera::setPreviewWindow(_DWORD, _DWORD); weak
// _DWORD android::ExynosCamera::getParameters(android::ExynosCamera *__hidden this); idb
// _DWORD android::CameraParameters::flatten(android::CameraParameters *__hidden this); idb
// _DWORD __fastcall android::String8::setTo(android::String8 *__hidden this, const android::String8 *); idb
// char *strdup(const char *s);
// void __fastcall android::CameraParameters::~CameraParameters(android::CameraParameters *__hidden this); idb
// _DWORD __fastcall android::String8::String8(android::String8 *__hidden this, const char *); idb
// _DWORD __fastcall android::SortedVectorImpl::SortedVectorImpl(android::SortedVectorImpl *__hidden this, unsigned int, unsigned int); idb
// _DWORD __fastcall android::CameraParameters::unflatten(android::CameraParameters *__hidden this, const android::String8 *); idb
// _DWORD __fastcall android::ExynosCamera::setParameters(android::ExynosCamera *__hidden this, const android::CameraParameters *); idb
// int _aeabi_atexit(void); weak
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_construct(int a1, android::String8 *this, int a3);
void __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_destroy(int, int, int);
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_copy(int a1, android::String8 *this, android::String8 *a3, int a4);
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_splat(int a1, android::String8 *this, android::String8 *a3, int a4);
void *__fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_move_backward(int, void *, const void *, int);
void *__fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_move_backward(int, void *, const void *, int);
unsigned int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_compare(int, const char **, const char **);
char *android::HAL_camera_device_get_parameters();
int sub_1A5C();
int (*__fastcall sub_1A7C(int (*result)(void)))(void);
int __fastcall sub_1AA8(void *a1);
int sub_1AF0();
int sub_1AF4();
int __fastcall sub_1B18(int a1);
void *__fastcall sub_1BA0(void *a1);
int sub_1BB4();
int sub_1BD0();
int sub_1BEC();
int sub_1C08();
int __fastcall sub_1C24(int a1, const void *a2);
int __fastcall sub_1C2A(int a1, int a2);
int __fastcall sub_1C34(int a1, int a2);
int __fastcall sub_1C3A(int a1, int a2);
android::VectorImpl *__fastcall sub_1C40(android::VectorImpl *a1);
android::VectorImpl *__fastcall sub_1C68(android::VectorImpl *a1);
void *__fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_move_backward(int a1, void *a2, const void *a3, int a4);
unsigned int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_compare(int a1, const char **a2, const char **a3);
void __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_destroy(int a1, int a2, int a3);
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_construct(int a1, android::String8 *this, int a3);
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_splat(int a1, android::String8 *this, android::String8 *a3, int a4);
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_copy(int a1, android::String8 *this, android::String8 *a3, int a4);
int __fastcall sub_1D24(pthread_mutex_t *a1);
int __fastcall sub_1D30(int a1, int a2);
_DWORD *__fastcall sub_1EDC(_DWORD *a1, int a2);
int sub_1F24();
int __fastcall sub_1F44(int a1, _DWORD *a2);
int __fastcall sub_1FB4(int a1, const char *a2, int *a3);
int __fastcall sub_2260(int a1, int a2);
int __fastcall sub_228C(int a1);
int __fastcall sub_2394(int a1, int a2, int a3, int a4);
int __fastcall sub_23CC(int a1, void *a2);
int __fastcall sub_23F0(int a1);
int __fastcall sub_2418(int a1);
int __fastcall sub_2440(int a1);
int __fastcall sub_2468(int a1);
int __fastcall sub_2490(int a1);
int __fastcall sub_24B8(int a1);
int __fastcall sub_25C0(int a1);
int __fastcall sub_2708(int a1, _BOOL4 a2);
int __fastcall sub_2738(int a1);
int __fastcall sub_2760(int a1);
int __fastcall sub_292C(int a1);
int __fastcall sub_2A70(int a1, int a2, int a3, int a4, int a5, int a6);
int __fastcall sub_2AB0(int a1, int a2);
int __fastcall sub_2B30(android::ExynosCamera **a1);
char *android::HAL_camera_device_get_parameters();
int __fastcall sub_2D00(int a1, const char *a2);
int __fastcall j_pthread_mutex_destroy(pthread_mutex_t *mutex);
int __fastcall android::ExynosCamera::releaseRecordingFrame(android::ExynosCamera *this, const void *a2);
int __fastcall android::ExynosCamera::disableMsgType(android::ExynosCamera *this, int a2);
int __fastcall android::ExynosCamera::enableMsgType(android::ExynosCamera *this, int a2);
void *__fastcall j_memmove(void *dest, const void *src, size_t n);
int j___aeabi_atexit();

//-------------------------------------------------------------------------
// Data declarations

char *off_4CC0[6] = { "NONE", "OPENED", "RELEASED", "CLOSED", "PREVIEW_RUNNING", "PREVIEW_STOPPED" }; // weak
void *off_4D70 = (void *)0x1C41; // weak
void *off_4DA0 = (void *)0x1B19; // weak
void *off_5000 = &off_5000; // weak
void *off_50B4 = (void *)0x2AB1; // weak
_UNKNOWN unk_5110; // weak
_DWORD dword_5124[2]; // weak
_UNKNOWN unk_512C; // weak
_UNKNOWN unk_5130; // weak
_UNKNOWN unk_5134; // weak
_UNKNOWN unk_5138; // weak
_UNKNOWN unk_513C; // weak
_UNKNOWN unk_5140; // weak
_UNKNOWN unk_5144; // weak
_UNKNOWN unk_5148; // weak
int dword_514C; // weak
int dword_5150[]; // weak
int dword_5158; // weak
int dword_515C; // weak


//----- (000016B0) --------------------------------------------------------
void sub_16B0()
{
  JUMPOUT(0);
}
// 16BC: control flows out of bounds to 0

//----- (0000194C) --------------------------------------------------------
// attributes: thunk
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_construct(
        int a1,
        android::String8 *this,
        int a3)
{
  return _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE12do_constructEPvj(a1, this, a3);
}

//----- (00001958) --------------------------------------------------------
// attributes: thunk
void __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_destroy(
        int a1,
        int a2,
        int a3)
{
  _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE10do_destroyEPvj(a1, a2, a3);
}

//----- (00001964) --------------------------------------------------------
// attributes: thunk
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_copy(
        int a1,
        android::String8 *this,
        android::String8 *a3,
        int a4)
{
  return _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE7do_copyEPvPKvj(a1, this, a3, a4);
}

//----- (00001970) --------------------------------------------------------
// attributes: thunk
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_splat(
        int a1,
        android::String8 *this,
        android::String8 *a3,
        int a4)
{
  return _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE8do_splatEPvPKvj(a1, this, a3, a4);
}

//----- (0000197C) --------------------------------------------------------
// attributes: thunk
void *__fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_move_backward(
        int a1,
        void *a2,
        const void *a3,
        int a4)
{
  return _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE16do_move_backwardEPvPKvj(a1, a2, a3, a4);
}

//----- (00001988) --------------------------------------------------------
// attributes: thunk
void *__fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_move_backward(
        int a1,
        void *a2,
        const void *a3,
        int a4)
{
  return _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE16do_move_backwardEPvPKvj(a1, a2, a3, a4);
}

//----- (00001994) --------------------------------------------------------
// attributes: thunk
unsigned int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_compare(
        int a1,
        const char **a2,
        const char **a3)
{
  return _ZNK7android12SortedVectorINS_16key_value_pair_tINS_7String8ES2_EEE10do_compareEPKvS6_(a1, a2, a3);
}

//----- (000019A0) --------------------------------------------------------
// attributes: thunk
char *android::HAL_camera_device_get_parameters()
{
  return _ZN7android32HAL_camera_device_get_parametersEP13camera_device();
}

//----- (00001A5C) --------------------------------------------------------
int sub_1A5C()
{
  return _cxa_finalize(&off_5000);
}
// 5000: using guessed type void *off_5000;

//----- (00001A7C) --------------------------------------------------------
int (*__fastcall sub_1A7C(int (*result)(void)))(void)
{
  if ( result )
    return (int (*)(void))result();
  return result;
}

//----- (00001AA8) --------------------------------------------------------
int __fastcall sub_1AA8(void *a1)
{
  return _cxa_atexit((void (__fastcall *)(void *))sub_1A7C, a1, &off_5000);
}
// 5000: using guessed type void *off_5000;

//----- (00001AF0) --------------------------------------------------------
int sub_1AF0()
{
  return 0;
}

//----- (00001AF4) --------------------------------------------------------
int sub_1AF4()
{
  _android_log_print(5, "ExynosCameraInterface", "WRN(%s): not supported API level 1.0", "HAL_set_callbacks");
  return 0;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);

//----- (00001B18) --------------------------------------------------------
int __fastcall sub_1B18(int a1)
{
  int v2; // r4

  *(_DWORD *)a1 = &off_4DA0;
  gettimeofday((struct timeval *)(a1 + 12), 0);
  v2 = 1000 * *(_DWORD *)(a1 + 12)
     + *(_DWORD *)(a1 + 16) / 1000
     - (1000 * *(_DWORD *)(a1 + 4)
      + *(_DWORD *)(a1 + 8) / 1000);
  if ( *(_DWORD *)(a1 + 28) )
    _android_log_print(3, "ExynosCameraInterface", "DEBUG:duration time(%5d msec):(%s)", v2, *(const char **)(a1 + 28));
  else
    _android_log_print(3, "ExynosCameraInterface", "DEBUG:duration time(%5d msec):(NULL)", v2);
  return a1;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 4DA0: using guessed type void *;

//----- (00001BA0) --------------------------------------------------------
void *__fastcall sub_1BA0(void *a1)
{
  sub_1B18((int)a1);
  operator delete(a1);
  return a1;
}

//----- (00001BB4) --------------------------------------------------------
int sub_1BB4()
{
  pthread_mutex_destroy((pthread_mutex_t *)&unk_5140);
  return j_pthread_mutex_destroy((pthread_mutex_t *)&unk_513C);
}

//----- (00001BD0) --------------------------------------------------------
int sub_1BD0()
{
  pthread_mutex_destroy((pthread_mutex_t *)&unk_5130);
  return j_pthread_mutex_destroy((pthread_mutex_t *)&unk_512C);
}

//----- (00001BEC) --------------------------------------------------------
int sub_1BEC()
{
  pthread_mutex_destroy((pthread_mutex_t *)&unk_5138);
  return j_pthread_mutex_destroy((pthread_mutex_t *)&unk_5134);
}

//----- (00001C08) --------------------------------------------------------
int sub_1C08()
{
  pthread_mutex_destroy((pthread_mutex_t *)&unk_5148);
  return j_pthread_mutex_destroy((pthread_mutex_t *)&unk_5144);
}

//----- (00001C24) --------------------------------------------------------
int __fastcall sub_1C24(int a1, const void *a2)
{
  return android::ExynosCamera::releaseRecordingFrame(*(android::ExynosCamera **)(a1 + 68), a2);
}

//----- (00001C2A) --------------------------------------------------------
int __fastcall sub_1C2A(int a1, int a2)
{
  return android::ExynosCamera::msgTypeEnabled(*(android::ExynosCamera **)(a1 + 68), a2);
}

//----- (00001C34) --------------------------------------------------------
int __fastcall sub_1C34(int a1, int a2)
{
  return android::ExynosCamera::disableMsgType(*(android::ExynosCamera **)(a1 + 68), a2);
}

//----- (00001C3A) --------------------------------------------------------
int __fastcall sub_1C3A(int a1, int a2)
{
  return android::ExynosCamera::enableMsgType(*(android::ExynosCamera **)(a1 + 68), a2);
}

//----- (00001C40) --------------------------------------------------------
android::VectorImpl *__fastcall sub_1C40(android::VectorImpl *a1)
{
  *(_DWORD *)a1 = &off_4D70;
  android::VectorImpl::finish_vector(a1);
  android::SortedVectorImpl::~SortedVectorImpl(a1);
  return a1;
}
// 4D70: using guessed type void *;

//----- (00001C68) --------------------------------------------------------
android::VectorImpl *__fastcall sub_1C68(android::VectorImpl *a1)
{
  sub_1C40(a1);
  operator delete(a1);
  return a1;
}

//----- (00001C7A) --------------------------------------------------------
void *__fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_move_backward(
        int a1,
        void *a2,
        const void *a3,
        int a4)
{
  return j_memmove(a2, a3, 8 * a4);
}

//----- (00001C84) --------------------------------------------------------
unsigned int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_compare(
        int a1,
        const char **a2,
        const char **a3)
{
  const char *v3; // r4
  const char *v4; // r5
  unsigned int v5; // r6

  v3 = *a3;
  v4 = *a2;
  v5 = strcmp(*a3, *a2);
  return (v5 >> 31) - ((unsigned int)strcmp(v4, v3) >> 31);
}

//----- (00001CA4) --------------------------------------------------------
void __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_destroy(
        int a1,
        int a2,
        int a3)
{
  android::String8 *v5; // r0

  while ( a3 )
  {
    --a3;
    android::String8::~String8((android::String8 *)(a2 + 4));
    v5 = (android::String8 *)a2;
    a2 += 8;
    android::String8::~String8(v5);
  }
}

//----- (00001CC0) --------------------------------------------------------
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_construct(
        int a1,
        android::String8 *this,
        int a3)
{
  android::String8 *v5; // r0
  int result; // r0

  while ( a3 )
  {
    --a3;
    android::String8::String8(this);
    v5 = (android::String8 *)((char *)this + 4);
    this = (android::String8 *)((char *)this + 8);
    result = android::String8::String8(v5);
  }
  return result;
}

//----- (00001CDC) --------------------------------------------------------
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_splat(
        int a1,
        android::String8 *this,
        android::String8 *a3,
        int a4)
{
  const android::String8 *v7; // r7
  int result; // r0

  v7 = (android::String8 *)((char *)a3 + 4);
  while ( a4 )
  {
    android::String8::String8(this, a3);
    result = android::String8::String8((android::String8 *)((char *)this + 4), v7);
    this = (android::String8 *)((char *)this + 8);
    --a4;
  }
  return result;
}

//----- (00001D00) --------------------------------------------------------
int __fastcall android::SortedVector<android::key_value_pair_t<android::String8,android::String8>>::do_copy(
        int a1,
        android::String8 *this,
        android::String8 *a3,
        int a4)
{
  int result; // r0

  while ( a4 )
  {
    android::String8::String8(this, a3);
    result = android::String8::String8((android::String8 *)((char *)this + 4), (android::String8 *)((char *)a3 + 4));
    this = (android::String8 *)((char *)this + 8);
    a3 = (android::String8 *)((char *)a3 + 8);
    --a4;
  }
  return result;
}

//----- (00001D24) --------------------------------------------------------
int __fastcall sub_1D24(pthread_mutex_t *a1)
{
  return -pthread_mutex_lock(a1);
}

//----- (00001D30) --------------------------------------------------------
int __fastcall sub_1D30(int a1, int a2)
{
  pthread_mutex_t *v4; // r6
  int v5; // r0
  bool v6; // zf
  int v7; // r1
  int v8; // r3
  int v9; // r2
  int v10; // r0
  int v11; // r4
  int v13; // [sp+0h] [bp-28h]
  int v14; // [sp+0h] [bp-28h]
  int v15; // [sp+4h] [bp-24h]
  int v16; // [sp+4h] [bp-24h]

  v4 = (pthread_mutex_t *)((char *)&unk_5144 + 4 * a2);
  sub_1D24(v4);
  _android_log_print(
    3,
    "ExynosCameraInterface",
    "DEBUG(%s):camera(%d) state(%d) checking...",
    "check_camera_state",
    a2,
    a1);
  switch ( a1 )
  {
    case 0:
      goto LABEL_23;
    case 1:
      v5 = dword_5124[a2];
      if ( !v5 )
        goto LABEL_23;
      v6 = v5 == 3;
      break;
    case 2:
      v7 = dword_5124[a2];
      if ( v7 == a1 )
        goto LABEL_23;
      goto LABEL_10;
    case 3:
      v8 = dword_5124[a2];
      if ( v8 == a1 || (unsigned int)(v8 - 1) <= 1 )
        goto LABEL_23;
      v6 = v8 == 5;
      break;
    case 4:
      v7 = dword_5124[a2];
LABEL_10:
      v6 = (v7 & 0xFFFFFFFB) == 1;
      break;
    case 5:
      v9 = dword_5124[a2];
      if ( v9 == a1 || v9 == 1 )
        goto LABEL_23;
      goto LABEL_15;
    case 6:
      v9 = dword_5124[a2];
LABEL_15:
      if ( v9 == 4 )
        goto LABEL_23;
      v6 = v9 == 7;
      break;
    case 7:
      v10 = dword_5124[a2];
      if ( v10 == a1 )
        goto LABEL_23;
      v6 = v10 == 6;
      break;
    default:
      _android_log_print(
        6,
        "ExynosCameraInterface",
        "ERR(%s):camera(%d) state(%s) is unknown value",
        "check_camera_state",
        a2,
        off_4CC0[a1]);
      goto LABEL_24;
  }
  if ( v6 )
  {
LABEL_23:
    v13 = a2;
    v15 = dword_5124[a2];
    v11 = 1;
    _android_log_print(
      3,
      "ExynosCameraInterface",
      "DEBUG(%s):camera(%d) state(%d:%s->%d:%s) is valid",
      "check_camera_state",
      v13,
      v15,
      off_4CC0[v15],
      a1,
      off_4CC0[a1]);
  }
  else
  {
LABEL_24:
    v14 = a2;
    v16 = dword_5124[a2];
    v11 = 0;
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d:%s->%d:%s) is INVALID",
      "check_camera_state",
      v14,
      v16,
      off_4CC0[v16],
      a1,
      off_4CC0[a1]);
  }
  pthread_mutex_unlock(v4);
  return v11;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 4CC0: using guessed type char *off_4CC0[6];
// 5124: using guessed type _DWORD dword_5124[2];

//----- (00001EDC) --------------------------------------------------------
_DWORD *__fastcall sub_1EDC(_DWORD *a1, int a2)
{
  struct timeval *v4; // r5

  *a1 = &off_4DA0;
  v4 = (struct timeval *)(a1 + 1);
  memset(a1 + 1, 0, 8u);
  memset(a1 + 3, 0, 8u);
  a1[7] = a2;
  gettimeofday(v4, 0);
  return a1;
}
// 4DA0: using guessed type void *off_4DA0;

//----- (00001F24) --------------------------------------------------------
int sub_1F24()
{
  _DWORD v1[10]; // [sp+0h] [bp-28h] BYREF

  sub_1EDC(v1, (int)"HAL_getNumberOfCameras");
  sub_1B18((int)v1);
  return 2;
}

//----- (00001F44) --------------------------------------------------------
int __fastcall sub_1F44(int a1, _DWORD *a2)
{
  _DWORD *v4; // r2
  int v5; // r4
  int v6; // r1
  int v8; // [sp+0h] [bp-38h]
  _DWORD v9[12]; // [sp+8h] [bp-30h] BYREF

  sub_1EDC(v9, (int)"HAL_getCameraInfo");
  if ( a1 < 0 || a1 >= sub_1F24() )
  {
    v8 = a1;
    v5 = -22;
    _android_log_print(6, "ExynosCameraInterface", "ERR(%s):Invalid camera ID %d", "HAL_getCameraInfo", v8);
  }
  else
  {
    v4 = (_DWORD *)((char *)&unk_5110 + 8 * a1);
    v5 = 0;
    v6 = v4[1];
    *a2 = *v4;
    a2[1] = v6;
    a2[2] = 256;
  }
  sub_1B18((int)v9);
  return v5;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 1F44: using guessed type _DWORD var_30[12];

//----- (00001FB4) --------------------------------------------------------
int __fastcall sub_1FB4(int a1, const char *a2, int *a3)
{
  int v6; // r4
  int v7; // r0
  unsigned int v8; // r11
  int v9; // r3
  int *v10; // r2
  int v11; // t1
  int v12; // r4
  void *v13; // r0
  _DWORD *v14; // r3
  int v15; // r11
  int v16; // r5
  int v18; // [sp+0h] [bp-10h]
  int v19; // [sp+4h] [bp-Ch]
  _DWORD v20[9]; // [sp+10h] [bp+0h] BYREF

  sub_1EDC(v20, (int)"HAL_camera_device_open");
  v6 = atoi(a2);
  _android_log_print(4, "ExynosCameraInterface", "INFO(%s[%d]):camera(%d) in", "HAL_camera_device_open", 52, v6);
  v7 = sub_1F24();
  v8 = v7;
  if ( v6 < 0 || v6 >= v7 )
  {
    _android_log_print(6, "ExynosCameraInterface", "ERR(%s):Invalid camera ID %s", "HAL_camera_device_open", a2);
LABEL_22:
    v12 = -22;
    goto LABEL_25;
  }
  v9 = 0;
  v10 = &dword_514C;
  while ( v9 < v7 )
  {
    v11 = v10[1];
    ++v10;
    if ( v11 )
    {
      if ( v6 == v9 )
      {
        _android_log_print(
          6,
          "ExynosCameraInterface",
          "DEBUG(%s): Camera %d was opend already",
          "HAL_camera_device_open",
          v6);
        goto LABEL_22;
      }
      if ( v6 == v9 + 1 )
        goto LABEL_12;
    }
    if ( v10[1] && v6 == v9 )
    {
LABEL_12:
      v12 = -87;
      _android_log_print(
        6,
        "ExynosCameraInterface",
        "DEBUG(%s): Can't poen the two camera in same time:",
        "HAL_camera_device_open");
      goto LABEL_25;
    }
    ++v9;
  }
  if ( sub_1D30(1, v6) )
  {
    if ( v6 >= v8 )
    {
      _android_log_print(
        6,
        "ExynosCameraInterface",
        "DEBUG(%s):camera(%s) open fail - must front camera open first",
        "HAL_camera_device_open",
        a2);
      goto LABEL_22;
    }
    if ( dword_5150[v6] )
    {
      _android_log_print(
        6,
        "ExynosCameraInterface",
        "DEBUG(%s):returning existing camera ID %s",
        "HAL_camera_device_open",
        a2);
      *a3 = dword_5150[v6];
    }
    else
    {
      v13 = malloc(0x48u);
      dword_5150[v6] = (int)v13;
      if ( !v13 )
      {
        v12 = -12;
        goto LABEL_25;
      }
      sub_1D24((pthread_mutex_t *)((char *)&unk_5134 + 4 * v6));
      v14 = (_DWORD *)dword_5150[v6];
      v14[2] = a1;
      *v14 = 1213678676;
      v14[1] = 1;
      v14[15] = sub_2B30;
      v14[16] = &off_50B4;
      _android_log_print(6, "ExynosCameraInterface", "DEBUG(%s):open camera %s", "HAL_camera_device_open", a2);
      v15 = operator new(0x17990u);
      android::ExynosCamera::ExynosCamera(v15, v6, dword_5150[v6]);
      v16 = dword_5150[v6];
      *(_DWORD *)(v16 + 68) = v15;
      *a3 = v16;
      _android_log_print(
        4,
        "ExynosCameraInterface",
        "INFO(%s[%d]):camera(%d) out from new g_cam_device[%d]->priv()",
        "HAL_camera_device_open",
        102,
        v6,
        v6);
      pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5134 + 4 * v6));
      _android_log_print(
        4,
        "ExynosCameraInterface",
        "INFO(%s[%d]):camera(%d) unlocked..",
        "HAL_camera_device_open",
        105,
        v6);
    }
    sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * v6));
    dword_5124[v6] = 1;
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * v6));
    v19 = v6;
    v12 = 0;
    _android_log_print(4, "ExynosCameraInterface", "INFO(%s[%d]):camera(%d) out", "HAL_camera_device_open", 116, v19);
  }
  else
  {
    v18 = v6;
    v12 = -1;
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d) is INVALID",
      "HAL_camera_device_open",
      v18,
      1);
  }
LABEL_25:
  sub_1B18((int)v20);
  return v12;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 17D8: using guessed type int __fastcall android::ExynosCamera::ExynosCamera(_DWORD, _DWORD, _DWORD);
// 2B30: using guessed type int sub_2B30();
// 50B4: using guessed type void *off_50B4;
// 5124: using guessed type _DWORD dword_5124[2];
// 514C: using guessed type int dword_514C;
// 5150: using guessed type int dword_5150[];

//----- (00002260) --------------------------------------------------------
int __fastcall sub_2260(int a1, int a2)
{
  int v4; // r4
  _DWORD v6[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v6, (int)"HAL_camera_device_dump");
  v4 = android::ExynosCamera::dump(*(android::ExynosCamera **)(a1 + 68), a2);
  sub_1B18((int)v6);
  return v4;
}

//----- (0000228C) --------------------------------------------------------
int __fastcall sub_228C(int a1)
{
  int CameraId; // r4
  _DWORD v4[8]; // [sp+8h] [bp+0h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_release");
  CameraId = android::ExynosCamera::getCameraId(*(android::ExynosCamera **)(a1 + 68));
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) in",
    "HAL_camera_device_release",
    514,
    CameraId);
  if ( sub_1D30(2, CameraId) )
  {
    sub_1D24((pthread_mutex_t *)((char *)&unk_5134 + 4 * CameraId));
    android::ExynosCamera::release(*(android::ExynosCamera **)(a1 + 68));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out from release()",
      "HAL_camera_device_release",
      527,
      CameraId);
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5134 + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) unlocked..",
      "HAL_camera_device_release",
      531,
      CameraId);
    sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    dword_5124[CameraId] = 2;
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out",
      "HAL_camera_device_release",
      536,
      CameraId);
  }
  else
  {
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d) is INVALID",
      "HAL_camera_device_release",
      CameraId,
      2);
  }
  return sub_1B18((int)v4);
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5124: using guessed type _DWORD dword_5124[2];

//----- (00002394) --------------------------------------------------------
int __fastcall sub_2394(int a1, int a2, int a3, int a4)
{
  int v8; // r4
  _DWORD v10[14]; // [sp+0h] [bp-38h] BYREF

  sub_1EDC(v10, (int)"HAL_camera_device_send_command");
  v8 = android::ExynosCamera::sendCommand(*(android::ExynosCamera **)(a1 + 68), a2, a3, a4);
  sub_1B18((int)v10);
  return v8;
}

//----- (000023CC) --------------------------------------------------------
int __fastcall sub_23CC(int a1, void *a2)
{
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_put_parameters");
  free(a2);
  return sub_1B18((int)v4);
}

//----- (000023F0) --------------------------------------------------------
int __fastcall sub_23F0(int a1)
{
  int v2; // r4
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_cancel_picture");
  v2 = android::ExynosCamera::cancelPicture(*(android::ExynosCamera **)(a1 + 68));
  sub_1B18((int)v4);
  return v2;
}

//----- (00002418) --------------------------------------------------------
int __fastcall sub_2418(int a1)
{
  int v2; // r4
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_take_picture");
  v2 = android::ExynosCamera::takePicture_mz(*(android::ExynosCamera **)(a1 + 68));
  sub_1B18((int)v4);
  return v2;
}

//----- (00002440) --------------------------------------------------------
int __fastcall sub_2440(int a1)
{
  int v2; // r4
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_cancel_auto_focus");
  v2 = android::ExynosCamera::cancelAutoFocus(*(android::ExynosCamera **)(a1 + 68));
  sub_1B18((int)v4);
  return v2;
}

//----- (00002468) --------------------------------------------------------
int __fastcall sub_2468(int a1)
{
  int v2; // r4
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_auto_focus");
  v2 = android::ExynosCamera::autoFocus(*(android::ExynosCamera **)(a1 + 68));
  sub_1B18((int)v4);
  return v2;
}

//----- (00002490) --------------------------------------------------------
int __fastcall sub_2490(int a1)
{
  int v2; // r4
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_recording_enabled");
  v2 = android::ExynosCamera::recordingEnabled(*(android::ExynosCamera **)(a1 + 68));
  sub_1B18((int)v4);
  return v2;
}

//----- (000024B8) --------------------------------------------------------
int __fastcall sub_24B8(int a1)
{
  int CameraId; // r4
  _DWORD v4[8]; // [sp+8h] [bp+0h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_stop_recording");
  CameraId = android::ExynosCamera::getCameraId(*(android::ExynosCamera **)(a1 + 68));
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) in",
    "HAL_camera_device_stop_recording",
    379,
    CameraId);
  if ( sub_1D30(7, CameraId) )
  {
    sub_1D24((pthread_mutex_t *)((char *)&unk_513C + 4 * CameraId));
    android::ExynosCamera::stopRecording(*(android::ExynosCamera **)(a1 + 68));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out from stopRecording()",
      "HAL_camera_device_stop_recording",
      391,
      CameraId);
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_513C + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) unlocked..",
      "HAL_camera_device_stop_recording",
      395,
      CameraId);
    sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    dword_5124[CameraId] = 7;
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out",
      "HAL_camera_device_stop_recording",
      400,
      CameraId);
  }
  else
  {
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d) is INVALID",
      "HAL_camera_device_stop_recording",
      CameraId,
      7);
  }
  return sub_1B18((int)v4);
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5124: using guessed type _DWORD dword_5124[2];

//----- (000025C0) --------------------------------------------------------
int __fastcall sub_25C0(int a1)
{
  int CameraId; // r4
  int v3; // r4
  int v5; // [sp+0h] [bp-8h]
  _DWORD v6[8]; // [sp+8h] [bp+0h] BYREF

  sub_1EDC(v6, (int)"HAL_camera_device_start_recording");
  CameraId = android::ExynosCamera::getCameraId(*(android::ExynosCamera **)(a1 + 68));
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) in",
    "HAL_camera_device_start_recording",
    340,
    CameraId);
  if ( sub_1D30(6, CameraId) )
  {
    sub_1D24((pthread_mutex_t *)((char *)&unk_513C + 4 * CameraId));
    dword_5158 = android::ExynosCamera::startRecording(*(android::ExynosCamera **)(a1 + 68));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out from startRecording()",
      "HAL_camera_device_start_recording",
      353,
      CameraId);
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_513C + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) unlocked..",
      "HAL_camera_device_start_recording",
      357,
      CameraId);
    if ( dword_5158 )
    {
      _android_log_print(
        4,
        "ExynosCameraInterface",
        "INFO(%s[%d]):camera(%d) out (startRecording FAILED)",
        "HAL_camera_device_start_recording",
        367,
        CameraId);
    }
    else
    {
      sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
      dword_5124[CameraId] = 6;
      pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
      _android_log_print(
        4,
        "ExynosCameraInterface",
        "INFO(%s[%d]):camera(%d) out (startRecording succeeded)",
        "HAL_camera_device_start_recording",
        364,
        CameraId);
    }
    v3 = dword_5158;
  }
  else
  {
    v5 = CameraId;
    v3 = -1;
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d) is INVALID",
      "HAL_camera_device_start_recording",
      v5,
      6);
  }
  sub_1B18((int)v6);
  return v3;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5124: using guessed type _DWORD dword_5124[2];
// 5158: using guessed type int dword_5158;

//----- (00002708) --------------------------------------------------------
int __fastcall sub_2708(int a1, _BOOL4 a2)
{
  bool v4; // r1
  int v5; // r4
  _DWORD v7[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v7, (int)"HAL_camera_device_store_meta_data_in_buffers");
  v4 = a2;
  if ( a2 )
    v4 = 1;
  v5 = android::ExynosCamera::storeMetaDataInBuffers(*(android::ExynosCamera **)(a1 + 68), v4);
  sub_1B18((int)v7);
  return v5;
}

//----- (00002738) --------------------------------------------------------
int __fastcall sub_2738(int a1)
{
  int v2; // r4
  _DWORD v4[12]; // [sp+0h] [bp-30h] BYREF

  sub_1EDC(v4, (int)"HAL_camera_device_preview_enabled");
  v2 = android::ExynosCamera::previewEnabled(*(android::ExynosCamera **)(a1 + 68));
  sub_1B18((int)v4);
  return v2;
}

//----- (00002760) --------------------------------------------------------
int __fastcall sub_2760(int a1)
{
  int CameraId; // r4
  int v3; // r7
  _DWORD v5[16]; // [sp+8h] [bp-40h] BYREF

  sub_1EDC(v5, (int)"HAL_camera_device_stop_preview");
  CameraId = android::ExynosCamera::getCameraId(*(android::ExynosCamera **)(a1 + 68));
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) in",
    "HAL_camera_device_stop_preview",
    268,
    CameraId);
  if ( dword_5124[CameraId] == 6 )
  {
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s[%d]):camera(%d) in RECORDING RUNNING state ---- INVALID ----",
      "HAL_camera_device_stop_preview",
      274,
      CameraId);
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s[%d]):camera(%d) The stop_recording must be called before the stop_preview  ---- INVALID ----",
      "HAL_camera_device_stop_preview",
      277,
      CameraId);
    sub_24B8(a1);
    v3 = 30;
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s[%d]):cameraId=%d out from stop_recording  ---- INVALID ----",
      "HAL_camera_device_stop_preview",
      280,
      CameraId);
    do
    {
      _android_log_print(
        6,
        "ExynosCameraInterface",
        "ERR(%s[%d]):camera(%d) The stop_recording must be called before the stop_preview  ---- INVALID ----",
        "HAL_camera_device_stop_preview",
        285,
        CameraId);
      --v3;
    }
    while ( v3 );
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s[%d]):camera(%d) sleep 500ms for ---- INVALID ---- state",
      "HAL_camera_device_stop_preview",
      288,
      CameraId);
    usleep(0x7A120u);
  }
  if ( sub_1D30(5, CameraId) )
  {
    sub_1D24((pthread_mutex_t *)((char *)&unk_512C + 4 * CameraId));
    android::ExynosCamera::stopPreview(*(android::ExynosCamera **)(a1 + 68));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out from stopPreview()",
      "HAL_camera_device_stop_preview",
      302,
      CameraId);
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_512C + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) unlocked..",
      "HAL_camera_device_stop_preview",
      306,
      CameraId);
    sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    dword_5124[CameraId] = 5;
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out",
      "HAL_camera_device_stop_preview",
      311,
      CameraId);
  }
  else
  {
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d) is INVALID",
      "HAL_camera_device_stop_preview",
      CameraId,
      5);
  }
  return sub_1B18((int)v5);
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5124: using guessed type _DWORD dword_5124[2];
// 2760: using guessed type _DWORD var_40[16];

//----- (0000292C) --------------------------------------------------------
int __fastcall sub_292C(int a1)
{
  int CameraId; // r4
  int v3; // r4
  int v5; // [sp+0h] [bp-8h]
  _DWORD v6[8]; // [sp+8h] [bp+0h] BYREF

  sub_1EDC(v6, (int)"HAL_camera_device_start_preview");
  CameraId = android::ExynosCamera::getCameraId(*(android::ExynosCamera **)(a1 + 68));
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) in",
    "HAL_camera_device_start_preview",
    229,
    CameraId);
  if ( sub_1D30(4, CameraId) )
  {
    sub_1D24((pthread_mutex_t *)((char *)&unk_512C + 4 * CameraId));
    dword_514C = android::ExynosCamera::startPreview(*(android::ExynosCamera **)(a1 + 68));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) out from startPreview()",
      "HAL_camera_device_start_preview",
      242,
      CameraId);
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_512C + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) unlocked..",
      "HAL_camera_device_start_preview",
      246,
      CameraId);
    if ( dword_514C )
    {
      _android_log_print(
        4,
        "ExynosCameraInterface",
        "INFO(%s[%d]):camera(%d) out (startPreview FAILED)",
        "HAL_camera_device_start_preview",
        256,
        CameraId);
    }
    else
    {
      sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
      dword_5124[CameraId] = 4;
      pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
      _android_log_print(
        4,
        "ExynosCameraInterface",
        "INFO(%s[%d]):camera(%d) out (startPreview succeeded)",
        "HAL_camera_device_start_preview",
        253,
        CameraId);
    }
    v3 = dword_514C;
  }
  else
  {
    v5 = CameraId;
    v3 = -1;
    _android_log_print(
      6,
      "ExynosCameraInterface",
      "ERR(%s):camera(%d) state(%d) is INVALID",
      "HAL_camera_device_start_preview",
      v5,
      4);
  }
  sub_1B18((int)v6);
  return v3;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5124: using guessed type _DWORD dword_5124[2];
// 514C: using guessed type int dword_514C;

//----- (00002A70) --------------------------------------------------------
int __fastcall sub_2A70(int a1, int a2, int a3, int a4, int a5, int a6)
{
  _DWORD v11[14]; // [sp+8h] [bp-38h] BYREF

  sub_1EDC(v11, (int)"HAL_camera_device_set_callbacks");
  android::ExynosCamera::setCallbacks(*(_DWORD *)(a1 + 68), a2, a3, a4, a5, a6);
  return sub_1B18((int)v11);
}
// 18B0: using guessed type int __fastcall android::ExynosCamera::setCallbacks(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 2A70: using guessed type _DWORD var_38[14];

//----- (00002AB0) --------------------------------------------------------
int __fastcall sub_2AB0(int a1, int a2)
{
  int CameraId; // r8
  int v5; // r4
  _DWORD v7[16]; // [sp+8h] [bp-40h] BYREF

  sub_1EDC(v7, (int)"HAL_camera_device_set_preview_window");
  CameraId = android::ExynosCamera::getCameraId(*(android::ExynosCamera **)(a1 + 68));
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) in",
    "HAL_camera_device_set_preview_window",
    176,
    CameraId);
  dword_515C = android::ExynosCamera::setPreviewWindow(*(_DWORD *)(a1 + 68), a2);
  _android_log_print(
    4,
    "ExynosCameraInterface",
    "INFO(%s[%d]):camera(%d) out",
    "HAL_camera_device_set_preview_window",
    178,
    CameraId);
  v5 = dword_515C;
  sub_1B18((int)v7);
  return v5;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 18BC: using guessed type int __fastcall android::ExynosCamera::setPreviewWindow(_DWORD, _DWORD);
// 515C: using guessed type int dword_515C;
// 2AB0: using guessed type _DWORD var_40[16];

//----- (00002B30) --------------------------------------------------------
int __fastcall sub_2B30(android::ExynosCamera **a1)
{
  int CameraId; // r4
  int v3; // r9
  android::ExynosCamera *v4; // r0
  _DWORD v6[16]; // [sp+8h] [bp-40h] BYREF

  sub_1EDC(v6, (int)"HAL_camera_device_close");
  _android_log_print(4, "ExynosCameraInterface", "INFO(%s[%d]): in", "HAL_camera_device_close", 131);
  if ( !a1 )
  {
LABEL_7:
    v3 = 0;
    _android_log_print(4, "ExynosCameraInterface", "INFO(%s[%d]): out", "HAL_camera_device_close", 161);
    goto LABEL_8;
  }
  CameraId = android::ExynosCamera::getCameraId(a1[17]);
  _android_log_print(4, "ExynosCameraInterface", "INFO(%s[%d]):camera(%d)", "HAL_camera_device_close", 137, CameraId);
  if ( sub_1D30(3, CameraId) )
  {
    sub_1D24((pthread_mutex_t *)((char *)&unk_5134 + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) locked..",
      "HAL_camera_device_close",
      147,
      CameraId);
    dword_5150[CameraId] = 0;
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5134 + 4 * CameraId));
    _android_log_print(
      4,
      "ExynosCameraInterface",
      "INFO(%s[%d]):camera(%d) unlocked..",
      "HAL_camera_device_close",
      150,
      CameraId);
    v4 = a1[17];
    if ( v4 )
      (*(void (__fastcall **)(android::ExynosCamera *))(*(_DWORD *)v4 + 32))(v4);
    free(a1);
    sub_1D24((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    dword_5124[CameraId] = 3;
    pthread_mutex_unlock((pthread_mutex_t *)((char *)&unk_5144 + 4 * CameraId));
    _android_log_print(4, "ExynosCameraInterface", "INFO(%s[%d]):camera(%d)", "HAL_camera_device_close", 158, CameraId);
    goto LABEL_7;
  }
  v3 = -1;
  _android_log_print(
    6,
    "ExynosCameraInterface",
    "ERR(%s):camera(%d) state(%d) is INVALID",
    "HAL_camera_device_close",
    CameraId,
    3);
LABEL_8:
  sub_1B18((int)v6);
  return v3;
}
// 16DC: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 5124: using guessed type _DWORD dword_5124[2];
// 5150: using guessed type int dword_5150[];
// 2B30: using guessed type _DWORD var_40[16];

//----- (00002CA0) --------------------------------------------------------
char *android::HAL_camera_device_get_parameters()
{
  char *v0; // r6
  char *s; // [sp+0h] [bp-20h] BYREF
  char v3[4]; // [sp+4h] [bp-1Ch] BYREF
  char v4[24]; // [sp+8h] [bp-18h] BYREF
  _DWORD v5[9]; // [sp+20h] [bp+0h] BYREF

  sub_1EDC(v5, (int)"HAL_camera_device_get_parameters");
  android::String8::String8((android::String8 *)&s);
  android::ExynosCamera::getParameters((android::ExynosCamera *)v4);
  android::CameraParameters::flatten((android::CameraParameters *)v3);
  android::String8::setTo((android::String8 *)&s, (const android::String8 *)v3);
  android::String8::~String8((android::String8 *)v3);
  v0 = strdup(s);
  android::CameraParameters::~CameraParameters((android::CameraParameters *)v4);
  android::String8::~String8((android::String8 *)&s);
  sub_1B18((int)v5);
  return v0;
}
// 2CA0: using guessed type char var_40[4];

//----- (00002D00) --------------------------------------------------------
int __fastcall sub_2D00(int a1, const char *a2)
{
  int v4; // r8
  int v6; // [sp+0h] [bp-20h] BYREF
  char v7[4]; // [sp+4h] [bp-1Ch] BYREF
  int v8[5]; // [sp+8h] [bp-18h] BYREF
  int v9; // [sp+1Ch] [bp-4h] BYREF
  _DWORD v10[9]; // [sp+20h] [bp+0h] BYREF

  sub_1EDC(v10, (int)"HAL_camera_device_set_parameters");
  android::String8::String8((android::String8 *)&v6, a2);
  android::String8::String8((android::String8 *)v7);
  android::SortedVectorImpl::SortedVectorImpl((android::SortedVectorImpl *)v8, 8u, 0);
  v8[0] = (int)&off_4D70;
  android::String8::String8((android::String8 *)&v9, (const android::String8 *)v7);
  android::String8::~String8((android::String8 *)v7);
  android::CameraParameters::unflatten((android::CameraParameters *)v8, (const android::String8 *)&v6);
  v4 = android::ExynosCamera::setParameters(*(android::ExynosCamera **)(a1 + 68), (const android::CameraParameters *)v8);
  android::CameraParameters::~CameraParameters((android::CameraParameters *)v8);
  android::String8::~String8((android::String8 *)&v6);
  sub_1B18((int)v10);
  return v4;
}
// 4D70: using guessed type void *off_4D70;
// 2D00: using guessed type char var_40[4];

//----- (00002D90) --------------------------------------------------------
// attributes: thunk
int __fastcall j_pthread_mutex_destroy(pthread_mutex_t *mutex)
{
  return pthread_mutex_destroy(mutex);
}

//----- (00002DA0) --------------------------------------------------------
// attributes: thunk
int __fastcall android::ExynosCamera::releaseRecordingFrame(android::ExynosCamera *this, const void *a2)
{
  return _ZN7android12ExynosCamera21releaseRecordingFrameEPKv(this, a2);
}

//----- (00002DB0) --------------------------------------------------------
// attributes: thunk
int __fastcall android::ExynosCamera::disableMsgType(android::ExynosCamera *this, int a2)
{
  return _ZN7android12ExynosCamera14disableMsgTypeEi(this, a2);
}

//----- (00002DC0) --------------------------------------------------------
// attributes: thunk
int __fastcall android::ExynosCamera::enableMsgType(android::ExynosCamera *this, int a2)
{
  return _ZN7android12ExynosCamera13enableMsgTypeEi(this, a2);
}

//----- (00002DD0) --------------------------------------------------------
// attributes: thunk
void *__fastcall j_memmove(void *dest, const void *src, size_t n)
{
  return memmove(dest, src, n);
}

//----- (00002DE0) --------------------------------------------------------
// attributes: thunk
int j___aeabi_atexit()
{
  return _aeabi_atexit();
}
// 1940: using guessed type int _aeabi_atexit(void);

// nfuncs=174 queued=64 decompiled=64 lumina nreq=0 worse=0 better=0
// ALL OK, 64 function(s) have been successfully decompiled
