/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void sub_758();
// int __fastcall _cxa_finalize(void *);
// int __fastcall _cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle);
// int __fastcall _register_atfork(_DWORD, _DWORD, _DWORD, _DWORD); weak
// void *malloc(size_t size);
// void __fastcall _aeabi_memclr4(void *, size_t); idb
// int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD); weak
// void free(void *ptr);
// int set_effect(void); weak
// int __fastcall set_effect_current_level(_DWORD); weak
// int get_effect_current_level(void); weak
// int init_effect(void); weak
// int deinit_effect(void); weak
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// void __fastcall _aeabi_memcpy(void *, const void *, size_t); idb
// void __fastcall _aeabi_memclr8(void *, size_t); idb
// int __fastcall dladdr(_DWORD, _DWORD); weak
// int _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, const char *, ...); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_85C();
int (*__fastcall sub_87C(int (*result)(void)))(void);
int __fastcall sub_8A8(void *a1);
int __fastcall sub_8F4(int a1, int a2, int a3);
int __fastcall sub_93C(int a1, int a2, _DWORD *a3);
int __fastcall sub_9E4(void *a1);
int __fastcall sub_9EE(int a1);
int sub_A00(); // weak
int sub_A04(); // weak
int sub_A08(); // weak
unsigned int *__fastcall sub_A18(unsigned int *result, int *a2, int *a3);
int __fastcall sub_A6C(int a1, int a2, unsigned int a3, unsigned int a4);
int __fastcall sub_DB0(int a1, int a2, unsigned int a3, int a4, int *a5);
int __fastcall sub_E4C(int a1, int a2, unsigned int a3, int a4);
int __fastcall sub_F88(int a1, int a2, int a3);
void sub_FEC();
void sub_FF4();
int __fastcall sub_FFC(int *a1, int a2, int a3, int a4);
int __fastcall sub_10A8(const void *a1, int *a2, char a3);
void __fastcall __noreturn sub_1198(int *a1, int a2, int a3, int a4);
void __fastcall __noreturn sub_11CC(const char *a1, int a2, const char *a3);
int __fastcall sub_11FC(int a1);
int __fastcall sub_1238(int a1);
int __fastcall sub_1280(int a1, int a2);
int __fastcall sub_1294(_DWORD *a1, int a2, int a3, int a4, int a5);
_QWORD *__fastcall sub_12AC(_QWORD *result);
_QWORD *__fastcall sub_12B4(_QWORD *result);
_QWORD *__fastcall sub_12BC(_QWORD *result);
void sub_12C4();
void sub_1308();
int __fastcall sub_131C(int a1, const void *a2);
int __fastcall sub_1360(int a1, int a2, _DWORD *a3);
int __fastcall sub_138E(int a1, int a2, int a3);
int __fastcall sub_13D2(int a1, int a2, _QWORD *a3);
int __fastcall sub_1402(int a1, int a2, int a3, int a4);
int __fastcall sub_143A(int a1);
int __fastcall sub_1440(int a1, int a2);
int __fastcall sub_145E(int a1);
int __fastcall sub_1470(int a1);
int __fastcall sub_1476(int a1, int a2);
int __fastcall sub_1498(int a1, int a2);
int __fastcall sub_1524(int result, int a2, int a3);
int __fastcall sub_15B0(int a1, int a2);
__int64 __fastcall sub_15D4(int a1, int a2);
int __fastcall sub_1678(int a1, int a2, int a3, int a4);
int __fastcall sub_1744(_DWORD *a1);
_DWORD *__fastcall sub_1794(int a1, _DWORD *a2);
int __fastcall sub_17AC(int a1);
int __fastcall sub_17C2(int a1);
int __fastcall sub_17C8(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_1838(int *a1, int a2);
int __fastcall sub_18AE(int result);
void __fastcall __noreturn sub_18B8(const char *a1, const char *a2, int a3, const char *a4);
int __fastcall sub_18E4(int a1);
_DWORD *__fastcall sub_1938(int a1);
int __fastcall sub_1990(int *a1, int a2, _DWORD *a3);
_DWORD *__fastcall sub_1B34(_DWORD *a1, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int __fastcall sub_1FC4(int a1);
void sub_1FD8();
void sub_1FE0();
void sub_1FE8();
_DWORD *__fastcall sub_1FF0(int *a1);
_DWORD *__fastcall sub_2034(int *a1);
int j_get_effect_current_level();
int j_init_effect();
int j_deinit_effect();
int __fastcall sub_2078(int a1);
_DWORD *__fastcall sub_2088(int *a1);

//-------------------------------------------------------------------------
// Data declarations

char byte_4 = '\x01'; // weak
_UNKNOWN j_j_get_effect_current_level; // weak
_UNKNOWN j_j_init_effect; // weak
_UNKNOWN j_j_deinit_effect; // weak
void *off_3E38 = (void *)0x1195; // weak
void *off_4000 = &off_4000; // weak
_UNKNOWN unk_4088; // weak
// extern _UNKNOWN _stack_chk_guard; weak
// extern struct _IO_FILE *stderr;


//----- (00000758) --------------------------------------------------------
void sub_758()
{
  JUMPOUT(0);
}
// 764: control flows out of bounds to 0

//----- (0000085C) --------------------------------------------------------
int sub_85C()
{
  return _cxa_finalize(&off_4000);
}
// 4000: using guessed type void *off_4000;

//----- (0000087C) --------------------------------------------------------
int (*__fastcall sub_87C(int (*result)(void)))(void)
{
  if ( result )
    return (int (*)(void))result();
  return result;
}

//----- (000008A8) --------------------------------------------------------
int __fastcall sub_8A8(void *a1)
{
  return _cxa_atexit((void (__fastcall *)(void *))sub_87C, a1, &off_4000);
}
// 4000: using guessed type void *off_4000;

//----- (000008F4) --------------------------------------------------------
int __fastcall sub_8F4(int a1, int a2, int a3)
{
  return _register_atfork(a1, a2, a3, &off_4000);
}
// 784: using guessed type int __fastcall _register_atfork(_DWORD, _DWORD, _DWORD, _DWORD);
// 4000: using guessed type void *off_4000;

//----- (0000093C) --------------------------------------------------------
int __fastcall sub_93C(int a1, int a2, _DWORD *a3)
{
  _DWORD *v5; // r0
  _DWORD *v6; // r5
  __int64 v7; // d16
  __int64 v8; // d17
  int result; // r0

  v5 = malloc(0x5Cu);
  v6 = v5;
  if ( v5 )
  {
    memset(v5, 0, 0x58u);
    LODWORD(v7) = sub_A00;
    HIDWORD(v7) = sub_A04;
    *v6 = 1213678676;
    LODWORD(v8) = sub_A08;
    result = 0;
    v6[1] = 0;
    v6[2] = a1;
    HIDWORD(v8) = &j_j_get_effect_current_level;
    v6[15] = sub_9E4;
    *((_QWORD *)v6 + 9) = v7;
    *((_QWORD *)v6 + 10) = v8;
    v6[22] = sub_9EE;
    v6[16] = &j_j_init_effect;
    v6[17] = &j_j_deinit_effect;
    *a3 = v6;
  }
  else
  {
    _android_log_print(6, "dis_effect", "[ERROR] failed to create dis effect device!\r\n");
    return -12;
  }
  return result;
}
// 7A8: using guessed type int __fastcall _android_log_print(_DWORD, _DWORD, _DWORD);
// 9E4: using guessed type int sub_9E4();
// 9EE: using guessed type int sub_9EE();
// A00: using guessed type int sub_A00();
// A04: using guessed type int sub_A04();
// A08: using guessed type int sub_A08();

//----- (000009E4) --------------------------------------------------------
int __fastcall sub_9E4(void *a1)
{
  free(a1);
  return 0;
}

//----- (000009EE) --------------------------------------------------------
int __fastcall sub_9EE(int a1)
{
  set_effect();
  set_effect_current_level(a1);
  return 0;
}
// 7C0: using guessed type int set_effect(void);
// 7CC: using guessed type int __fastcall set_effect_current_level(_DWORD);

//----- (00000A00) --------------------------------------------------------
int sub_A00()
{
  return 0;
}
// A00: using guessed type int sub_A00();

//----- (00000A04) --------------------------------------------------------
int sub_A04()
{
  return 30;
}
// A04: using guessed type int sub_A04();

//----- (00000A08) --------------------------------------------------------
int sub_A08()
{
  return 15;
}
// A08: using guessed type int sub_A08();

//----- (00000A18) --------------------------------------------------------
unsigned int *__fastcall sub_A18(unsigned int *result, int *a2, int *a3)
{
  unsigned int v3; // r3
  unsigned int v4; // t1
  int v5; // r12
  bool v6; // zf
  int v7; // r3
  int v8; // r12

  v3 = *result;
  if ( (*result & 0x80000000) == 0 )
  {
    *a2 = 1;
    v4 = result[1];
    ++result;
    *a3 = 4 * HIBYTE(v4) + 4;
    return result;
  }
  v5 = HIBYTE(v3) & 0xF;
  if ( v5 )
  {
    v6 = v5 == 3;
    if ( v5 != 3 )
      v6 = v5 == 1;
    if ( !v6 )
      return 0;
    v7 = 4 * BYTE2(v3) + 4;
    v8 = 2;
  }
  else
  {
    v8 = 1;
    v7 = 4;
  }
  *a3 = v7;
  *a2 = v8;
  return result;
}

//----- (00000A6C) --------------------------------------------------------
int __fastcall sub_A6C(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v6; // r11
  unsigned int v8; // r7
  int v9; // r10
  int v10; // r2
  unsigned int v11; // r1
  int result; // r0
  int v13; // r3
  int v14; // r2
  int v15; // r0
  int v16; // r1
  int v17; // r2
  int v18; // r1
  int v19; // r6
  int v20; // r2
  int v21; // r0
  int v22; // r1
  int v23; // r3
  int v24; // r0
  int v25; // r2
  int v26; // r0
  unsigned int v33; // r1
  unsigned int v34; // r0
  int v35; // r1
  unsigned int v36; // r0
  int v37; // [sp+0h] [bp-30h]
  int v38; // [sp+4h] [bp-2Ch] BYREF

  v6 = a3;
  if ( a3 >= a4 )
  {
LABEL_54:
    sub_1360(a1, 14, &v38);
    sub_138E(a1, 15, v38);
    return 8;
  }
  v37 = 0;
  do
  {
    v8 = v6 + 1;
    v9 = *(unsigned __int8 *)(a2 + (v6 ^ 3));
    if ( (v9 & 0x80) == 0 )
    {
      sub_1360(a1, 13, &v38);
      if ( (v9 & 0x40) != 0 )
        v10 = -4 - (unsigned __int8)(4 * v9) + v38;
      else
        v10 = 4 * v9 + v38 + 4;
LABEL_12:
      v38 = v10;
LABEL_13:
      sub_138E(a1, 13, v10);
LABEL_36:
      v6 = v8;
      continue;
    }
    v11 = v9 & 0xF0;
    result = 9;
    if ( v11 > 0xAF )
    {
      if ( v11 == 176 )
      {
        result = 9;
        v18 = 0;
        v19 = 0;
        switch ( *(_BYTE *)(a2 + (v6 ^ 3)) )
        {
          case 0xB0:
            goto LABEL_53;
          case 0xB1:
            if ( v8 >= a4 )
              return 9;
            v20 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
            result = 9;
            if ( !*(_BYTE *)(a2 + (v8 ^ 3)) || (v20 & 0xF0) != 0 )
              return result;
            v21 = a1;
            v22 = 0;
            v23 = 0;
            goto LABEL_48;
          case 0xB2:
            break;
          case 0xB3:
            v23 = 1;
            v26 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
            _R1 = v26 << 12;
            __asm { UXTB16.W        R1, R1 }
            v20 = ((v26 & 0xF) + 1) | _R1;
            v21 = a1;
            v22 = 1;
            goto LABEL_48;
          case 0xB4:
          case 0xB5:
          case 0xB6:
          case 0xB7:
            return result;
          default:
            v16 = 1;
            v13 = 1;
            v14 = ((v9 & 7) + 1) | 0x80000;
            v15 = a1;
            goto LABEL_35;
        }
        while ( v8 < a4 )
        {
          v24 = v8++ ^ 3;
          LOBYTE(v24) = *(_BYTE *)(a2 + v24);
          v25 = (v24 & 0x7F) << v18;
          v18 += 7;
          v19 |= v25;
          if ( (v24 & 0x80) == 0 )
          {
            sub_1360(a1, 13, &v38);
            v10 = v38 + 4 * v19 + 516;
            goto LABEL_12;
          }
        }
        return 9;
      }
      if ( v11 != 192 )
      {
        if ( v11 != 208 )
          return result;
        if ( (v9 & 8) != 0 )
          return 9;
        v16 = 1;
        v14 = ((v9 & 7) + 1) | 0x80000;
        v15 = a1;
LABEL_34:
        v13 = 5;
        goto LABEL_35;
      }
      switch ( *(_BYTE *)(a2 + (v6 ^ 3)) )
      {
        case 0xC0:
        case 0xC1:
        case 0xC2:
        case 0xC3:
        case 0xC4:
        case 0xC5:
          v16 = 3;
          v14 = ((v9 & 7) + 1) | 0xA0000;
          v15 = a1;
          goto LABEL_34;
        case 0xC6:
          v36 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
          if ( (v36 & 0xF) + (v36 >> 4) > 0xF )
            return 9;
          v20 = ((v36 & 0xF) + 1) | (v36 >> 4 << 16);
          v21 = a1;
          v22 = 3;
          break;
        case 0xC7:
          if ( !*(_BYTE *)(a2 + (v8 ^ 3)) || *(unsigned __int8 *)(a2 + (v8 ^ 3)) >= 0x10u )
            return 9;
          goto LABEL_49;
        case 0xC8:
        case 0xC9:
          v33 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
          v34 = v33 >> 4;
          if ( v9 == 200 )
            v34 = (v33 >> 4) | 0x10;
          v35 = v33 & 0xF;
          if ( v34 + v35 > 0x1F )
            return 9;
          v20 = (v35 + 1) | (v34 << 16);
          v21 = a1;
          v22 = 1;
          break;
        default:
          return 9;
      }
      v23 = 5;
LABEL_48:
      sub_E4C(v21, v22, v20, v23);
    }
    else
    {
      if ( v11 != 128 )
      {
        if ( v11 == 144 )
        {
          if ( (v9 & 0xD | 2) == 15 )
            return 9;
          sub_1360(a1, v9 & 0xF, &v38);
          v10 = v38;
          goto LABEL_13;
        }
        if ( v11 != 160 )
          return result;
        v13 = 0;
        v14 = ((16 << ((v9 & 7) + 1)) - 16) | (v9 << 11) & 0x4000;
        v15 = a1;
        v16 = 0;
LABEL_35:
        sub_E4C(v15, v16, v14, v13);
        goto LABEL_36;
      }
      if ( v8 >= a4 )
        return 9;
      v17 = (unsigned __int16)((_WORD)v9 << 12) | (16 * *(unsigned __int8 *)(a2 + (v8 ^ 3)));
      if ( !v17 )
        return 9;
      sub_E4C(a1, 0, v17, 0);
      v37 |= (unsigned __int16)(((_WORD)v9 << 12) & 0x8000) >> 15;
    }
LABEL_49:
    v6 += 2;
  }
  while ( v6 < a4 );
LABEL_53:
  if ( (v37 & 1) == 0 )
    goto LABEL_54;
  return 8;
}

//----- (00000DB0) --------------------------------------------------------
int __fastcall sub_DB0(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int result; // r0
  int v8; // r2
  int v9; // r0
  int v10; // r1
  __int64 v11; // r2
  int v12; // r1

  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = a1;
      v10 = a3;
      goto LABEL_11;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_19;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_1470(a1);
LABEL_19:
      v11 = *(_QWORD *)a5;
      v12 = a3 + 256;
LABEL_20:
      result = sub_1402(a1, v12, v11, SHIDWORD(v11));
LABEL_21:
      if ( result )
        return 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = a3 + 112;
      goto LABEL_20;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = a3 + 192;
      v9 = a1;
LABEL_11:
      result = sub_138E(v9, v10, v8);
      goto LABEL_21;
    default:
      sub_11CC(
        "_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation, void *)",
        837,
        "unsupported register class");
  }
}

//----- (00000E4C) --------------------------------------------------------
int __fastcall sub_E4C(int a1, int a2, unsigned int a3, int a4)
{
  char v8; // r4
  unsigned int i; // r7
  int *v10; // r0
  int v11; // r0
  char v12; // r1
  char v13; // r2
  int result; // r0
  unsigned int v15; // r4
  unsigned int v16; // r6
  int *v17; // r0
  int v18; // r2
  int v19; // r0
  int v20; // r2
  int v21[2]; // [sp+8h] [bp-30h] BYREF
  int *v22; // [sp+10h] [bp-28h] BYREF

  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_1360(a1, 13, v21) )
        return 2;
      v8 = 0;
      for ( i = 0; i < 0x10; ++i )
      {
        if ( ((1 << i) & a3) != 0 )
        {
          v10 = (int *)v21[0];
          v21[0] += 4;
          v22 = (int *)*v10;
          v11 = sub_DB0(a1, a2, i, 0, (int *)&v22);
          v12 = 0;
          v13 = 0;
          if ( i == 13 )
            v12 = 1;
          if ( !a2 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
      }
      if ( (v8 & 1) != 0 )
        return 0;
      v20 = v21[0];
      goto LABEL_26;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_1360(a1, 13, &v22) )
        return 2;
      if ( !(_WORD)a3 )
        goto LABEL_21;
      v15 = HIWORD(a3);
      v16 = HIWORD(a3) + (unsigned __int16)a3;
      break;
    default:
      sub_11CC(
        "_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        971,
        "unsupported register class");
  }
  do
  {
    v17 = v22++;
    v18 = *v17;
    v22 = v17 + 2;
    v19 = v17[1];
    v21[0] = v18;
    v21[1] = v19;
    if ( sub_DB0(a1, a2, v15, a4, v21) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( a4 == 1 )
    v20 = (int)++v22;
  else
    v20 = (int)v22;
LABEL_26:
  result = sub_138E(a1, 13, v20);
  if ( result )
    return 2;
  return result;
}

//----- (00000F88) --------------------------------------------------------
int __fastcall sub_F88(int a1, int a2, int a3)
{
  int result; // r0
  int v6; // r1
  char v7[8]; // [sp+4h] [bp-3Ch] BYREF
  _DWORD *v8; // [sp+Ch] [bp-34h]

  sub_1440(a3, (int)v7);
  if ( (*(_BYTE *)(a2 + 80) & 1) == 0 && *v8 )
    return 9;
  v6 = sub_143A(a3);
  result = 9;
  if ( v6 == 1 )
    return 8;
  return result;
}
// F88: using guessed type char var_3C[8];

//----- (00000FEC) --------------------------------------------------------
void sub_FEC()
{
  JUMPOUT(0xF90);
}
// FF0: control flows out of bounds to F90

//----- (00000FF4) --------------------------------------------------------
void sub_FF4()
{
  JUMPOUT(0xF90);
}
// FF8: control flows out of bounds to F90

//----- (00000FFC) --------------------------------------------------------
int __fastcall sub_FFC(int *a1, int a2, int a3, int a4)
{
  int v5; // r5
  int (__fastcall *v6)(_DWORD, int *, char *); // r3
  int v7; // r0
  int v9[3]; // [sp+0h] [bp-8A0h] BYREF
  int (__fastcall *v10)(_DWORD, int *, char *); // [sp+Ch] [bp-894h]
  int v11; // [sp+14h] [bp-88Ch]
  int v12; // [sp+20h] [bp-880h]
  _DWORD v13[256]; // [sp+28h] [bp-878h] BYREF
  char v14[1120]; // [sp+428h] [bp-478h] BYREF

  sub_1294(v13, a2, a3, a4, v9[0]);
  a1[3] = 0;
  sub_131C((int)v14, v13);
  if ( sub_1440((int)v14, (int)v9) )
    return 3;
  v5 = 3;
  while ( 1 )
  {
    v6 = v10;
    if ( v10 )
    {
      a1[18] = v9[0];
      a1[19] = v12;
      a1[20] = v11;
      v7 = v6(0, a1, v14);
      if ( v7 != 8 )
        break;
    }
    if ( sub_1440((int)v14, (int)v9) )
      return 3;
  }
  if ( v7 == 6 )
  {
    sub_10A8(v13, a1, 0);
    return 2;
  }
  else if ( v7 == 9 )
  {
    return 9;
  }
  return v5;
}
// FFC: using guessed type _DWORD var_878[256];

//----- (000010A8) --------------------------------------------------------
int __fastcall sub_10A8(const void *a1, int *a2, char a3)
{
  int i; // r6
  int v6; // r7
  int (__fastcall *v7)(int, int *, char *); // r3
  int v8; // r0
  int v10; // [sp+0h] [bp-4B8h] BYREF
  int v11[3]; // [sp+4h] [bp-4B4h] BYREF
  int (__fastcall *v12)(int, int *, char *); // [sp+10h] [bp-4A8h]
  int v13; // [sp+18h] [bp-4A0h]
  int v14; // [sp+24h] [bp-494h]
  int v15; // [sp+2Ch] [bp-48Ch] BYREF
  char v16[1124]; // [sp+30h] [bp-488h] BYREF
  int v17; // [sp+494h] [bp-24h]

  sub_131C((int)v16, a1);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( (a3 & 1) != 0 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_138E((int)v16, -1, a2[4]);
        a3 = 0;
      }
    }
    sub_1360((int)v16, -2, &v15);
    if ( sub_1440((int)v16, (int)v11) )
      break;
    v7 = v12;
    if ( v12 )
    {
      a2[18] = v11[0];
      a2[19] = v14;
      a2[20] = v13;
      v8 = v7(v6, a2, v16);
      if ( v8 == 7 )
      {
        sub_1360((int)v16, -1, &v10);
        a2[4] = v10;
        sub_145E((int)v16);
        return _stack_chk_guard - v17;
      }
      if ( v8 != 8 )
      {
        if ( v8 == 9 )
          abort();
        return _stack_chk_guard - v17;
      }
      if ( v15 == a2[8] )
        sub_11CC(
          "_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          653,
          "during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return _stack_chk_guard - v17;
}
// 10A8: using guessed type int var_4B4[3];

//----- (00001198) --------------------------------------------------------
void __fastcall __noreturn sub_1198(int *a1, int a2, int a3, int a4)
{
  int v5[260]; // [sp+0h] [bp-410h] BYREF

  sub_1294(v5, a2, a3, a4, v5[0]);
  sub_10A8(v5, a1, 1);
  sub_11CC("void _Unwind_Resume(_Unwind_Exception *)", 753, "_Unwind_Resume() can't return");
}

//----- (000011CC) --------------------------------------------------------
void __fastcall __noreturn sub_11CC(const char *a1, int a2, const char *a3)
{
  fprintf(stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libunwind_llvm/src/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (000011FC) --------------------------------------------------------
int __fastcall sub_11FC(int a1)
{
  int v1; // r1
  int result; // r0
  char v3[8]; // [sp+4h] [bp-34h] BYREF
  int v4; // [sp+Ch] [bp-2Ch]

  v1 = sub_1440(a1, (int)v3);
  result = v4;
  if ( v1 )
    return 0;
  return result;
}
// 11FC: using guessed type char var_34[8];

//----- (00001238) --------------------------------------------------------
int __fastcall sub_1238(int a1)
{
  int v1; // r1
  int result; // r0
  int v3[10]; // [sp+4h] [bp-34h] BYREF

  v1 = sub_1440(a1, (int)v3);
  result = v3[0];
  if ( v1 )
    return 0;
  return result;
}
// 1238: using guessed type int var_34[10];

//----- (00001280) --------------------------------------------------------
int __fastcall sub_1280(int a1, int a2)
{
  int v2; // r0
  int v3; // r1

  v2 = sub_143A(a2);
  v3 = 9;
  if ( v2 == 1 )
    return 0;
  return v3;
}

//----- (00001294) --------------------------------------------------------
int __fastcall sub_1294(_DWORD *a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r5
  int v7; // r6
  int v8; // r7
  int v9; // r8
  int v10; // r9
  int v11; // r10
  int v12; // r11
  int v13; // r12
  int v14; // lr

  *a1 = a1;
  a1[1] = a2;
  a1[2] = a3;
  a1[3] = a4;
  a1[4] = v5;
  a1[5] = v6;
  a1[6] = v7;
  a1[7] = v8;
  a1[8] = v9;
  a1[9] = v10;
  a1[10] = v11;
  a1[11] = v12;
  a1[12] = v13;
  a1[13] = &a5;
  a1[14] = v14;
  a1[15] = v14;
  return 0;
}
// 1294: variable 'v5' is possibly undefined
// 1294: variable 'v6' is possibly undefined
// 1294: variable 'v7' is possibly undefined
// 1294: variable 'v8' is possibly undefined
// 1294: variable 'v9' is possibly undefined
// 1294: variable 'v10' is possibly undefined
// 1294: variable 'v11' is possibly undefined
// 1294: variable 'v12' is possibly undefined
// 1294: variable 'v13' is possibly undefined
// 129C: variable 'v14' is possibly undefined

//----- (000012AC) --------------------------------------------------------
_QWORD *__fastcall sub_12AC(_QWORD *result)
{
  __int64 v1; // d0
  __int64 v2; // d1
  __int64 v3; // d2
  __int64 v4; // d3
  __int64 v5; // d4
  __int64 v6; // d5
  __int64 v7; // d6
  __int64 v8; // d7
  __int64 v9; // d8
  __int64 v10; // d9
  __int64 v11; // d10
  __int64 v12; // d11
  __int64 v13; // d12
  __int64 v14; // d13
  __int64 v15; // d14
  __int64 v16; // d15

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 12AC: variable 'v1' is possibly undefined
// 12AC: variable 'v2' is possibly undefined
// 12AC: variable 'v3' is possibly undefined
// 12AC: variable 'v4' is possibly undefined
// 12AC: variable 'v5' is possibly undefined
// 12AC: variable 'v6' is possibly undefined
// 12AC: variable 'v7' is possibly undefined
// 12AC: variable 'v8' is possibly undefined
// 12AC: variable 'v9' is possibly undefined
// 12AC: variable 'v10' is possibly undefined
// 12AC: variable 'v11' is possibly undefined
// 12AC: variable 'v12' is possibly undefined
// 12AC: variable 'v13' is possibly undefined
// 12AC: variable 'v14' is possibly undefined
// 12AC: variable 'v15' is possibly undefined
// 12AC: variable 'v16' is possibly undefined

//----- (000012B4) --------------------------------------------------------
_QWORD *__fastcall sub_12B4(_QWORD *result)
{
  __int64 v1; // d0
  __int64 v2; // d1
  __int64 v3; // d2
  __int64 v4; // d3
  __int64 v5; // d4
  __int64 v6; // d5
  __int64 v7; // d6
  __int64 v8; // d7
  __int64 v9; // d8
  __int64 v10; // d9
  __int64 v11; // d10
  __int64 v12; // d11
  __int64 v13; // d12
  __int64 v14; // d13
  __int64 v15; // d14
  __int64 v16; // d15

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 12B4: variable 'v1' is possibly undefined
// 12B4: variable 'v2' is possibly undefined
// 12B4: variable 'v3' is possibly undefined
// 12B4: variable 'v4' is possibly undefined
// 12B4: variable 'v5' is possibly undefined
// 12B4: variable 'v6' is possibly undefined
// 12B4: variable 'v7' is possibly undefined
// 12B4: variable 'v8' is possibly undefined
// 12B4: variable 'v9' is possibly undefined
// 12B4: variable 'v10' is possibly undefined
// 12B4: variable 'v11' is possibly undefined
// 12B4: variable 'v12' is possibly undefined
// 12B4: variable 'v13' is possibly undefined
// 12B4: variable 'v14' is possibly undefined
// 12B4: variable 'v15' is possibly undefined
// 12B4: variable 'v16' is possibly undefined

//----- (000012BC) --------------------------------------------------------
_QWORD *__fastcall sub_12BC(_QWORD *result)
{
  __int64 v1; // d16
  __int64 v2; // d17
  __int64 v3; // d18
  __int64 v4; // d19
  __int64 v5; // d20
  __int64 v6; // d21
  __int64 v7; // d22
  __int64 v8; // d23
  __int64 v9; // d24
  __int64 v10; // d25
  __int64 v11; // d26
  __int64 v12; // d27
  __int64 v13; // d28
  __int64 v14; // d29
  __int64 v15; // d30
  __int64 v16; // d31

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 12BC: variable 'v1' is possibly undefined
// 12BC: variable 'v2' is possibly undefined
// 12BC: variable 'v3' is possibly undefined
// 12BC: variable 'v4' is possibly undefined
// 12BC: variable 'v5' is possibly undefined
// 12BC: variable 'v6' is possibly undefined
// 12BC: variable 'v7' is possibly undefined
// 12BC: variable 'v8' is possibly undefined
// 12BC: variable 'v9' is possibly undefined
// 12BC: variable 'v10' is possibly undefined
// 12BC: variable 'v11' is possibly undefined
// 12BC: variable 'v12' is possibly undefined
// 12BC: variable 'v13' is possibly undefined
// 12BC: variable 'v14' is possibly undefined
// 12BC: variable 'v15' is possibly undefined
// 12BC: variable 'v16' is possibly undefined

//----- (000012C4) --------------------------------------------------------
void sub_12C4()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (00001308) --------------------------------------------------------
void sub_1308()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (0000131C) --------------------------------------------------------
int __fastcall sub_131C(int a1, const void *a2)
{
  *(_DWORD *)a1 = &off_3E38;
  *(_DWORD *)(a1 + 4) = &unk_4088;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  qmemcpy((void *)(a1 + 8), a2, 0x40u);
  memset((void *)(a1 + 80), 0, 0x1C2u);
  sub_1838((int *)a1, 0);
  return 0;
}
// 3E38: using guessed type void *;

//----- (00001360) --------------------------------------------------------
int __fastcall sub_1360(int a1, int a2, _DWORD *a3)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 8))(a1) != 1 )
    return -6542;
  *a3 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 12))(a1, a2);
  return 0;
}

//----- (0000138E) --------------------------------------------------------
int __fastcall sub_138E(int a1, int a2, int a3)
{
  int v6; // r5

  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 8))(a1) != 1 )
    return -6542;
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 16))(a1, a2, a3);
  if ( a2 != -1 )
    return 0;
  v6 = 0;
  (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)a1 + 52))(a1, 0);
  return v6;
}

//----- (000013D2) --------------------------------------------------------
int __fastcall sub_13D2(int a1, int a2, _QWORD *a3)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 20))(a1) != 1 )
    return -6542;
  *a3 = ((__int64 (__fastcall *)(int, int))*(_DWORD *)(*(_DWORD *)a1 + 24))(a1, a2);
  return 0;
}

//----- (00001402) --------------------------------------------------------
int __fastcall sub_1402(int a1, int a2, int a3, int a4)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 20))(a1) != 1 )
    return -6542;
  (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 28))(a1, a2, a3, a4);
  return 0;
}

//----- (0000143A) --------------------------------------------------------
int __fastcall sub_143A(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 32))(a1);
}

//----- (00001440) --------------------------------------------------------
int __fastcall sub_1440(int a1, int a2)
{
  int result; // r0

  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 36))(a1, a2);
  result = 0;
  if ( !*(_DWORD *)(a2 + 4) )
    return -6549;
  return result;
}

//----- (0000145E) --------------------------------------------------------
int __fastcall sub_145E(int a1)
{
  (*(void (__fastcall **)(int))(*(_DWORD *)a1 + 40))(a1);
  return -6540;
}

//----- (00001470) --------------------------------------------------------
int __fastcall sub_1470(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 60))(a1);
}

//----- (00001476) --------------------------------------------------------
int __fastcall sub_1476(int a1, int a2)
{
  int v2; // r2
  bool v3; // zf
  int v4; // r0
  unsigned int v5; // r1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (00001498) --------------------------------------------------------
int __fastcall sub_1498(int a1, int a2)
{
  int v4; // r0

  if ( a2 > 12 )
  {
    if ( a2 != 15 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 13 )
        goto LABEL_11;
LABEL_9:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    goto LABEL_8;
  }
  if ( a2 == -2 )
    goto LABEL_9;
  if ( a2 == -1 )
  {
LABEL_8:
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
LABEL_11:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_18B8(
        "uint32_t libunwind::Registers_arm::getRegister(int)",
        "external/libunwind_llvm/src/Registers.hpp",
        1452,
        "unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_1308();
    }
    v4 = a1 + 4 * a2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (00001524) --------------------------------------------------------
int __fastcall sub_1524(int result, int a2, int a3)
{
  int v5; // r5

  v5 = result;
  if ( a2 <= 12 )
  {
    if ( a2 == -2 )
      goto LABEL_9;
    if ( a2 != -1 )
      goto LABEL_11;
LABEL_8:
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  switch ( a2 )
  {
    case 15:
      goto LABEL_8;
    case 14:
      *(_DWORD *)(result + 64) = a3;
      return result;
    case 13:
LABEL_9:
      *(_DWORD *)(result + 60) = a3;
      return result;
  }
LABEL_11:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_18B8(
        "void libunwind::Registers_arm::setRegister(int, uint32_t)",
        "external/libunwind_llvm/src/Registers.hpp",
        1471,
        "unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_1308();
    }
    result = v5 + 4 * a2;
    *(_DWORD *)(result - 296) = a3;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (000015B0) --------------------------------------------------------
int __fastcall sub_15B0(int a1, int a2)
{
  int v2; // r2
  bool v3; // zf
  int v4; // r0
  unsigned int v5; // r1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (000015D4) --------------------------------------------------------
__int64 __fastcall sub_15D4(int a1, int a2)
{
  unsigned int v4; // r0
  _QWORD *v5; // r0
  int v6; // r0

  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(a1 + 75) )
    {
      *(_BYTE *)(a1 + 75) = 1;
      sub_12C4();
    }
    v6 = a1 + 8 * a2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(a1 + 74) )
    {
      *(_BYTE *)(a1 + 74) = 1;
      sub_12BC((_QWORD *)(a1 + 216));
    }
    v6 = a1 + 8 * a2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_18B8(
        "unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        "external/libunwind_llvm/src/Registers.hpp",
        1673,
        "Unknown ARM float register");
    if ( !*(_BYTE *)(a1 + 73) )
    {
      *(_BYTE *)(a1 + 73) = 1;
      v5 = (_QWORD *)(a1 + 80);
      if ( *(_BYTE *)(a1 + 72) )
        sub_12B4(v5);
      else
        sub_12AC(v5);
    }
    v6 = a1 + 8 * a2 - 1968;
  }
  return *(_QWORD *)v6;
}

//----- (00001678) --------------------------------------------------------
int __fastcall sub_1678(int a1, int a2, int a3, int a4)
{
  unsigned int v6; // r0
  _QWORD *v9; // r0
  int result; // r0
  int v11; // r1

  v6 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(a1 + 75) )
    {
      *(_BYTE *)(a1 + 75) = 1;
      sub_12C4();
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 548) = a4;
    LOWORD(v11) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(a1 + 74) )
    {
      *(_BYTE *)(a1 + 74) = 1;
      sub_12BC((_QWORD *)(a1 + 216));
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 1956) = a4;
    LOWORD(v11) = -1960;
  }
  else
  {
    if ( v6 != 256 )
      sub_18B8(
        "void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        "external/libunwind_llvm/src/Registers.hpp",
        1700,
        "Unknown ARM float register");
    if ( !*(_BYTE *)(a1 + 73) )
    {
      *(_BYTE *)(a1 + 73) = 1;
      v9 = (_QWORD *)(a1 + 80);
      if ( *(_BYTE *)(a1 + 72) )
        sub_12B4(v9);
      else
        sub_12AC(v9);
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 1964) = a4;
    LOWORD(v11) = -1968;
  }
  HIWORD(v11) = -1;
  *(_DWORD *)(result + v11) = a3;
  return result;
}

//----- (00001744) --------------------------------------------------------
int __fastcall sub_1744(_DWORD *a1)
{
  int result; // r0
  __int64 v3; // kr00_8
  int v4; // r0

  if ( *((_BYTE *)a1 + 528) )
    return 0;
  result = sub_18E4((int)a1);
  if ( result != 1 )
    return result;
  (*(void (__fastcall **)(_DWORD *, int))(*a1 + 52))(a1, 1);
  if ( *((_BYTE *)a1 + 528) )
    return 0;
  if ( a1[126] )
  {
    v3 = *(_QWORD *)(*a1 + 12);
    v4 = ((int (__fastcall *)(_DWORD *, int))v3)(a1, -2);
    ((void (__fastcall *)(_DWORD *, int, int))HIDWORD(v3))(a1, -2, a1[126] + v4);
  }
  return 1;
}

//----- (00001794) --------------------------------------------------------
_DWORD *__fastcall sub_1794(int a1, _DWORD *a2)
{
  int *v2; // r0
  _DWORD *result; // r0
  int v4; // r2
  int v5; // r3
  int v6; // r4
  int v7; // r12
  int v8; // lr
  _DWORD *v9; // r1
  int v10; // r3
  int v11; // r4
  int v12; // r12
  int v13; // lr

  v2 = (int *)(a1 + 488);
  v4 = *v2;
  v5 = v2[1];
  v6 = v2[2];
  v7 = v2[3];
  v8 = v2[4];
  result = v2 + 5;
  *a2 = v4;
  a2[1] = v5;
  a2[2] = v6;
  a2[3] = v7;
  a2[4] = v8;
  v9 = a2 + 5;
  v10 = result[1];
  v11 = result[2];
  v12 = result[3];
  v13 = result[4];
  *v9 = *result;
  v9[1] = v10;
  v9[2] = v11;
  v9[3] = v12;
  v9[4] = v13;
  return result;
}

//----- (000017AC) --------------------------------------------------------
int __fastcall sub_17AC(int a1)
{
  int v1; // r4

  v1 = a1 + 8;
  sub_1938(a1 + 8);
  return sub_2078(v1);
}

//----- (000017C2) --------------------------------------------------------
int __fastcall sub_17C2(int a1)
{
  return *(unsigned __int8 *)(a1 + 529);
}

//----- (000017C8) --------------------------------------------------------
int __fastcall sub_17C8(int a1, int a2, int a3, _DWORD *a4)
{
  int v7; // r7
  char v9[8]; // [sp+8h] [bp-28h] BYREF
  const char *v10; // [sp+10h] [bp-20h]
  int v11; // [sp+14h] [bp-1Ch]

  v7 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 12))(a1, -1);
  if ( !dladdr(v7, v9) || !v10 )
    return 0;
  _snprintf_chk(a2, a3, 0, -1, "%s", v10);
  *a4 = v7 - v11;
  return 1;
}
// 838: using guessed type int __fastcall dladdr(_DWORD, _DWORD);
// 844: using guessed type int _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, const char *, ...);
// 17C8: using guessed type char var_28[8];

//----- (00001838) --------------------------------------------------------
int __fastcall sub_1838(int *a1, int a2)
{
  int v4; // r5
  int v6[2]; // [sp+0h] [bp-20h] BYREF
  int v7[6]; // [sp+8h] [bp-18h] BYREF

  v4 = (*(int (__fastcall **)(int *, int))(*a1 + 12))(a1, -1) & 0xFFFFFFFE;
  v7[0] = 0;
  if ( a2 )
    --v4;
  v6[0] = _gnu_Unwind_Find_exidx(v4, v7);
  v6[1] = v7[0];
  if ( !v6[0] || !v7[0] || !sub_1990(a1, v4, v6) )
    *((_BYTE *)a1 + 528) = 1;
  return _stack_chk_guard - v7[1];
}
// 850: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);

//----- (000018AE) --------------------------------------------------------
int __fastcall sub_18AE(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (000018B8) --------------------------------------------------------
void __fastcall __noreturn sub_18B8(const char *a1, const char *a2, int a3, const char *a4)
{
  fprintf(stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (000018E4) --------------------------------------------------------
int __fastcall sub_18E4(int a1)
{
  int v2; // r4
  unsigned int *v3; // r0
  unsigned int v5; // [sp+4h] [bp-1Ch] BYREF
  unsigned int v6; // [sp+8h] [bp-18h] BYREF

  v2 = 0;
  v5 = 0;
  v6 = 0;
  v3 = sub_A18(*(unsigned int **)(a1 + 520), (int *)&v5, (int *)&v6);
  if ( sub_A6C(a1, (int)v3, v5, v6) == 8 )
    return 1;
  return v2;
}

//----- (00001938) --------------------------------------------------------
_DWORD *__fastcall sub_1938(int a1)
{
  int v2; // r0
  _DWORD *result; // r0

  if ( *(_BYTE *)(a1 + 65) )
  {
    if ( *(_BYTE *)(a1 + 64) )
      sub_1FE0();
    else
      sub_1FD8();
  }
  if ( (unsigned __int8)*(_WORD *)(a1 + 66) )
  {
    sub_1FE8();
    v2 = *(unsigned __int8 *)(a1 + 67);
  }
  else
  {
    v2 = HIBYTE(*(unsigned __int16 *)(a1 + 66));
  }
  if ( v2 )
    sub_1FF0((int *)(a1 + 336));
  result = (_DWORD *)*(unsigned __int8 *)(a1 + 68);
  if ( *(_BYTE *)(a1 + 68) )
    return sub_2088((int *)(a1 + 464));
  return result;
}

//----- (00001990) --------------------------------------------------------
int __fastcall sub_1990(int *a1, int a2, _DWORD *a3)
{
  int v4; // r5
  int v5; // r6
  char *v6; // r1
  int *v7; // r0
  int v8; // r5
  int v9; // r7
  unsigned int v10; // r6
  int v11; // r12
  char *v12; // lr
  int v13; // r9
  int v14; // r6
  int v15; // r6
  int v16; // r3
  int v17; // r7
  int v19[3]; // [sp+14h] [bp-34h] BYREF
  int v20; // [sp+20h] [bp-28h] BYREF

  v4 = 0;
  v20 = a2;
  v5 = a3[1];
  sub_1B34(v19, 0, a1[1], a3, v5, a1[1], (int)a3, &v20);
  if ( !v19[0] || v19[0] == v5 )
    return v4;
  v6 = (char *)(*(_DWORD *)v19[2] + 8 * v19[0]);
  v7 = (int *)(v6 - 4);
  v8 = *(_DWORD *)v6;
  if ( v6 == &byte_4 )
    return 0;
  v9 = *v7;
  if ( *v7 == 1 )
    return 0;
  if ( v9 < 0 )
  {
    v11 = 1;
    goto LABEL_11;
  }
  v10 = (2 * v9) & 0x80000000 | v9;
  v9 = *(int *)((char *)v7 + v10);
  v7 = (int *)((char *)v7 + v10);
  if ( v9 <= -1 )
  {
    v11 = 0;
LABEL_11:
    v14 = HIBYTE(v9) & 0xF;
    if ( v14 == 2 )
    {
      v12 = (char *)sub_FF4;
      v15 = 1;
    }
    else
    {
      if ( v14 != 1 )
      {
        if ( v14 )
          sub_18B8(
            "bool libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::getInfoFromEHABISectio"
            "n(pint_t, const libunwind::UnwindInfoSections &) [A = libunwind::LocalAddressSpace, R = libunwind::Registers_arm]",
            "external/libunwind_llvm/src/UnwindCursor.hpp",
            776,
            "unknown personality routine");
        v13 = (int)(v7 + 1);
        if ( v11 )
          v13 = 0;
        v12 = (char *)sub_F88;
        goto LABEL_17;
      }
      v12 = (char *)sub_FEC;
      v15 = 0;
    }
    v16 = BYTE2(v9);
    v17 = v16;
    if ( v16 )
      v17 = 1;
    if ( (v17 & v11) == 1 )
      sub_18B8(
        "bool libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::getInfoFromEHABISection(pi"
        "nt_t, const libunwind::UnwindInfoSections &) [A = libunwind::LocalAddressSpace, R = libunwind::Registers_arm]",
        "external/libunwind_llvm/src/UnwindCursor.hpp",
        783,
        "index inlined table detected but pr function requires extra words");
    v13 = (int)&v7[v16 + 1];
    goto LABEL_24;
  }
  v11 = 0;
  v12 = (char *)v7 + (v9 | (2 * v9) & 0x80000000);
  v13 = (int)&v7[HIBYTE(v7[1]) + 2];
LABEL_17:
  v15 = 0;
LABEL_24:
  a1[122] = (int)&v6[((2 * *((_DWORD *)v6 - 2)) & 0x80000000 | *((_DWORD *)v6 - 2)) - 8];
  a1[123] = (int)&v6[v8 | (2 * v8) & 0x80000000];
  v4 = 1;
  a1[130] = (int)v7;
  a1[124] = v13;
  a1[125] = (int)v12;
  if ( v15 )
    v15 = 2;
  if ( v11 )
    v15 = 1;
  a1[127] = v15;
  return v4;
}
// 4: using guessed type char;

//----- (00001B34) --------------------------------------------------------
_DWORD *__fastcall sub_1B34(_DWORD *a1, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4
  unsigned int v9; // r5
  int v10; // r6

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + ((2 * *(_DWORD *)(*a4 + 8 * v10)) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *a1 = a2;
  a1[1] = a3;
  a1[2] = a4;
  return a1 + 3;
}

//----- (00001FC4) --------------------------------------------------------
int __fastcall sub_1FC4(int a1)
{
  return (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD))(a1 + 60))(
           *(_DWORD *)a1,
           *(_DWORD *)(a1 + 4),
           *(_DWORD *)(a1 + 8),
           *(_DWORD *)(a1 + 12));
}

//----- (00001FD8) --------------------------------------------------------
void sub_1FD8()
{
  ;
}

//----- (00001FE0) --------------------------------------------------------
void sub_1FE0()
{
  ;
}

//----- (00001FE8) --------------------------------------------------------
void sub_1FE8()
{
  ;
}

//----- (00001FF0) --------------------------------------------------------
_DWORD *__fastcall sub_1FF0(int *a1)
{
  int *v5; // r0
  _DWORD *result; // r0

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = v5 + 2;
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (00002034) --------------------------------------------------------
_DWORD *__fastcall sub_2034(int *a1)
{
  int *v5; // r0
  _DWORD *result; // r0

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5++;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5++;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = v5 + 1;
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (00002048) --------------------------------------------------------
// attributes: thunk
int j_get_effect_current_level()
{
  return get_effect_current_level();
}
// 7D8: using guessed type int get_effect_current_level(void);

//----- (00002058) --------------------------------------------------------
// attributes: thunk
int j_init_effect()
{
  return init_effect();
}
// 7E4: using guessed type int init_effect(void);

//----- (00002068) --------------------------------------------------------
// attributes: thunk
int j_deinit_effect()
{
  return deinit_effect();
}
// 7F0: using guessed type int deinit_effect(void);

//----- (00002078) --------------------------------------------------------
// attributes: thunk
int __fastcall sub_2078(int a1)
{
  return sub_1FC4(a1);
}

//----- (00002088) --------------------------------------------------------
// attributes: thunk
_DWORD *__fastcall sub_2088(int *a1)
{
  return sub_2034(a1);
}

// nfuncs=113 queued=69 decompiled=69 lumina nreq=0 worse=0 better=0
// ALL OK, 69 function(s) have been successfully decompiled
