/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void sub_18E8();
// int __fastcall _cxa_finalize(void *);
// int __fastcall _cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle);
// int __fastcall _register_atfork(_DWORD, _DWORD, _DWORD, _DWORD); weak
int __fastcall j_RilAimsOpen(int);
// int _android_log_print(_DWORD, _DWORD, const char *, ...); weak
// void *dlopen(const char *file, int mode);
// void *dlsym(void *handle, const char *name);
int __fastcall j_RilAimsClose(int);
// int dlclose(void *handle);
int __fastcall j_RequestAimsForChannelId(unsigned int, int, const void *, int, const void *, unsigned int);
// void __fastcall operator delete(void *); idb
void *__fastcall ProductFeature::GetInstance(ProductFeature *this);
// int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...); weak
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
int __fastcall ProductFeature::Function_GetFastDormancyInfo(ProductFeature *this, unsigned __int8 *a2, unsigned __int8 *a3, unsigned __int8 *a4, unsigned __int8 *a5);
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this);
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this);
void __fastcall ProductFeature::ProductFeature(ProductFeature *this);
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2);
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this);
// void abort(void);
// int fprintf(FILE *stream, const char *format, ...);
// void __fastcall _aeabi_memcpy(void *, const void *, size_t); idb
// void __fastcall _aeabi_memclr8(void *, size_t); idb
// int __fastcall dladdr(_DWORD, _DWORD); weak
// int _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, const char *, ...); weak
// int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD); weak
int sub_1ABC();
int (*__fastcall sub_1ADC(int (*result)(void)))(void);
int __fastcall sub_1B08(void *a1);
int __fastcall sub_1B54(int a1, int a2, int a3);
int __fastcall RilAimsOpen(int a1);
int __fastcall sub_1FF0(int a1, unsigned __int8 *a2, int a3, int a4);
int __fastcall Close(int a1);
int __fastcall RilAimsClose(int a1);
int __fastcall RilAimsRegisterCallback(int a1, const void *a2);
int __fastcall SetImsConfiguration(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall GetImsConfiguration(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall GetSimAuth(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall SetEmergencyCallStatus(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall SetSrvccCallList(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall GetGBAAuth(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsForChannelId(unsigned int a1, int a2, const void *a3, int a4, const void *a5, unsigned int a6);
int __fastcall RequestAimsDial(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsAnswer(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall ReqeustAimsHangup(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsDegregistration(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsHiddenMenu(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsPdnInfo(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsCallManage(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSendDtmf(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSetFrameTime(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsGetFrameTime(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsCallModify(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsResponseCallModify(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsTimeInfo(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsConfCallAddRemoveUser(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsEnhancedConfCall(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsGetCallForwardStatus(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSetCallForwardStatus(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsGetCallWaiting(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSetCallWaiting(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsGetCallBarring(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSetCallBarring(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSendSms(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSendSmsExpectMore(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSendSmsAck(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsAckIncomingGsmSms(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsChangeBarringPassword(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSendUssdInfo(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsGetPresentationSettings(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSetPresentationSettings(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsSetSelfCapability(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsHoToWifiReady(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsHoToWifiCancel(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsHoPayloadInd(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsHoTo3gpp(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsAckIncomingCdmaSms(unsigned int a1, const void *a2, int a3, const void *a4);
int __fastcall RequestAimsMediaStateInd(unsigned int a1, const void *a2, int a3, const void *a4);
void __fastcall ProductFeature::ProductFeature(ProductFeature *this);
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
void __fastcall ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
int __fastcall ProductFeature::Init(ProductFeature *this, const char *a2);
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this);
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this);
int __fastcall ProductFeature::Function_SendDebugTraceOffAtBootup(ProductFeature *this);
int __fastcall ProductFeature::Function_GetFastDormancyInfo(ProductFeature *this, unsigned __int8 *a2, unsigned __int8 *a3, unsigned __int8 *a4, unsigned __int8 *a5);
int __fastcall ProductFeature::Function_RilResetByCrashExitInUserMode(ProductFeature *this);
int __fastcall ProductFeature::Function_DeviceBasedCwInCs(ProductFeature *this);
const char *sub_2DAC();
const char *sub_2DB8();
void *__fastcall ProductFeature::GetInstance(ProductFeature *this);
void __fastcall CustomProductFeature::CustomProductFeature(CustomProductFeature *this);
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *__hidden this); // idb
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2);
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this);
int __fastcall CustomProductFeature::Custom_SaveImeiToProperty(CustomProductFeature *this);
int __fastcall CustomProductFeature::Custom_ReturnCurrentPlmn(CustomProductFeature *this);
int __fastcall CustomProductFeature::ModuleAudio_VolumeStartFrom1(CustomProductFeature *this);
const char *sub_2ED0();
const char *sub_2EDC();
unsigned int *__fastcall sub_2EE8(unsigned int *result, int *a2, int *a3);
int __fastcall sub_2F3C(int a1, int a2, unsigned int a3, unsigned int a4);
int __fastcall sub_3280(int a1, int a2, unsigned int a3, int a4, int *a5);
int __fastcall sub_331C(int a1, int a2, unsigned int a3, int a4);
int __fastcall sub_34CC(int *a1, int a2, int a3, int a4);
int __fastcall sub_3578(const void *a1, int *a2, char a3);
void __fastcall __noreturn sub_3664(int *a1, int a2, int a3, int a4);
void __fastcall __noreturn sub_3698(const char *a1, int a2, const char *a3);
int __fastcall sub_36C8(int a1);
int __fastcall sub_3704(int a1);
int __fastcall sub_374C(int a1, int a2);
int __fastcall sub_3760(_DWORD *a1, int a2, int a3, int a4, int a5);
_QWORD *__fastcall sub_3778(_QWORD *result);
_QWORD *__fastcall sub_3780(_QWORD *result);
_QWORD *__fastcall sub_3788(_QWORD *result);
void sub_3790();
void sub_37D4();
int __fastcall sub_37E8(int a1, const void *a2);
int __fastcall sub_382C(int a1, int a2, _DWORD *a3);
int __fastcall sub_385A(int a1, int a2, int a3);
int __fastcall sub_389E(int a1, int a2, _QWORD *a3);
int __fastcall sub_38CE(int a1, int a2, int a3, int a4);
int __fastcall sub_3906(int a1);
int __fastcall sub_390C(int a1, int a2);
int __fastcall sub_392A(int a1);
int __fastcall sub_393C(int a1);
int __fastcall sub_3942(int a1, int a2);
int __fastcall sub_3964(int a1, int a2);
int __fastcall sub_39F0(int result, int a2, int a3);
int __fastcall sub_3A7C(int a1, int a2);
__int64 __fastcall sub_3AA0(int a1, int a2);
int __fastcall sub_3B44(int a1, int a2, int a3, int a4);
int __fastcall sub_3C10(_DWORD *a1);
_DWORD *__fastcall sub_3C60(int a1, _DWORD *a2);
int __fastcall sub_3C78(int a1);
int __fastcall sub_3C8E(int a1);
int __fastcall sub_3C94(int a1, int a2, int a3, _DWORD *a4);
int __fastcall sub_3D04(int *a1, int a2);
int __fastcall sub_3D7A(int result);
void __fastcall __noreturn sub_3D84(const char *a1, const char *a2, int a3, const char *a4);
int __fastcall sub_3DB0(int a1);
_DWORD *__fastcall sub_3E04(int a1);
int __fastcall sub_3E5C(int *a1, int a2, _DWORD *a3);
_DWORD *__fastcall sub_4000(_DWORD *a1, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8);
int __fastcall sub_4490(int a1);
void sub_44A4();
void sub_44AC();
void sub_44B4();
_DWORD *__fastcall sub_44BC(int *a1);
_DWORD *__fastcall sub_4500(int *a1);
int __fastcall j_j_RilAimsOpen(int a1);
void __fastcall operator delete(void *); // idb
void __fastcall j_ProductFeature::~ProductFeature(ProductFeature *__hidden this); // idb
int __fastcall j___cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle);
int __fastcall sub_4554(int a1);
_DWORD *__fastcall sub_4564(int *a1);

//-------------------------------------------------------------------------
// Data declarations

char byte_4 = '\x01'; // weak
char byte_3459[3] = { 'F', '\x11', 'F' }; // weak
char byte_34BD[3] = { 'F', '\x11', 'F' }; // weak
char byte_34C5[3] = { 'F', '\x11', 'F' }; // weak
void *off_6D5C = (void *)0x2C55; // weak
void *off_6D88 = (void *)0x2DE9; // weak
void *off_6DB4 = (void *)0x2C55; // weak
void *off_7000 = &off_7000; // weak
_DWORD gdlHandle[3]; // weak
_DWORD gSITRILC_Handle[3]; // weak
_DWORD gSITRILC_Open[3]; // weak
_DWORD gSITRILC_Close[3]; // weak
_DWORD gSITRILC_Reconnect[3]; // weak
_DWORD gSITRILC_RegisterUnsolicitedHandler[3]; // weak
_DWORD gSITRILC_Send[3]; // weak
_DWORD dword_7058[3]; // weak
_UNKNOWN instance; // weak
_UNKNOWN unk_7068; // weak
// extern _UNKNOWN _stack_chk_guard; weak
// extern struct _IO_FILE *stderr;


//----- (000018E8) --------------------------------------------------------
void sub_18E8()
{
  JUMPOUT(0);
}
// 18F4: control flows out of bounds to 0

//----- (00001920) --------------------------------------------------------
// attributes: thunk
int __fastcall j_RilAimsOpen(int a1)
{
  return RilAimsOpen(a1);
}

//----- (00001950) --------------------------------------------------------
// attributes: thunk
int __fastcall j_RilAimsClose(int a1)
{
  return RilAimsClose(a1);
}

//----- (00001968) --------------------------------------------------------
// attributes: thunk
int __fastcall j_RequestAimsForChannelId(
        unsigned int a1,
        int a2,
        const void *a3,
        int a4,
        const void *a5,
        unsigned int a6)
{
  return RequestAimsForChannelId(a1, a2, a3, a4, a5, a6);
}

//----- (00001980) --------------------------------------------------------
// attributes: thunk
void *__fastcall ProductFeature::GetInstance(ProductFeature *this)
{
  return _ZN14ProductFeature11GetInstanceEv(this);
}

//----- (00001998) --------------------------------------------------------
// attributes: thunk
void __fastcall ProductFeature::~ProductFeature(ProductFeature *this)
{
  _ZN14ProductFeatureD2Ev(this);
}

//----- (000019A4) --------------------------------------------------------
// attributes: thunk
void __fastcall ProductFeature::~ProductFeature(ProductFeature *this)
{
  _ZN14ProductFeatureD0Ev(this);
}

//----- (000019BC) --------------------------------------------------------
// attributes: thunk
int __fastcall ProductFeature::Function_GetFastDormancyInfo(
        ProductFeature *this,
        unsigned __int8 *a2,
        unsigned __int8 *a3,
        unsigned __int8 *a4,
        unsigned __int8 *a5)
{
  return _ZN14ProductFeature28Function_GetFastDormancyInfoERhS0_S0_S0_(this, a2, a3, a4, a5);
}

//----- (000019C8) --------------------------------------------------------
// attributes: thunk
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this)
{
  return _ZN14ProductFeature23Custom_SupportOnly5ModeEv(this);
}

//----- (000019D4) --------------------------------------------------------
// attributes: thunk
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this)
{
  return _ZN14ProductFeature43Custom_SupportOnlyBasicPreferredNetworkTypeEv(this);
}

//----- (000019E0) --------------------------------------------------------
// attributes: thunk
void __fastcall ProductFeature::ProductFeature(ProductFeature *this)
{
  _ZN14ProductFeatureC2Ev(this);
}

//----- (000019EC) --------------------------------------------------------
// attributes: thunk
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *this)
{
  _ZN20CustomProductFeatureD2Ev(this);
}

//----- (000019F8) --------------------------------------------------------
// attributes: thunk
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *this)
{
  _ZN20CustomProductFeatureD0Ev(this);
}

//----- (00001A04) --------------------------------------------------------
// attributes: thunk
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2)
{
  return _ZN20CustomProductFeature10CustomInitEPKc(this, a2);
}

//----- (00001A10) --------------------------------------------------------
// attributes: thunk
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this)
{
  return _ZN20CustomProductFeature14GetProductNameEv(this);
}

//----- (00001ABC) --------------------------------------------------------
int sub_1ABC()
{
  return _cxa_finalize(&off_7000);
}
// 7000: using guessed type void *off_7000;

//----- (00001ADC) --------------------------------------------------------
int (*__fastcall sub_1ADC(int (*result)(void)))(void)
{
  if ( result )
    return (int (*)(void))result();
  return result;
}

//----- (00001B08) --------------------------------------------------------
int __fastcall sub_1B08(void *a1)
{
  return _cxa_atexit((void (__fastcall *)(void *))sub_1ADC, a1, &off_7000);
}
// 7000: using guessed type void *off_7000;

//----- (00001B54) --------------------------------------------------------
int __fastcall sub_1B54(int a1, int a2, int a3)
{
  return _register_atfork(a1, a2, a3, &off_7000);
}
// 1914: using guessed type int __fastcall _register_atfork(_DWORD, _DWORD, _DWORD, _DWORD);
// 7000: using guessed type void *off_7000;

//----- (00001BA0) --------------------------------------------------------
int __fastcall RilAimsOpen(int a1)
{
  const char *v2; // r2
  int v3; // r0
  int v4; // r5
  void *v5; // r0
  void *v6; // r0
  void *v7; // r0
  void *v8; // r0
  void *v9; // r0
  void *v10; // r0
  int v11; // r0
  int i; // r0
  const char *v14; // [sp+0h] [bp-20h]

  _android_log_print(4, "RIL-AIMS", "%s() [<-- ", "RilAimsOpen");
  if ( !gdlHandle[a1] )
  {
    v5 = dlopen("libsitril-client.so", 0);
    gdlHandle[a1] = v5;
    if ( v5 )
    {
      gSITRILC_Close[a1] = 0;
      gSITRILC_Open[a1] = 0;
      gSITRILC_Reconnect[a1] = 0;
      gSITRILC_RegisterUnsolicitedHandler[a1] = 0;
      gSITRILC_Send[a1] = 0;
      v6 = dlsym(v5, "RILC_Open");
      gSITRILC_Open[a1] = v6;
      if ( v6 )
      {
        _android_log_print(4, "RIL-AIMS", "%s() Martin gSITRILC_Open[%d]:0x%p ...", "RilAimsOpen", a1, gSITRILC_Open);
        v7 = dlsym((void *)gdlHandle[a1], "RILC_Close");
        gSITRILC_Close[a1] = v7;
        if ( v7 )
        {
          _android_log_print(4, "RIL-AIMS", "%s() gSITRILC_Close[%d]:0x%p ...", "RilAimsOpen", a1, gSITRILC_Close);
          v8 = dlsym((void *)gdlHandle[a1], "RILC_Reconnect");
          gSITRILC_Reconnect[a1] = v8;
          if ( v8 )
          {
            _android_log_print(
              4,
              "RIL-AIMS",
              "%s() gSITRILC_Reconnect[%d]:0x%p ...",
              "RilAimsOpen",
              a1,
              gSITRILC_Reconnect);
            v9 = dlsym((void *)gdlHandle[a1], "RILC_RegisterUnsolicitedHandler");
            gSITRILC_RegisterUnsolicitedHandler[a1] = v9;
            if ( v9 )
            {
              _android_log_print(
                4,
                "RIL-AIMS",
                "%s() gSITRILC_RegisterUnsolicitedHandler[%d]:0x%p ...",
                "RilAimsOpen",
                a1,
                gSITRILC_RegisterUnsolicitedHandler);
              v10 = dlsym((void *)gdlHandle[a1], "RILC_Send");
              gSITRILC_Send[a1] = v10;
              if ( v10 )
              {
                _android_log_print(4, "RIL-AIMS", "%s() gSITRILC_Send[%d]:0x%p ...", "RilAimsOpen", a1, gSITRILC_Send);
                v11 = ((int (*)(void))gSITRILC_Open[a1])();
                gSITRILC_Handle[a1] = v11;
                if ( v11 )
                {
                  _android_log_print(4, "RIL-AIMS", "%s() gSITRILC_Open[%d]() ... OK.", "RilAimsOpen", a1);
                  for ( i = 0; i < 3; ++i )
                  {
                    if ( dword_7058[i] )
                      goto LABEL_26;
                  }
                  if ( i != 3 )
                  {
LABEL_26:
                    v2 = "%s() Already registered gSITRILC_RegisterUnsolicitedHandler ... OK.";
                    goto LABEL_27;
                  }
                  if ( ((int (__fastcall *)(_DWORD, int (__fastcall *)(int, unsigned __int8 *, int, int)))gSITRILC_RegisterUnsolicitedHandler[a1])(
                         gSITRILC_Handle[a1],
                         sub_1FF0) )
                  {
                    _android_log_print(
                      6,
                      "RIL-AIMS",
                      "%s() !! ERROR !!, Fail in gSITRILC_RegisterUnsolicitedHandler[%d]()",
                      "RilAimsOpen",
                      a1);
                    v4 = 7;
                    goto LABEL_24;
                  }
                  v14 = (const char *)a1;
                  v2 = "%s() gSITRILC_RegisterUnsolicitedHandler[%d]() ... OK.";
LABEL_27:
                  v3 = 4;
                  goto LABEL_3;
                }
                _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, Fail in gSITRILC_Open[%d]()", "RilAimsOpen", a1);
                v4 = 5;
LABEL_24:
                j_RilAimsClose(a1);
                goto LABEL_25;
              }
              _android_log_print(
                6,
                "RIL-AIMS",
                "%s() !! ERROR !!, Fail in dlsym() for gSITRILC_Send[%d]",
                "RilAimsOpen",
                a1);
            }
            else
            {
              _android_log_print(
                6,
                "RIL-AIMS",
                "%s() !! ERROR !!, Fail in dlsym() for gSITRILC_RegisterUnsolicitedHandler[%d]",
                "RilAimsOpen",
                a1);
            }
          }
          else
          {
            _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, Fail in dlsym() for gSITRILC_Reconnect", "RilAimsOpen");
          }
        }
        else
        {
          _android_log_print(
            6,
            "RIL-AIMS",
            "%s() !! ERROR !!, Fail in dlsym() for gSITRILC_Close[%d]",
            "RilAimsOpen",
            a1);
        }
      }
      else
      {
        _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, Fail in dlsym() for gSITRILC_Open[%d]", "RilAimsOpen", a1);
      }
    }
    else
    {
      _android_log_print(6, "RIL-AIMS", "%s() client_id : %d !! ERROR !!, Fail in dlopen()", "RilAimsOpen", a1);
    }
    v4 = 3;
    goto LABEL_24;
  }
  v14 = "libsitril-client.so";
  v2 = "%s() SITRilClient(%s) already is opened ...";
  v3 = 5;
LABEL_3:
  _android_log_print(v3, "RIL-AIMS", v2, "RilAimsOpen", v14);
  v4 = 0;
LABEL_25:
  _android_log_print(4, "RIL-AIMS", "%s() [--> ", "RilAimsOpen");
  return v4;
}
// 1BD8: variable 'v14' is possibly undefined
// 192C: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 7004: using guessed type _DWORD gdlHandle[3];
// 7010: using guessed type _DWORD gSITRILC_Handle[3];
// 701C: using guessed type _DWORD gSITRILC_Open[3];
// 7028: using guessed type _DWORD gSITRILC_Close[3];
// 7034: using guessed type _DWORD gSITRILC_Reconnect[3];
// 7040: using guessed type _DWORD gSITRILC_RegisterUnsolicitedHandler[3];
// 704C: using guessed type _DWORD gSITRILC_Send[3];
// 7058: using guessed type _DWORD dword_7058[3];

//----- (00001FF0) --------------------------------------------------------
int __fastcall sub_1FF0(int a1, unsigned __int8 *a2, int a3, int a4)
{
  int v8; // r0
  int i; // r6

  _android_log_print(4, "RIL-AIMS", "%s() [<-- ", "SITRilClient__OnUnsolicitedResponse");
  _android_log_print(
    4,
    "RIL-AIMS",
    "%s() msgId(%d), data(0x%p), length(%zu) channel(%d)",
    "SITRilClient__OnUnsolicitedResponse",
    a1,
    a2,
    a3,
    a4);
  v8 = 0;
  while ( !dword_7058[v8] )
  {
    if ( ++v8 >= 3 )
    {
      if ( v8 == 3 )
      {
        _android_log_print(
          6,
          "RIL-AIMS",
          "%s() !! ERROR !!, gSITRilImsUnsolCallback == NULL",
          "SITRilClient__OnUnsolicitedResponse");
        return _android_log_print(4, "RIL-AIMS", "%s() [--> ", "SITRilClient__OnUnsolicitedResponse");
      }
      break;
    }
  }
  switch ( a1 )
  {
    case 3000:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_IMS_CONFIGURATION msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3000);
      goto LABEL_33;
    case 3001:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_IMS_DEDICATED_PDN_INFO msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3001);
      goto LABEL_33;
    case 3002:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_IMS_EMERGENCY_ACT_INFO msgId = %d, len = %zu",
        "SITRilClient__OnUnsolicitedResponse",
        3002,
        a3);
      goto LABEL_33;
    case 3003:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_IMS_SRVCC_HO msgId = %d, len = %zu",
        "SITRilClient__OnUnsolicitedResponse",
        3003,
        a3);
      goto LABEL_33;
    case 3004:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_IMS_EMERGENCY_CALL_LIST msgId = %d, len = %zu",
        "SITRilClient__OnUnsolicitedResponse",
        3004,
        a3);
      goto LABEL_33;
    case 3005:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_IMS_SUPPORT_SERVICE msgId = %d, Volte %d, EMC %d, sim %d, rat %d",
        "SITRilClient__OnUnsolicitedResponse",
        3005,
        *a2,
        a2[1],
        a2[2],
        a2[3]);
      goto LABEL_33;
    case 3006:
    case 3007:
    case 3008:
    case 3009:
      return _android_log_print(
               6,
               "RIL-AIMS",
               "%s() !! ERROR !!, Unknown msgId = %d",
               "SITRilClient__OnUnsolicitedResponse",
               a1);
    case 3010:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CALL_RING msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3010);
      goto LABEL_33;
    case 3011:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CALL_STATUS msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3011);
      goto LABEL_33;
    case 3012:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_REGISTRATION msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3012);
      goto LABEL_33;
    case 3013:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CALL_MODIFY msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3013);
      goto LABEL_33;
    case 3014:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_FRAME_TIME msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3014);
      goto LABEL_33;
    case 3015:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_SUPP_SVC_NOTIFICATION msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3015);
      goto LABEL_33;
    case 3016:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_NEW_SMS msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3016);
      goto LABEL_33;
    case 3017:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_NEW_SMS_STATUS_REPORT msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3017);
      goto LABEL_33;
    case 3018:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_ON_USSD msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3018);
      goto LABEL_33;
    case 3019:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CONFERENCE_CALL_EVENT msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3019);
      goto LABEL_33;
    case 3020:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_HO_PAYLOAD msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3020);
      goto LABEL_33;
    case 3021:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s RILC_UNSOL_AIMS_VOWIFI_HO_CALL_INFO msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3021);
      goto LABEL_33;
    case 3022:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s RILC_UNSOL_AIMS_NEW_CDMA_SMS msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3022);
      goto LABEL_33;
    case 3023:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CALL_MANAGE msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3023);
      goto LABEL_33;
    case 3024:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CONF_CALL_ADD_REMOVE_USER msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3024);
      goto LABEL_33;
    case 3025:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_ENHANCED_CONF_CALL msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3025);
      goto LABEL_33;
    case 3026:
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AIMS_CALL_MODIFY_RSP msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        3026);
      goto LABEL_33;
    default:
      if ( a1 != 2003 )
        return _android_log_print(
                 6,
                 "RIL-AIMS",
                 "%s() !! ERROR !!, Unknown msgId = %d",
                 "SITRilClient__OnUnsolicitedResponse",
                 a1);
      _android_log_print(
        4,
        "RIL-AIMS",
        "%s() RILC_UNSOL_AUDIO_RINGBACK msgId = %d",
        "SITRilClient__OnUnsolicitedResponse",
        2003);
LABEL_33:
      for ( i = 0; i != 3; ++i )
      {
        if ( dword_7058[i] )
        {
          _android_log_print(
            4,
            "RIL-AIMS",
            "%s() Send unsol msg msgId = %d, client id = %d, socket_id = %d",
            "SITRilClient__OnUnsolicitedResponse",
            a1,
            i,
            a4);
          ((void (__fastcall *)(int, unsigned __int8 *, int, int))dword_7058[i])(a1, a2, a3, a4);
        }
      }
      break;
  }
  return _android_log_print(4, "RIL-AIMS", "%s() [--> ", "SITRilClient__OnUnsolicitedResponse");
}
// 192C: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 7058: using guessed type _DWORD dword_7058[3];

//----- (00002490) --------------------------------------------------------
int __fastcall Close(int a1)
{
  j_RilAimsClose(a1);
  return 0;
}

//----- (0000249C) --------------------------------------------------------
int __fastcall RilAimsClose(int a1)
{
  void (*v2)(void); // r1
  void *v3; // r0

  _android_log_print(4, "RIL-AIMS", "%s() [<-- ", "RilAimsClose");
  if ( gSITRILC_Send[a1] )
    gSITRILC_Send[a1] = 0;
  if ( gSITRILC_RegisterUnsolicitedHandler[a1] )
    gSITRILC_RegisterUnsolicitedHandler[a1] = 0;
  if ( gSITRILC_Reconnect[a1] )
    gSITRILC_Reconnect[a1] = 0;
  v2 = (void (*)(void))gSITRILC_Close[a1];
  if ( v2 )
  {
    if ( gSITRILC_Handle[a1] )
    {
      v2();
      _android_log_print(4, "RIL-AIMS", "%s() gSITRILC_Close[%d]() ... OK.", "RilAimsClose", a1);
      gSITRILC_Handle[a1] = 0;
    }
    gSITRILC_Close[a1] = 0;
  }
  if ( gSITRILC_Open[a1] )
    gSITRILC_Open[a1] = 0;
  v3 = (void *)gdlHandle[a1];
  if ( v3 )
  {
    dlclose(v3);
    gdlHandle[a1] = 0;
  }
  _android_log_print(4, "RIL-AIMS", "%s() [--> ", "RilAimsClose");
  return 0;
}
// 192C: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 7004: using guessed type _DWORD gdlHandle[3];
// 7010: using guessed type _DWORD gSITRILC_Handle[3];
// 701C: using guessed type _DWORD gSITRILC_Open[3];
// 7028: using guessed type _DWORD gSITRILC_Close[3];
// 7034: using guessed type _DWORD gSITRILC_Reconnect[3];
// 7040: using guessed type _DWORD gSITRILC_RegisterUnsolicitedHandler[3];
// 704C: using guessed type _DWORD gSITRILC_Send[3];

//----- (000025EC) --------------------------------------------------------
int __fastcall RilAimsRegisterCallback(int a1, const void *a2)
{
  int v4; // r4

  _android_log_print(4, "RIL-AIMS", "%s() [<-- ", "RilAimsRegisterCallback");
  if ( dword_7058[a1] )
  {
    _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, gSITRilImsCallback(%p)", "RilAimsRegisterCallback", dword_7058);
    v4 = 8;
  }
  else
  {
    dword_7058[a1] = a2;
    _android_log_print(4, "RIL-AIMS", "%s() new gSITRilImsCallback[%d](%p)", "RilAimsRegisterCallback", a1, a2);
    v4 = 0;
  }
  _android_log_print(4, "RIL-AIMS", "%s() [--> ", "RilAimsRegisterCallback");
  return v4;
}
// 192C: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 7058: using guessed type _DWORD dword_7058[3];

//----- (000026A0) --------------------------------------------------------
int __fastcall SetImsConfiguration(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 30, a2, a3, a4, 2u);
}

//----- (000026BA) --------------------------------------------------------
int __fastcall GetImsConfiguration(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 31, a2, a3, a4, 2u);
}

//----- (000026D4) --------------------------------------------------------
int __fastcall GetSimAuth(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 32, a2, a3, a4, 2u);
}

//----- (000026EE) --------------------------------------------------------
int __fastcall SetEmergencyCallStatus(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 33, a2, a3, a4, 2u);
}

//----- (00002708) --------------------------------------------------------
int __fastcall SetSrvccCallList(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 34, a2, a3, a4, 2u);
}

//----- (00002722) --------------------------------------------------------
int __fastcall GetGBAAuth(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 35, a2, a3, a4, 2u);
}

//----- (0000273C) --------------------------------------------------------
int __fastcall RequestAimsForChannelId(
        unsigned int a1,
        int a2,
        const void *a3,
        int a4,
        const void *a5,
        unsigned int a6)
{
  const char *v10; // r2
  int v11; // r0
  bool v12; // zf
  int v13; // r4
  int v14; // r0
  int (__fastcall *v15)(int, int); // r6
  const void *v17; // [sp+0h] [bp-30h]

  _android_log_print(4, "RIL-AIMS", "%s() [<-- ", "RequestAimsForChannelId");
  _android_log_print(
    4,
    "RIL-AIMS",
    "%s: msdId=%d data=0x0%p data_len=%d callback=0x%p",
    "RequestAimsForChannelId",
    a2,
    a3,
    a4,
    a5);
  if ( a1 >= 3 )
  {
    v10 = "%s() !! ERROR !!, array out of index. client_id=%d";
    v17 = (const void *)a1;
LABEL_8:
    v13 = 6;
    v14 = 6;
LABEL_16:
    _android_log_print(v14, "RIL-AIMS", v10, "RequestAimsForChannelId", v17);
    return v13;
  }
  v11 = gSITRILC_Handle[a1];
  if ( !v11 )
  {
    _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, gSITRILC_Handle[%d] == NULL", "RequestAimsForChannelId", a1);
    v13 = 3;
LABEL_15:
    v14 = 4;
    v10 = "%s() [--> ";
    goto LABEL_16;
  }
  v12 = a6 == 2;
  if ( a6 != 2 )
    v12 = (a6 | 1) == 1;
  if ( !v12 )
  {
    v17 = (const void *)a6;
    v10 = "%s() !! ERROR !!, unsupported channel=%d";
    goto LABEL_8;
  }
  v15 = (int (__fastcall *)(int, int))gSITRILC_Send[a1];
  if ( v15 )
  {
    v17 = a5;
    if ( v15(v11, a2) )
    {
      _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, Fail in gSITRILC_Send[%d]() ", "RequestAimsForChannelId", a1);
      v13 = 4;
    }
    else
    {
      v13 = 0;
    }
    goto LABEL_15;
  }
  _android_log_print(6, "RIL-AIMS", "%s() !! ERROR !!, gSITRILC_Send[%d] == NULL", "RequestAimsForChannelId", a1);
  return 4;
}
// 282E: variable 'v17' is possibly undefined
// 0: using guessed type int dword_0;
// 192C: using guessed type int _android_log_print(_DWORD, _DWORD, const char *, ...);
// 7010: using guessed type _DWORD gSITRILC_Handle[3];
// 704C: using guessed type _DWORD gSITRILC_Send[3];

//----- (0000289C) --------------------------------------------------------
int __fastcall RequestAimsDial(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 100, a2, a3, a4, 2u);
}

//----- (000028B6) --------------------------------------------------------
int __fastcall RequestAimsAnswer(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 101, a2, a3, a4, 2u);
}

//----- (000028D0) --------------------------------------------------------
int __fastcall ReqeustAimsHangup(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 102, a2, a3, a4, 2u);
}

//----- (000028EA) --------------------------------------------------------
int __fastcall RequestAimsDegregistration(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 103, a2, a3, a4, 2u);
}

//----- (00002904) --------------------------------------------------------
int __fastcall RequestAimsHiddenMenu(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 104, a2, a3, a4, 2u);
}

//----- (0000291E) --------------------------------------------------------
int __fastcall RequestAimsPdnInfo(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 105, a2, a3, a4, 2u);
}

//----- (00002938) --------------------------------------------------------
int __fastcall RequestAimsCallManage(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 106, a2, a3, a4, 2u);
}

//----- (00002952) --------------------------------------------------------
int __fastcall RequestAimsSendDtmf(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 107, a2, a3, a4, 2u);
}

//----- (0000296C) --------------------------------------------------------
int __fastcall RequestAimsSetFrameTime(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 108, a2, a3, a4, 2u);
}

//----- (00002986) --------------------------------------------------------
int __fastcall RequestAimsGetFrameTime(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 109, a2, a3, a4, 2u);
}

//----- (000029A0) --------------------------------------------------------
int __fastcall RequestAimsCallModify(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 110, a2, a3, a4, 2u);
}

//----- (000029BA) --------------------------------------------------------
int __fastcall RequestAimsResponseCallModify(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 111, a2, a3, a4, 2u);
}

//----- (000029D4) --------------------------------------------------------
int __fastcall RequestAimsTimeInfo(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 112, a2, a3, a4, 2u);
}

//----- (000029EE) --------------------------------------------------------
int __fastcall RequestAimsConfCallAddRemoveUser(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 113, a2, a3, a4, 2u);
}

//----- (00002A08) --------------------------------------------------------
int __fastcall RequestAimsEnhancedConfCall(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 114, a2, a3, a4, 2u);
}

//----- (00002A22) --------------------------------------------------------
int __fastcall RequestAimsGetCallForwardStatus(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 115, a2, a3, a4, 2u);
}

//----- (00002A3C) --------------------------------------------------------
int __fastcall RequestAimsSetCallForwardStatus(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 116, a2, a3, a4, 2u);
}

//----- (00002A56) --------------------------------------------------------
int __fastcall RequestAimsGetCallWaiting(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 117, a2, a3, a4, 2u);
}

//----- (00002A70) --------------------------------------------------------
int __fastcall RequestAimsSetCallWaiting(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 118, a2, a3, a4, 2u);
}

//----- (00002A8A) --------------------------------------------------------
int __fastcall RequestAimsGetCallBarring(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 119, a2, a3, a4, 2u);
}

//----- (00002AA4) --------------------------------------------------------
int __fastcall RequestAimsSetCallBarring(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 120, a2, a3, a4, 2u);
}

//----- (00002ABE) --------------------------------------------------------
int __fastcall RequestAimsSendSms(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 121, a2, a3, a4, 2u);
}

//----- (00002AD8) --------------------------------------------------------
int __fastcall RequestAimsSendSmsExpectMore(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 122, a2, a3, a4, 2u);
}

//----- (00002AF2) --------------------------------------------------------
int __fastcall RequestAimsSendSmsAck(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 123, a2, a3, a4, 2u);
}

//----- (00002B0C) --------------------------------------------------------
int __fastcall RequestAimsAckIncomingGsmSms(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 124, a2, a3, a4, 2u);
}

//----- (00002B26) --------------------------------------------------------
int __fastcall RequestAimsChangeBarringPassword(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 125, a2, a3, a4, 2u);
}

//----- (00002B40) --------------------------------------------------------
int __fastcall RequestAimsSendUssdInfo(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 126, a2, a3, a4, 2u);
}

//----- (00002B5A) --------------------------------------------------------
int __fastcall RequestAimsGetPresentationSettings(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 127, a2, a3, a4, 2u);
}

//----- (00002B74) --------------------------------------------------------
int __fastcall RequestAimsSetPresentationSettings(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 128, a2, a3, a4, 2u);
}

//----- (00002B8E) --------------------------------------------------------
int __fastcall RequestAimsSetSelfCapability(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 129, a2, a3, a4, 2u);
}

//----- (00002BA8) --------------------------------------------------------
int __fastcall RequestAimsHoToWifiReady(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 130, a2, a3, a4, 2u);
}

//----- (00002BC2) --------------------------------------------------------
int __fastcall RequestAimsHoToWifiCancel(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 131, a2, a3, a4, 2u);
}

//----- (00002BDC) --------------------------------------------------------
int __fastcall RequestAimsHoPayloadInd(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 132, a2, a3, a4, 2u);
}

//----- (00002BF6) --------------------------------------------------------
int __fastcall RequestAimsHoTo3gpp(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 133, a2, a3, a4, 2u);
}

//----- (00002C10) --------------------------------------------------------
int __fastcall RequestAimsAckIncomingCdmaSms(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 134, a2, a3, a4, 2u);
}

//----- (00002C2A) --------------------------------------------------------
int __fastcall RequestAimsMediaStateInd(unsigned int a1, const void *a2, int a3, const void *a4)
{
  return j_RequestAimsForChannelId(a1, 135, a2, a3, a4, 2u);
}

//----- (00002C44) --------------------------------------------------------
void __fastcall ProductFeature::ProductFeature(ProductFeature *this)
{
  *(_DWORD *)this = &off_6D5C;
}
// 6D5C: using guessed type void *;

//----- (00002C5A) --------------------------------------------------------
int __fastcall ProductFeature::Init(ProductFeature *this, const char *a2)
{
  void *Instance; // r0

  Instance = ProductFeature::GetInstance(this);
  (*(void (__fastcall **)(void *, ProductFeature *))(*(_DWORD *)Instance + 8))(Instance, this);
  return 1;
}

//----- (00002C70) --------------------------------------------------------
int __fastcall ProductFeature::Custom_SupportOnly5Mode(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::SupportOnly5Mode == %s", v1, "true");
  return 1;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002CA0) --------------------------------------------------------
int __fastcall ProductFeature::Custom_SupportOnlyBasicPreferredNetworkType(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::SupportOnlyBasicPreferredNetworkType == %s", v1, "true");
  return 1;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002CD0) --------------------------------------------------------
int __fastcall ProductFeature::Function_SendDebugTraceOffAtBootup(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::SendDebugTraceOffAtBootup == %s", v1, "false");
  return 0;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002D00) --------------------------------------------------------
int __fastcall ProductFeature::Function_GetFastDormancyInfo(
        ProductFeature *this,
        unsigned __int8 *a2,
        unsigned __int8 *a3,
        unsigned __int8 *a4,
        unsigned __int8 *a5)
{
  const char *v8; // r0

  *a2 = 0;
  *a3 = 0;
  *a4 = 0;
  *a5 = 0;
  v8 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(
    1,
    4,
    0,
    "[%s]  ProductFeature::SupportFastDormancyInfo == %s(%d,%d,%d,%d [.5sec/unit]))",
    v8,
    "false",
    *a2,
    *a3,
    *a4,
    *a5);
  return 0;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002D4C) --------------------------------------------------------
int __fastcall ProductFeature::Function_RilResetByCrashExitInUserMode(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::RilResetByModemCrash == %s", v1, "false");
  return 0;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002D7C) --------------------------------------------------------
int __fastcall ProductFeature::Function_DeviceBasedCwInCs(ProductFeature *this)
{
  const char *v1; // r0

  v1 = (const char *)(*(int (__fastcall **)(ProductFeature *))(*(_DWORD *)this + 12))(this);
  _android_log_buf_print(1, 4, 0, "[%s]  ProductFeature::DeviceBasedCWinCS == %s", v1, "true");
  return 1;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002DAC) --------------------------------------------------------
const char *sub_2DAC()
{
  return "/efs/";
}

//----- (00002DB8) --------------------------------------------------------
const char *sub_2DB8()
{
  return "/efs/backup/nv_protected";
}

//----- (00002DC4) --------------------------------------------------------
void *__fastcall ProductFeature::GetInstance(ProductFeature *this)
{
  return &instance;
}

//----- (00002DD0) --------------------------------------------------------
void __fastcall CustomProductFeature::CustomProductFeature(CustomProductFeature *this)
{
  _DWORD *v1; // r0

  ProductFeature::ProductFeature(this);
  *v1 = &off_6D88;
}
// 2DDE: variable 'v1' is possibly undefined
// 6D88: using guessed type void *;

//----- (00002DEC) --------------------------------------------------------
void __fastcall CustomProductFeature::~CustomProductFeature(CustomProductFeature *this)
{
  void *v1; // r0

  ProductFeature::~ProductFeature(this);
  operator delete(v1);
}
// 2DF6: variable 'v1' is possibly undefined

//----- (00002DFC) --------------------------------------------------------
int __fastcall CustomProductFeature::CustomInit(CustomProductFeature *this, const char *a2)
{
  const char *v2; // r0

  v2 = "unknown";
  if ( a2 )
    v2 = a2;
  _android_log_buf_print(1, 4, 0, "<%s> [%s] CustomProductFeature::Init", v2, "m86");
  return 1;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002E34) --------------------------------------------------------
const char *__fastcall CustomProductFeature::GetProductName(CustomProductFeature *this)
{
  return "m86";
}

//----- (00002E40) --------------------------------------------------------
int __fastcall CustomProductFeature::Custom_SaveImeiToProperty(CustomProductFeature *this)
{
  _android_log_buf_print(1, 4, 0, "[%s] CustomProductFeature::SaveImeiToProperty == %s", "m86", "true");
  return 1;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002E70) --------------------------------------------------------
int __fastcall CustomProductFeature::Custom_ReturnCurrentPlmn(CustomProductFeature *this)
{
  _android_log_buf_print(1, 4, 0, "[%s] CustomProductFeature::ReturnCurrentPlmn == %s", "m86", "false");
  return 0;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002EA0) --------------------------------------------------------
int __fastcall CustomProductFeature::ModuleAudio_VolumeStartFrom1(CustomProductFeature *this)
{
  _android_log_buf_print(1, 4, 0, "[%s] CustomProductFeature::VolumeStartFrom1 == %s", "m86", "true");
  return 1;
}
// 198C: using guessed type int _android_log_buf_print(_DWORD, _DWORD, _DWORD, const char *, ...);

//----- (00002ED0) --------------------------------------------------------
const char *sub_2ED0()
{
  return "/efs/nv_data/";
}

//----- (00002EDC) --------------------------------------------------------
const char *sub_2EDC()
{
  return "/mnv/bak/nv_protected";
}

//----- (00002EE8) --------------------------------------------------------
unsigned int *__fastcall sub_2EE8(unsigned int *result, int *a2, int *a3)
{
  unsigned int v3; // r3
  unsigned int v4; // t1
  int v5; // r12
  bool v6; // zf
  int v7; // r3
  int v8; // r12

  v3 = *result;
  if ( (*result & 0x80000000) == 0 )
  {
    *a2 = 1;
    v4 = result[1];
    ++result;
    *a3 = 4 * HIBYTE(v4) + 4;
    return result;
  }
  v5 = HIBYTE(v3) & 0xF;
  if ( v5 )
  {
    v6 = v5 == 3;
    if ( v5 != 3 )
      v6 = v5 == 1;
    if ( !v6 )
      return 0;
    v7 = 4 * BYTE2(v3) + 4;
    v8 = 2;
  }
  else
  {
    v8 = 1;
    v7 = 4;
  }
  *a3 = v7;
  *a2 = v8;
  return result;
}

//----- (00002F3C) --------------------------------------------------------
int __fastcall sub_2F3C(int a1, int a2, unsigned int a3, unsigned int a4)
{
  unsigned int v6; // r11
  unsigned int v8; // r7
  int v9; // r10
  int v10; // r2
  unsigned int v11; // r1
  int result; // r0
  int v13; // r3
  int v14; // r2
  int v15; // r0
  int v16; // r1
  int v17; // r2
  int v18; // r1
  int v19; // r6
  int v20; // r2
  int v21; // r0
  int v22; // r1
  int v23; // r3
  int v24; // r0
  int v25; // r2
  int v26; // r0
  unsigned int v33; // r1
  unsigned int v34; // r0
  int v35; // r1
  unsigned int v36; // r0
  int v37; // [sp+0h] [bp-30h]
  int v38; // [sp+4h] [bp-2Ch] BYREF

  v6 = a3;
  if ( a3 >= a4 )
  {
LABEL_54:
    sub_382C(a1, 14, &v38);
    sub_385A(a1, 15, v38);
    return 8;
  }
  v37 = 0;
  do
  {
    v8 = v6 + 1;
    v9 = *(unsigned __int8 *)(a2 + (v6 ^ 3));
    if ( (v9 & 0x80) == 0 )
    {
      sub_382C(a1, 13, &v38);
      if ( (v9 & 0x40) != 0 )
        v10 = -4 - (unsigned __int8)(4 * v9) + v38;
      else
        v10 = 4 * v9 + v38 + 4;
LABEL_12:
      v38 = v10;
LABEL_13:
      sub_385A(a1, 13, v10);
LABEL_36:
      v6 = v8;
      continue;
    }
    v11 = v9 & 0xF0;
    result = 9;
    if ( v11 > 0xAF )
    {
      if ( v11 == 176 )
      {
        result = 9;
        v18 = 0;
        v19 = 0;
        switch ( *(_BYTE *)(a2 + (v6 ^ 3)) )
        {
          case 0xB0:
            goto LABEL_53;
          case 0xB1:
            if ( v8 >= a4 )
              return 9;
            v20 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
            result = 9;
            if ( !*(_BYTE *)(a2 + (v8 ^ 3)) || (v20 & 0xF0) != 0 )
              return result;
            v21 = a1;
            v22 = 0;
            v23 = 0;
            goto LABEL_48;
          case 0xB2:
            break;
          case 0xB3:
            v23 = 1;
            v26 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
            _R1 = v26 << 12;
            __asm { UXTB16.W        R1, R1 }
            v20 = ((v26 & 0xF) + 1) | _R1;
            v21 = a1;
            v22 = 1;
            goto LABEL_48;
          case 0xB4:
          case 0xB5:
          case 0xB6:
          case 0xB7:
            return result;
          default:
            v16 = 1;
            v13 = 1;
            v14 = ((v9 & 7) + 1) | 0x80000;
            v15 = a1;
            goto LABEL_35;
        }
        while ( v8 < a4 )
        {
          v24 = v8++ ^ 3;
          LOBYTE(v24) = *(_BYTE *)(a2 + v24);
          v25 = (v24 & 0x7F) << v18;
          v18 += 7;
          v19 |= v25;
          if ( (v24 & 0x80) == 0 )
          {
            sub_382C(a1, 13, &v38);
            v10 = v38 + 4 * v19 + 516;
            goto LABEL_12;
          }
        }
        return 9;
      }
      if ( v11 != 192 )
      {
        if ( v11 != 208 )
          return result;
        if ( (v9 & 8) != 0 )
          return 9;
        v16 = 1;
        v14 = ((v9 & 7) + 1) | 0x80000;
        v15 = a1;
LABEL_34:
        v13 = 5;
        goto LABEL_35;
      }
      switch ( *(_BYTE *)(a2 + (v6 ^ 3)) )
      {
        case 0xC0:
        case 0xC1:
        case 0xC2:
        case 0xC3:
        case 0xC4:
        case 0xC5:
          v16 = 3;
          v14 = ((v9 & 7) + 1) | 0xA0000;
          v15 = a1;
          goto LABEL_34;
        case 0xC6:
          v36 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
          if ( (v36 & 0xF) + (v36 >> 4) > 0xF )
            return 9;
          v20 = ((v36 & 0xF) + 1) | (v36 >> 4 << 16);
          v21 = a1;
          v22 = 3;
          break;
        case 0xC7:
          if ( !*(_BYTE *)(a2 + (v8 ^ 3)) || *(unsigned __int8 *)(a2 + (v8 ^ 3)) >= 0x10u )
            return 9;
          goto LABEL_49;
        case 0xC8:
        case 0xC9:
          v33 = *(unsigned __int8 *)(a2 + (v8 ^ 3));
          v34 = v33 >> 4;
          if ( v9 == 200 )
            v34 = (v33 >> 4) | 0x10;
          v35 = v33 & 0xF;
          if ( v34 + v35 > 0x1F )
            return 9;
          v20 = (v35 + 1) | (v34 << 16);
          v21 = a1;
          v22 = 1;
          break;
        default:
          return 9;
      }
      v23 = 5;
LABEL_48:
      sub_331C(v21, v22, v20, v23);
    }
    else
    {
      if ( v11 != 128 )
      {
        if ( v11 == 144 )
        {
          if ( (v9 & 0xD | 2) == 15 )
            return 9;
          sub_382C(a1, v9 & 0xF, &v38);
          v10 = v38;
          goto LABEL_13;
        }
        if ( v11 != 160 )
          return result;
        v13 = 0;
        v14 = ((16 << ((v9 & 7) + 1)) - 16) | (v9 << 11) & 0x4000;
        v15 = a1;
        v16 = 0;
LABEL_35:
        sub_331C(v15, v16, v14, v13);
        goto LABEL_36;
      }
      if ( v8 >= a4 )
        return 9;
      v17 = (unsigned __int16)((_WORD)v9 << 12) | (16 * *(unsigned __int8 *)(a2 + (v8 ^ 3)));
      if ( !v17 )
        return 9;
      sub_331C(a1, 0, v17, 0);
      v37 |= (unsigned __int16)(((_WORD)v9 << 12) & 0x8000) >> 15;
    }
LABEL_49:
    v6 += 2;
  }
  while ( v6 < a4 );
LABEL_53:
  if ( (v37 & 1) == 0 )
    goto LABEL_54;
  return 8;
}

//----- (00003280) --------------------------------------------------------
int __fastcall sub_3280(int a1, int a2, unsigned int a3, int a4, int *a5)
{
  int result; // r0
  int v8; // r2
  int v9; // r0
  int v10; // r1
  __int64 v11; // r2
  int v12; // r1

  switch ( a2 )
  {
    case 0:
      result = 2;
      if ( a3 > 0xF || a4 )
        return result;
      v8 = *a5;
      v9 = a1;
      v10 = a3;
      goto LABEL_11;
    case 1:
      if ( a4 == 5 )
      {
        if ( a3 <= 0x1F )
          goto LABEL_19;
        return 2;
      }
      if ( a4 != 1 || a3 > 0xF )
        return 2;
      sub_393C(a1);
LABEL_19:
      v11 = *(_QWORD *)a5;
      v12 = a3 + 256;
LABEL_20:
      result = sub_38CE(a1, v12, v11, SHIDWORD(v11));
LABEL_21:
      if ( result )
        return 2;
      return result;
    case 3:
      result = 2;
      if ( a3 > 0x1F || a4 != 5 )
        return result;
      v11 = *(_QWORD *)a5;
      v12 = a3 + 112;
      goto LABEL_20;
    case 4:
      result = 2;
      if ( a3 > 3 || a4 )
        return result;
      v8 = *a5;
      v10 = a3 + 192;
      v9 = a1;
LABEL_11:
      result = sub_385A(v9, v10, v8);
      goto LABEL_21;
    default:
      sub_3698(
        "_Unwind_VRS_Result _Unwind_VRS_Set(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation, void *)",
        837,
        "unsupported register class");
  }
}

//----- (0000331C) --------------------------------------------------------
int __fastcall sub_331C(int a1, int a2, unsigned int a3, int a4)
{
  char v8; // r4
  unsigned int i; // r7
  int *v10; // r0
  int v11; // r0
  char v12; // r1
  char v13; // r2
  int result; // r0
  unsigned int v15; // r4
  unsigned int v16; // r6
  int *v17; // r0
  int v18; // r2
  int v19; // r0
  int v20; // r2
  int v21[2]; // [sp+8h] [bp-30h] BYREF
  int *v22; // [sp+10h] [bp-28h] BYREF

  switch ( a2 )
  {
    case 0:
    case 4:
      if ( a4 || sub_382C(a1, 13, v21) )
        return 2;
      v8 = 0;
      for ( i = 0; i < 0x10; ++i )
      {
        if ( ((1 << i) & a3) != 0 )
        {
          v10 = (int *)v21[0];
          v21[0] += 4;
          v22 = (int *)*v10;
          v11 = sub_3280(a1, a2, i, 0, (int *)&v22);
          v12 = 0;
          v13 = 0;
          if ( i == 13 )
            v12 = 1;
          if ( !a2 )
            v13 = 1;
          if ( v11 )
            return 2;
          v8 |= v13 & v12;
        }
      }
      if ( (v8 & 1) != 0 )
        return 0;
      v20 = v21[0];
      goto LABEL_26;
    case 1:
    case 3:
      if ( (a4 | 4) != 5 || sub_382C(a1, 13, &v22) )
        return 2;
      if ( !(_WORD)a3 )
        goto LABEL_21;
      v15 = HIWORD(a3);
      v16 = HIWORD(a3) + (unsigned __int16)a3;
      break;
    default:
      sub_3698(
        "_Unwind_VRS_Result _Unwind_VRS_Pop(_Unwind_Context *, _Unwind_VRS_RegClass, uint32_t, _Unwind_VRS_DataRepresentation)",
        971,
        "unsupported register class");
  }
  do
  {
    v17 = v22++;
    v18 = *v17;
    v22 = v17 + 2;
    v19 = v17[1];
    v21[0] = v18;
    v21[1] = v19;
    if ( sub_3280(a1, a2, v15, a4, v21) )
      return 2;
    ++v15;
  }
  while ( v15 < v16 );
LABEL_21:
  if ( a4 == 1 )
    v20 = (int)++v22;
  else
    v20 = (int)v22;
LABEL_26:
  result = sub_385A(a1, 13, v20);
  if ( result )
    return 2;
  return result;
}

//----- (000034CC) --------------------------------------------------------
int __fastcall sub_34CC(int *a1, int a2, int a3, int a4)
{
  int v5; // r5
  int (__fastcall *v6)(_DWORD, int *, char *); // r3
  int v7; // r0
  int v9[3]; // [sp+0h] [bp-8A0h] BYREF
  int (__fastcall *v10)(_DWORD, int *, char *); // [sp+Ch] [bp-894h]
  int v11; // [sp+14h] [bp-88Ch]
  int v12; // [sp+20h] [bp-880h]
  _DWORD v13[256]; // [sp+28h] [bp-878h] BYREF
  char v14[1120]; // [sp+428h] [bp-478h] BYREF

  sub_3760(v13, a2, a3, a4, v9[0]);
  a1[3] = 0;
  sub_37E8((int)v14, v13);
  if ( sub_390C((int)v14, (int)v9) )
    return 3;
  v5 = 3;
  while ( 1 )
  {
    v6 = v10;
    if ( v10 )
    {
      a1[18] = v9[0];
      a1[19] = v12;
      a1[20] = v11;
      v7 = v6(0, a1, v14);
      if ( v7 != 8 )
        break;
    }
    if ( sub_390C((int)v14, (int)v9) )
      return 3;
  }
  if ( v7 == 6 )
  {
    sub_3578(v13, a1, 0);
    return 2;
  }
  else if ( v7 == 9 )
  {
    return 9;
  }
  return v5;
}
// 34CC: using guessed type _DWORD var_878[256];

//----- (00003578) --------------------------------------------------------
int __fastcall sub_3578(const void *a1, int *a2, char a3)
{
  int i; // r6
  int v6; // r7
  int (__fastcall *v7)(int, int *, char *); // r3
  int v8; // r0
  int v10; // [sp+0h] [bp-4B8h] BYREF
  int v11[3]; // [sp+4h] [bp-4B4h] BYREF
  int (__fastcall *v12)(int, int *, char *); // [sp+10h] [bp-4A8h]
  int v13; // [sp+18h] [bp-4A0h]
  int v14; // [sp+24h] [bp-494h]
  int v15; // [sp+2Ch] [bp-48Ch] BYREF
  char v16[1124]; // [sp+30h] [bp-488h] BYREF
  int v17; // [sp+494h] [bp-24h]

  sub_37E8((int)v16, a1);
  for ( i = 1; ; --i )
  {
    v6 = 1;
    if ( (a3 & 1) != 0 )
    {
      v6 = 2;
      if ( !i )
      {
        sub_385A((int)v16, -1, a2[4]);
        a3 = 0;
      }
    }
    sub_382C((int)v16, -2, &v15);
    if ( sub_390C((int)v16, (int)v11) )
      break;
    v7 = v12;
    if ( v12 )
    {
      a2[18] = v11[0];
      a2[19] = v14;
      a2[20] = v13;
      v8 = v7(v6, a2, v16);
      if ( v8 == 7 )
      {
        sub_382C((int)v16, -1, &v10);
        a2[4] = v10;
        sub_392A((int)v16);
        return _stack_chk_guard - v17;
      }
      if ( v8 != 8 )
      {
        if ( v8 == 9 )
          abort();
        return _stack_chk_guard - v17;
      }
      if ( v15 == a2[8] )
        sub_3698(
          "_Unwind_Reason_Code unwind_phase2(unw_context_t *, _Unwind_Exception *, bool)",
          653,
          "during phase1 personality function said it would stop here, but now in phase2 it did not stop here");
    }
  }
  return _stack_chk_guard - v17;
}
// 3578: using guessed type int var_4B4[3];

//----- (00003664) --------------------------------------------------------
void __fastcall __noreturn sub_3664(int *a1, int a2, int a3, int a4)
{
  int v5[260]; // [sp+0h] [bp-410h] BYREF

  sub_3760(v5, a2, a3, a4, v5[0]);
  sub_3578(v5, a1, 1);
  sub_3698("void _Unwind_Resume(_Unwind_Exception *)", 753, "_Unwind_Resume() can't return");
}

//----- (00003698) --------------------------------------------------------
void __fastcall __noreturn sub_3698(const char *a1, int a2, const char *a3)
{
  fprintf(stderr, "libunwind: %s %s:%d - %s\n", a1, "external/libunwind_llvm/src/Unwind-EHABI.cpp", a2, a3);
  abort();
}

//----- (000036C8) --------------------------------------------------------
int __fastcall sub_36C8(int a1)
{
  int v1; // r1
  int result; // r0
  char v3[8]; // [sp+4h] [bp-34h] BYREF
  int v4; // [sp+Ch] [bp-2Ch]

  v1 = sub_390C(a1, (int)v3);
  result = v4;
  if ( v1 )
    return 0;
  return result;
}
// 36C8: using guessed type char var_34[8];

//----- (00003704) --------------------------------------------------------
int __fastcall sub_3704(int a1)
{
  int v1; // r1
  int result; // r0
  int v3[10]; // [sp+4h] [bp-34h] BYREF

  v1 = sub_390C(a1, (int)v3);
  result = v3[0];
  if ( v1 )
    return 0;
  return result;
}
// 3704: using guessed type int var_34[10];

//----- (0000374C) --------------------------------------------------------
int __fastcall sub_374C(int a1, int a2)
{
  int v2; // r0
  int v3; // r1

  v2 = sub_3906(a2);
  v3 = 9;
  if ( v2 == 1 )
    return 0;
  return v3;
}

//----- (00003760) --------------------------------------------------------
int __fastcall sub_3760(_DWORD *a1, int a2, int a3, int a4, int a5)
{
  int v5; // r4
  int v6; // r5
  int v7; // r6
  int v8; // r7
  int v9; // r8
  int v10; // r9
  int v11; // r10
  int v12; // r11
  int v13; // r12
  int v14; // lr

  *a1 = a1;
  a1[1] = a2;
  a1[2] = a3;
  a1[3] = a4;
  a1[4] = v5;
  a1[5] = v6;
  a1[6] = v7;
  a1[7] = v8;
  a1[8] = v9;
  a1[9] = v10;
  a1[10] = v11;
  a1[11] = v12;
  a1[12] = v13;
  a1[13] = &a5;
  a1[14] = v14;
  a1[15] = v14;
  return 0;
}
// 3760: variable 'v5' is possibly undefined
// 3760: variable 'v6' is possibly undefined
// 3760: variable 'v7' is possibly undefined
// 3760: variable 'v8' is possibly undefined
// 3760: variable 'v9' is possibly undefined
// 3760: variable 'v10' is possibly undefined
// 3760: variable 'v11' is possibly undefined
// 3760: variable 'v12' is possibly undefined
// 3760: variable 'v13' is possibly undefined
// 3768: variable 'v14' is possibly undefined

//----- (00003778) --------------------------------------------------------
_QWORD *__fastcall sub_3778(_QWORD *result)
{
  __int64 v1; // d0
  __int64 v2; // d1
  __int64 v3; // d2
  __int64 v4; // d3
  __int64 v5; // d4
  __int64 v6; // d5
  __int64 v7; // d6
  __int64 v8; // d7
  __int64 v9; // d8
  __int64 v10; // d9
  __int64 v11; // d10
  __int64 v12; // d11
  __int64 v13; // d12
  __int64 v14; // d13
  __int64 v15; // d14
  __int64 v16; // d15

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 3778: variable 'v1' is possibly undefined
// 3778: variable 'v2' is possibly undefined
// 3778: variable 'v3' is possibly undefined
// 3778: variable 'v4' is possibly undefined
// 3778: variable 'v5' is possibly undefined
// 3778: variable 'v6' is possibly undefined
// 3778: variable 'v7' is possibly undefined
// 3778: variable 'v8' is possibly undefined
// 3778: variable 'v9' is possibly undefined
// 3778: variable 'v10' is possibly undefined
// 3778: variable 'v11' is possibly undefined
// 3778: variable 'v12' is possibly undefined
// 3778: variable 'v13' is possibly undefined
// 3778: variable 'v14' is possibly undefined
// 3778: variable 'v15' is possibly undefined
// 3778: variable 'v16' is possibly undefined

//----- (00003780) --------------------------------------------------------
_QWORD *__fastcall sub_3780(_QWORD *result)
{
  __int64 v1; // d0
  __int64 v2; // d1
  __int64 v3; // d2
  __int64 v4; // d3
  __int64 v5; // d4
  __int64 v6; // d5
  __int64 v7; // d6
  __int64 v8; // d7
  __int64 v9; // d8
  __int64 v10; // d9
  __int64 v11; // d10
  __int64 v12; // d11
  __int64 v13; // d12
  __int64 v14; // d13
  __int64 v15; // d14
  __int64 v16; // d15

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 3780: variable 'v1' is possibly undefined
// 3780: variable 'v2' is possibly undefined
// 3780: variable 'v3' is possibly undefined
// 3780: variable 'v4' is possibly undefined
// 3780: variable 'v5' is possibly undefined
// 3780: variable 'v6' is possibly undefined
// 3780: variable 'v7' is possibly undefined
// 3780: variable 'v8' is possibly undefined
// 3780: variable 'v9' is possibly undefined
// 3780: variable 'v10' is possibly undefined
// 3780: variable 'v11' is possibly undefined
// 3780: variable 'v12' is possibly undefined
// 3780: variable 'v13' is possibly undefined
// 3780: variable 'v14' is possibly undefined
// 3780: variable 'v15' is possibly undefined
// 3780: variable 'v16' is possibly undefined

//----- (00003788) --------------------------------------------------------
_QWORD *__fastcall sub_3788(_QWORD *result)
{
  __int64 v1; // d16
  __int64 v2; // d17
  __int64 v3; // d18
  __int64 v4; // d19
  __int64 v5; // d20
  __int64 v6; // d21
  __int64 v7; // d22
  __int64 v8; // d23
  __int64 v9; // d24
  __int64 v10; // d25
  __int64 v11; // d26
  __int64 v12; // d27
  __int64 v13; // d28
  __int64 v14; // d29
  __int64 v15; // d30
  __int64 v16; // d31

  *result = v1;
  result[1] = v2;
  result[2] = v3;
  result[3] = v4;
  result[4] = v5;
  result[5] = v6;
  result[6] = v7;
  result[7] = v8;
  result[8] = v9;
  result[9] = v10;
  result[10] = v11;
  result[11] = v12;
  result[12] = v13;
  result[13] = v14;
  result[14] = v15;
  result[15] = v16;
  return result;
}
// 3788: variable 'v1' is possibly undefined
// 3788: variable 'v2' is possibly undefined
// 3788: variable 'v3' is possibly undefined
// 3788: variable 'v4' is possibly undefined
// 3788: variable 'v5' is possibly undefined
// 3788: variable 'v6' is possibly undefined
// 3788: variable 'v7' is possibly undefined
// 3788: variable 'v8' is possibly undefined
// 3788: variable 'v9' is possibly undefined
// 3788: variable 'v10' is possibly undefined
// 3788: variable 'v11' is possibly undefined
// 3788: variable 'v12' is possibly undefined
// 3788: variable 'v13' is possibly undefined
// 3788: variable 'v14' is possibly undefined
// 3788: variable 'v15' is possibly undefined
// 3788: variable 'v16' is possibly undefined

//----- (00003790) --------------------------------------------------------
void sub_3790()
{
  __asm
  {
    STCL            p1, c0, [R0],#8
    STCL            p1, c1, [R0],#8
    STCL            p1, c2, [R0],#8
    STCL            p1, c3, [R0],#8
    STCL            p1, c4, [R0],#8
    STCL            p1, c5, [R0],#8
    STCL            p1, c6, [R0],#8
    STCL            p1, c7, [R0],#8
    STCL            p1, c8, [R0],#8
    STCL            p1, c9, [R0],#8
    STCL            p1, c10, [R0],#8
    STCL            p1, c11, [R0],#8
    STCL            p1, c12, [R0],#8
    STCL            p1, c13, [R0],#8
    STCL            p1, c14, [R0],#8
    STCL            p1, c15, [R0],#8
  }
}

//----- (000037D4) --------------------------------------------------------
void sub_37D4()
{
  __asm
  {
    STC2            p1, c8, [R0],#4
    STC2            p1, c9, [R0],#4
    STC2            p1, c10, [R0],#4
    STC2            p1, c11, [R0],#4
  }
}

//----- (000037E8) --------------------------------------------------------
int __fastcall sub_37E8(int a1, const void *a2)
{
  *(_DWORD *)a1 = &off_6DB4;
  *(_DWORD *)(a1 + 4) = &unk_7068;
  *(_BYTE *)(a1 + 76) = 0;
  *(_DWORD *)(a1 + 72) = 0;
  qmemcpy((void *)(a1 + 8), a2, 0x40u);
  memset((void *)(a1 + 80), 0, 0x1C2u);
  sub_3D04((int *)a1, 0);
  return 0;
}
// 6DB4: using guessed type void *;

//----- (0000382C) --------------------------------------------------------
int __fastcall sub_382C(int a1, int a2, _DWORD *a3)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 8))(a1) != 1 )
    return -6542;
  *a3 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 12))(a1, a2);
  return 0;
}

//----- (0000385A) --------------------------------------------------------
int __fastcall sub_385A(int a1, int a2, int a3)
{
  int v6; // r5

  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 8))(a1) != 1 )
    return -6542;
  (*(void (__fastcall **)(int, int, int))(*(_DWORD *)a1 + 16))(a1, a2, a3);
  if ( a2 != -1 )
    return 0;
  v6 = 0;
  (*(void (__fastcall **)(int, _DWORD))(*(_DWORD *)a1 + 52))(a1, 0);
  return v6;
}

//----- (0000389E) --------------------------------------------------------
int __fastcall sub_389E(int a1, int a2, _QWORD *a3)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 20))(a1) != 1 )
    return -6542;
  *a3 = ((__int64 (__fastcall *)(int, int))*(_DWORD *)(*(_DWORD *)a1 + 24))(a1, a2);
  return 0;
}

//----- (000038CE) --------------------------------------------------------
int __fastcall sub_38CE(int a1, int a2, int a3, int a4)
{
  if ( (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 20))(a1) != 1 )
    return -6542;
  (*(void (__fastcall **)(int, int, int, int))(*(_DWORD *)a1 + 28))(a1, a2, a3, a4);
  return 0;
}

//----- (00003906) --------------------------------------------------------
int __fastcall sub_3906(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 32))(a1);
}

//----- (0000390C) --------------------------------------------------------
int __fastcall sub_390C(int a1, int a2)
{
  int result; // r0

  (*(void (__fastcall **)(int, int))(*(_DWORD *)a1 + 36))(a1, a2);
  result = 0;
  if ( !*(_DWORD *)(a2 + 4) )
    return -6549;
  return result;
}

//----- (0000392A) --------------------------------------------------------
int __fastcall sub_392A(int a1)
{
  (*(void (__fastcall **)(int))(*(_DWORD *)a1 + 40))(a1);
  return -6540;
}

//----- (0000393C) --------------------------------------------------------
int __fastcall sub_393C(int a1)
{
  return (*(int (__fastcall **)(int))(*(_DWORD *)a1 + 60))(a1);
}

//----- (00003942) --------------------------------------------------------
int __fastcall sub_3942(int a1, int a2)
{
  int v2; // r2
  bool v3; // zf
  int v4; // r0
  unsigned int v5; // r1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFFC) == 192;
  v4 = 0;
  v5 = a2 - 16;
  if ( v3 )
    v4 = 1;
  if ( v5 > 0xFFFFFFED )
    v2 = 1;
  return v4 | v2;
}

//----- (00003964) --------------------------------------------------------
int __fastcall sub_3964(int a1, int a2)
{
  int v4; // r0

  if ( a2 > 12 )
  {
    if ( a2 != 15 )
    {
      if ( a2 == 14 )
      {
        v4 = a1 + 64;
        return *(_DWORD *)v4;
      }
      if ( a2 != 13 )
        goto LABEL_11;
LABEL_9:
      v4 = a1 + 60;
      return *(_DWORD *)v4;
    }
    goto LABEL_8;
  }
  if ( a2 == -2 )
    goto LABEL_9;
  if ( a2 == -1 )
  {
LABEL_8:
    v4 = a1 + 68;
    return *(_DWORD *)v4;
  }
LABEL_11:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_3D84(
        "uint32_t libunwind::Registers_arm::getRegister(int)",
        "external/libunwind_llvm/src/Registers.hpp",
        1452,
        "unsupported arm register");
    if ( !*(_BYTE *)(a1 + 76) )
    {
      *(_BYTE *)(a1 + 76) = 1;
      sub_37D4();
    }
    v4 = a1 + 4 * a2 - 296;
  }
  else
  {
    v4 = a1 + 4 * a2 + 8;
  }
  return *(_DWORD *)v4;
}

//----- (000039F0) --------------------------------------------------------
int __fastcall sub_39F0(int result, int a2, int a3)
{
  int v5; // r5

  v5 = result;
  if ( a2 <= 12 )
  {
    if ( a2 == -2 )
      goto LABEL_9;
    if ( a2 != -1 )
      goto LABEL_11;
LABEL_8:
    *(_DWORD *)(result + 68) = a3;
    return result;
  }
  switch ( a2 )
  {
    case 15:
      goto LABEL_8;
    case 14:
      *(_DWORD *)(result + 64) = a3;
      return result;
    case 13:
LABEL_9:
      *(_DWORD *)(result + 60) = a3;
      return result;
  }
LABEL_11:
  if ( (unsigned int)a2 > 0xC )
  {
    if ( (a2 & 0xFFFFFFFC) != 192 )
      sub_3D84(
        "void libunwind::Registers_arm::setRegister(int, uint32_t)",
        "external/libunwind_llvm/src/Registers.hpp",
        1471,
        "unsupported arm register");
    if ( !*(_BYTE *)(result + 76) )
    {
      *(_BYTE *)(result + 76) = 1;
      sub_37D4();
    }
    result = v5 + 4 * a2;
    *(_DWORD *)(result - 296) = a3;
  }
  else
  {
    result += 4 * a2;
    *(_DWORD *)(result + 8) = a3;
  }
  return result;
}

//----- (00003A7C) --------------------------------------------------------
int __fastcall sub_3A7C(int a1, int a2)
{
  int v2; // r2
  bool v3; // zf
  int v4; // r0
  unsigned int v5; // r1

  v2 = 0;
  v3 = (a2 & 0xFFFFFFF0) == 112;
  v4 = 0;
  v5 = a2 & 0xFFFFFFE0;
  if ( v3 )
    v4 = 1;
  if ( v5 == 256 )
    v2 = 1;
  return v4 | v2;
}

//----- (00003AA0) --------------------------------------------------------
__int64 __fastcall sub_3AA0(int a1, int a2)
{
  unsigned int v4; // r0
  _QWORD *v5; // r0
  int v6; // r0

  v4 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(a1 + 75) )
    {
      *(_BYTE *)(a1 + 75) = 1;
      sub_3790();
    }
    v6 = a1 + 8 * a2 - 552;
  }
  else if ( v4 == 272 )
  {
    if ( !*(_BYTE *)(a1 + 74) )
    {
      *(_BYTE *)(a1 + 74) = 1;
      sub_3788((_QWORD *)(a1 + 216));
    }
    v6 = a1 + 8 * a2 - 1960;
  }
  else
  {
    if ( v4 != 256 )
      sub_3D84(
        "unw_fpreg_t libunwind::Registers_arm::getFloatRegister(int)",
        "external/libunwind_llvm/src/Registers.hpp",
        1673,
        "Unknown ARM float register");
    if ( !*(_BYTE *)(a1 + 73) )
    {
      *(_BYTE *)(a1 + 73) = 1;
      v5 = (_QWORD *)(a1 + 80);
      if ( *(_BYTE *)(a1 + 72) )
        sub_3780(v5);
      else
        sub_3778(v5);
    }
    v6 = a1 + 8 * a2 - 1968;
  }
  return *(_QWORD *)v6;
}

//----- (00003B44) --------------------------------------------------------
int __fastcall sub_3B44(int a1, int a2, int a3, int a4)
{
  unsigned int v6; // r0
  _QWORD *v9; // r0
  int result; // r0
  int v11; // r1

  v6 = a2 & 0xFFFFFFF0;
  if ( (a2 & 0xFFFFFFF0) == 112 )
  {
    if ( !*(_BYTE *)(a1 + 75) )
    {
      *(_BYTE *)(a1 + 75) = 1;
      sub_3790();
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 548) = a4;
    LOWORD(v11) = -552;
  }
  else if ( v6 == 272 )
  {
    if ( !*(_BYTE *)(a1 + 74) )
    {
      *(_BYTE *)(a1 + 74) = 1;
      sub_3788((_QWORD *)(a1 + 216));
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 1956) = a4;
    LOWORD(v11) = -1960;
  }
  else
  {
    if ( v6 != 256 )
      sub_3D84(
        "void libunwind::Registers_arm::setFloatRegister(int, unw_fpreg_t)",
        "external/libunwind_llvm/src/Registers.hpp",
        1700,
        "Unknown ARM float register");
    if ( !*(_BYTE *)(a1 + 73) )
    {
      *(_BYTE *)(a1 + 73) = 1;
      v9 = (_QWORD *)(a1 + 80);
      if ( *(_BYTE *)(a1 + 72) )
        sub_3780(v9);
      else
        sub_3778(v9);
    }
    result = a1 + 8 * a2;
    *(_DWORD *)(result - 1964) = a4;
    LOWORD(v11) = -1968;
  }
  HIWORD(v11) = -1;
  *(_DWORD *)(result + v11) = a3;
  return result;
}

//----- (00003C10) --------------------------------------------------------
int __fastcall sub_3C10(_DWORD *a1)
{
  int result; // r0
  __int64 v3; // kr00_8
  int v4; // r0

  if ( *((_BYTE *)a1 + 528) )
    return 0;
  result = sub_3DB0((int)a1);
  if ( result != 1 )
    return result;
  (*(void (__fastcall **)(_DWORD *, int))(*a1 + 52))(a1, 1);
  if ( *((_BYTE *)a1 + 528) )
    return 0;
  if ( a1[126] )
  {
    v3 = *(_QWORD *)(*a1 + 12);
    v4 = ((int (__fastcall *)(_DWORD *, int))v3)(a1, -2);
    ((void (__fastcall *)(_DWORD *, int, int))HIDWORD(v3))(a1, -2, a1[126] + v4);
  }
  return 1;
}

//----- (00003C60) --------------------------------------------------------
_DWORD *__fastcall sub_3C60(int a1, _DWORD *a2)
{
  int *v2; // r0
  _DWORD *result; // r0
  int v4; // r2
  int v5; // r3
  int v6; // r4
  int v7; // r12
  int v8; // lr
  _DWORD *v9; // r1
  int v10; // r3
  int v11; // r4
  int v12; // r12
  int v13; // lr

  v2 = (int *)(a1 + 488);
  v4 = *v2;
  v5 = v2[1];
  v6 = v2[2];
  v7 = v2[3];
  v8 = v2[4];
  result = v2 + 5;
  *a2 = v4;
  a2[1] = v5;
  a2[2] = v6;
  a2[3] = v7;
  a2[4] = v8;
  v9 = a2 + 5;
  v10 = result[1];
  v11 = result[2];
  v12 = result[3];
  v13 = result[4];
  *v9 = *result;
  v9[1] = v10;
  v9[2] = v11;
  v9[3] = v12;
  v9[4] = v13;
  return result;
}

//----- (00003C78) --------------------------------------------------------
int __fastcall sub_3C78(int a1)
{
  int v1; // r4

  v1 = a1 + 8;
  sub_3E04(a1 + 8);
  return sub_4554(v1);
}

//----- (00003C8E) --------------------------------------------------------
int __fastcall sub_3C8E(int a1)
{
  return *(unsigned __int8 *)(a1 + 529);
}

//----- (00003C94) --------------------------------------------------------
int __fastcall sub_3C94(int a1, int a2, int a3, _DWORD *a4)
{
  int v7; // r7
  char v9[8]; // [sp+8h] [bp-28h] BYREF
  const char *v10; // [sp+10h] [bp-20h]
  int v11; // [sp+14h] [bp-1Ch]

  v7 = (*(int (__fastcall **)(int, int))(*(_DWORD *)a1 + 12))(a1, -1);
  if ( !dladdr(v7, v9) || !v10 )
    return 0;
  _snprintf_chk(a2, a3, 0, -1, "%s", v10);
  *a4 = v7 - v11;
  return 1;
}
// 1A58: using guessed type int __fastcall dladdr(_DWORD, _DWORD);
// 1A64: using guessed type int _snprintf_chk(_DWORD, _DWORD, _DWORD, _DWORD, const char *, ...);
// 3C94: using guessed type char var_28[8];

//----- (00003D04) --------------------------------------------------------
int __fastcall sub_3D04(int *a1, int a2)
{
  int v4; // r5
  int v6[2]; // [sp+0h] [bp-20h] BYREF
  int v7[6]; // [sp+8h] [bp-18h] BYREF

  v4 = (*(int (__fastcall **)(int *, int))(*a1 + 12))(a1, -1) & 0xFFFFFFFE;
  v7[0] = 0;
  if ( a2 )
    --v4;
  v6[0] = _gnu_Unwind_Find_exidx(v4, v7);
  v6[1] = v7[0];
  if ( !v6[0] || !v7[0] || !sub_3E5C(a1, v4, v6) )
    *((_BYTE *)a1 + 528) = 1;
  return _stack_chk_guard - v7[1];
}
// 1A70: using guessed type int __fastcall _gnu_Unwind_Find_exidx(_DWORD, _DWORD);

//----- (00003D7A) --------------------------------------------------------
int __fastcall sub_3D7A(int result)
{
  *(_BYTE *)(result + 72) = 1;
  return result;
}

//----- (00003D84) --------------------------------------------------------
void __fastcall __noreturn sub_3D84(const char *a1, const char *a2, int a3, const char *a4)
{
  fprintf(stderr, "libunwind: %s %s:%d - %s\n", a1, a2, a3, a4);
  abort();
}

//----- (00003DB0) --------------------------------------------------------
int __fastcall sub_3DB0(int a1)
{
  int v2; // r4
  unsigned int *v3; // r0
  unsigned int v5; // [sp+4h] [bp-1Ch] BYREF
  unsigned int v6; // [sp+8h] [bp-18h] BYREF

  v2 = 0;
  v5 = 0;
  v6 = 0;
  v3 = sub_2EE8(*(unsigned int **)(a1 + 520), (int *)&v5, (int *)&v6);
  if ( sub_2F3C(a1, (int)v3, v5, v6) == 8 )
    return 1;
  return v2;
}

//----- (00003E04) --------------------------------------------------------
_DWORD *__fastcall sub_3E04(int a1)
{
  int v2; // r0
  _DWORD *result; // r0

  if ( *(_BYTE *)(a1 + 65) )
  {
    if ( *(_BYTE *)(a1 + 64) )
      sub_44AC();
    else
      sub_44A4();
  }
  if ( (unsigned __int8)*(_WORD *)(a1 + 66) )
  {
    sub_44B4();
    v2 = *(unsigned __int8 *)(a1 + 67);
  }
  else
  {
    v2 = HIBYTE(*(unsigned __int16 *)(a1 + 66));
  }
  if ( v2 )
    sub_44BC((int *)(a1 + 336));
  result = (_DWORD *)*(unsigned __int8 *)(a1 + 68);
  if ( *(_BYTE *)(a1 + 68) )
    return sub_4564((int *)(a1 + 464));
  return result;
}

//----- (00003E5C) --------------------------------------------------------
int __fastcall sub_3E5C(int *a1, int a2, _DWORD *a3)
{
  int v4; // r5
  int v5; // r6
  char *v6; // r1
  int *v7; // r0
  int v8; // r5
  int v9; // r7
  unsigned int v10; // r6
  int v11; // r12
  char *v12; // lr
  int v13; // r9
  int v14; // r6
  int v15; // r6
  int v16; // r3
  int v17; // r7
  int v19[3]; // [sp+14h] [bp-34h] BYREF
  int v20; // [sp+20h] [bp-28h] BYREF

  v4 = 0;
  v20 = a2;
  v5 = a3[1];
  sub_4000(v19, 0, a1[1], a3, v5, a1[1], (int)a3, &v20);
  if ( !v19[0] || v19[0] == v5 )
    return v4;
  v6 = (char *)(*(_DWORD *)v19[2] + 8 * v19[0]);
  v7 = (int *)(v6 - 4);
  v8 = *(_DWORD *)v6;
  if ( v6 == &byte_4 )
    return 0;
  v9 = *v7;
  if ( *v7 == 1 )
    return 0;
  if ( v9 < 0 )
  {
    v11 = 1;
    goto LABEL_11;
  }
  v10 = (2 * v9) & 0x80000000 | v9;
  v9 = *(int *)((char *)v7 + v10);
  v7 = (int *)((char *)v7 + v10);
  if ( v9 <= -1 )
  {
    v11 = 0;
LABEL_11:
    v14 = HIBYTE(v9) & 0xF;
    if ( v14 == 2 )
    {
      v12 = byte_34C5;
      v15 = 1;
    }
    else
    {
      if ( v14 != 1 )
      {
        if ( v14 )
          sub_3D84(
            "bool libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::getInfoFromEHABISectio"
            "n(pint_t, const libunwind::UnwindInfoSections &) [A = libunwind::LocalAddressSpace, R = libunwind::Registers_arm]",
            "external/libunwind_llvm/src/UnwindCursor.hpp",
            776,
            "unknown personality routine");
        v13 = (int)(v7 + 1);
        if ( v11 )
          v13 = 0;
        v12 = byte_3459;
        goto LABEL_17;
      }
      v12 = byte_34BD;
      v15 = 0;
    }
    v16 = BYTE2(v9);
    v17 = v16;
    if ( v16 )
      v17 = 1;
    if ( (v17 & v11) == 1 )
      sub_3D84(
        "bool libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_arm>::getInfoFromEHABISection(pi"
        "nt_t, const libunwind::UnwindInfoSections &) [A = libunwind::LocalAddressSpace, R = libunwind::Registers_arm]",
        "external/libunwind_llvm/src/UnwindCursor.hpp",
        783,
        "index inlined table detected but pr function requires extra words");
    v13 = (int)&v7[v16 + 1];
    goto LABEL_24;
  }
  v11 = 0;
  v12 = (char *)v7 + (v9 | (2 * v9) & 0x80000000);
  v13 = (int)&v7[HIBYTE(v7[1]) + 2];
LABEL_17:
  v15 = 0;
LABEL_24:
  a1[122] = (int)&v6[((2 * *((_DWORD *)v6 - 2)) & 0x80000000 | *((_DWORD *)v6 - 2)) - 8];
  a1[123] = (int)&v6[v8 | (2 * v8) & 0x80000000];
  v4 = 1;
  a1[130] = (int)v7;
  a1[124] = v13;
  a1[125] = (int)v12;
  if ( v15 )
    v15 = 2;
  if ( v11 )
    v15 = 1;
  a1[127] = v15;
  return v4;
}
// 4: using guessed type char;

//----- (00004000) --------------------------------------------------------
_DWORD *__fastcall sub_4000(_DWORD *a1, int a2, int a3, _DWORD *a4, int a5, int a6, int a7, _DWORD *a8)
{
  unsigned int v8; // r4
  unsigned int v9; // r5
  int v10; // r6

  v8 = a5 - a2;
  while ( 1 )
  {
    v9 = v8;
    if ( !v8 )
      break;
    v10 = a2 + (v8 >> 1);
    v8 >>= 1;
    if ( *a8 >= *a4 + 8 * v10 + ((2 * *(_DWORD *)(*a4 + 8 * v10)) & 0x80000000 | *(_DWORD *)(*a4 + 8 * v10)) )
    {
      v8 = v9 - 1 - v8;
      a2 = v10 + 1;
    }
  }
  *a1 = a2;
  a1[1] = a3;
  a1[2] = a4;
  return a1 + 3;
}

//----- (00004490) --------------------------------------------------------
int __fastcall sub_4490(int a1)
{
  return (*(int (__fastcall **)(_DWORD, _DWORD, _DWORD, _DWORD))(a1 + 60))(
           *(_DWORD *)a1,
           *(_DWORD *)(a1 + 4),
           *(_DWORD *)(a1 + 8),
           *(_DWORD *)(a1 + 12));
}

//----- (000044A4) --------------------------------------------------------
void sub_44A4()
{
  ;
}

//----- (000044AC) --------------------------------------------------------
void sub_44AC()
{
  ;
}

//----- (000044B4) --------------------------------------------------------
void sub_44B4()
{
  ;
}

//----- (000044BC) --------------------------------------------------------
_DWORD *__fastcall sub_44BC(int *a1)
{
  int *v5; // r0
  _DWORD *result; // r0

  _T1 = *a1;
  v5 = a1 + 2;
  __asm { LDCL            p1, c0, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c1, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c2, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c3, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c4, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c5, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c6, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c7, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c8, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c9, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c10, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c11, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c12, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c13, [R0],#8 }
  _T1 = *v5;
  v5 += 2;
  __asm { LDCL            p1, c14, [R0],#8 }
  _T1 = *v5;
  result = v5 + 2;
  __asm { LDCL            p1, c15, [R0],#8 }
  return result;
}

//----- (00004500) --------------------------------------------------------
_DWORD *__fastcall sub_4500(int *a1)
{
  int *v5; // r0
  _DWORD *result; // r0

  _T1 = *a1;
  v5 = a1 + 1;
  __asm { LDC2            p1, c8, [R0],#4 }
  _T1 = *v5++;
  __asm { LDC2            p1, c9, [R0],#4 }
  _T1 = *v5++;
  __asm { LDC2            p1, c10, [R0],#4 }
  _T1 = *v5;
  result = v5 + 1;
  __asm { LDC2            p1, c11, [R0],#4 }
  return result;
}

//----- (00004514) --------------------------------------------------------
// attributes: thunk
int __fastcall j_j_RilAimsOpen(int a1)
{
  return j_RilAimsOpen(a1);
}

//----- (00004524) --------------------------------------------------------
// attributes: thunk
void __fastcall operator delete(void *a1)
{
  _ZdlPv(a1);
}

//----- (00004534) --------------------------------------------------------
// attributes: thunk
void __fastcall j_ProductFeature::~ProductFeature(ProductFeature *this)
{
  ProductFeature::~ProductFeature(this);
}

//----- (00004544) --------------------------------------------------------
// attributes: thunk
int __fastcall j___cxa_atexit(void (__fastcall *lpfunc)(void *), void *obj, void *lpdso_handle)
{
  return _cxa_atexit(lpfunc, obj, lpdso_handle);
}

//----- (00004554) --------------------------------------------------------
// attributes: thunk
int __fastcall sub_4554(int a1)
{
  return sub_4490(a1);
}

//----- (00004564) --------------------------------------------------------
// attributes: thunk
_DWORD *__fastcall sub_4564(int *a1)
{
  return sub_4500(a1);
}

// nfuncs=183 queued=143 decompiled=143 lumina nreq=0 worse=0 better=0
// ALL OK, 143 function(s) have been successfully decompiled
